"""Audit a moment-relaxation point against one exact common instrument.

The reduced Choi moment programmes report first-moment Bloch coordinates for
the four prefix states and all sixteen conditioned outputs.  Those coordinates
need not themselves be generated by the first-moment Choi matrices when the
moment matrix has rank greater than one.  This script performs two independent
checks on the reported family:

1. all flagged trace-norm data-processing comparisons on the requested scale
   grid; and
2. Euclidean projection onto the exact fixed-input Choi-compatible output set,
   followed by a separating support SDP.

The resulting gap is a solver-conditional obstruction to the relaxation point,
not a global upper bound on the original frontier.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from carmenq.common_instrument import (
    project_to_common_instrument,
    scan_flagged_trace_norm_cuts,
)


PAULIS = np.asarray(
    [
        [[1.0, 0.0], [0.0, 1.0]],
        [[0.0, 1.0], [1.0, 0.0]],
        [[0.0, -1j], [1j, 0.0]],
        [[1.0, 0.0], [0.0, -1.0]],
    ],
    dtype=complex,
)


def matrix_from_bloch(coefficients: np.ndarray) -> np.ndarray:
    value = np.asarray(coefficients, dtype=float)
    if value.shape != (4,):
        raise ValueError("a qubit Bloch coefficient vector has length four")
    return np.tensordot(value, PAULIS, axes=1) / 2.0


def load_reported_family(payload: dict[str, object]) -> tuple[np.ndarray, np.ndarray]:
    prefix = np.asarray(payload["prefix_bloch_coefficients"], dtype=float)
    probabilities = np.asarray(payload["path_probabilities"], dtype=float)
    vectors = np.asarray(payload["conditioned_output_bloch_vectors"], dtype=float)
    if prefix.shape != (4, 4):
        raise ValueError("expected four reported prefix Bloch vectors")
    if probabilities.shape != (4, 4) or vectors.shape != (4, 4, 3):
        raise ValueError("expected sixteen reported conditioned outputs")
    states = np.asarray([matrix_from_bloch(item) for item in prefix])
    outputs = np.asarray(
        [
            [
                matrix_from_bloch(
                    np.concatenate(([probabilities[z, y]], vectors[z, y]))
                )
                for y in range(4)
            ]
            for z in range(4)
        ]
    )
    return states, outputs


def audit_payload(
    payload: dict[str, object],
    scales: tuple[float, ...],
    solver: str | None = None,
) -> tuple[dict[str, object], dict[str, np.ndarray]]:
    states, outputs = load_reported_family(payload)
    cuts = scan_flagged_trace_norm_cuts(states, outputs, scales=scales)
    worst = min(cuts, key=lambda item: item.slack)
    projection = project_to_common_instrument(states, outputs, solver=solver)
    report = {
        "source_weight": payload.get("weight"),
        "source_bound": payload.get("bound"),
        "source_terminal_effect_weights": payload.get("terminal_effect_weights"),
        "scales": list(scales),
        "worst_flagged_cut": {
            "input_pair": list(worst.input_pair),
            "scale": worst.scale,
            "input_trace_norm": worst.input_trace_norm,
            "output_trace_norm": worst.output_trace_norm,
            "slack": worst.slack,
            "violation": worst.violation,
        },
        "negative_flagged_cut_count": sum(cut.slack < -1e-8 for cut in cuts),
        "total_flagged_cut_count": len(cuts),
        "choi_projection": {
            "status": projection.status,
            "solver": projection.solver,
            "distance": projection.distance,
            "squared_distance": projection.squared_distance,
            "candidate_witness_value": projection.candidate_witness_value,
            "compatible_support_value": projection.compatible_support_value,
            "separation_gap": projection.separation_gap,
            "trace_preservation_residual": projection.trace_preservation_residual,
            "minimum_choi_eigenvalue": projection.minimum_choi_eigenvalue,
            "compatible_at_1e-7": projection.is_compatible(1e-7),
            "input_lipschitz_constants": projection.input_lipschitz_constants.tolist(),
            "uniform_input_trace_radius_budget": projection.uniform_input_radius_budget,
        },
        "interpretation": (
            "solver-conditional incompatibility audit of the reported "
            "first-moment family; not a global frontier certificate"
        ),
    }
    arrays = {
        "prefix_states": states,
        "candidate_outputs": outputs,
        "nearest_compatible_outputs": projection.projected_outputs,
        "choi_matrices": projection.choi_matrices,
        "separating_witness": projection.witness,
    }
    return report, arrays


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument(
        "--scale",
        type=float,
        action="append",
        default=None,
        help="repeatable flagged-channel comparison scale",
    )
    parser.add_argument("--solver")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    scales = tuple(
        (0.25, 0.5, 1.0, 2.0, 4.0) if args.scale is None else args.scale
    )
    if not scales or any(not np.isfinite(item) or item < 0.0 for item in scales):
        raise ValueError("scales must be finite and nonnegative")
    payload = json.loads(args.input.read_text(encoding="utf-8"))
    report, arrays = audit_payload(payload, scales, args.solver)
    rendered = json.dumps(report, indent=2) + "\n"
    print(rendered, end="")
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
        np.savez_compressed(args.output.with_suffix(".npz"), **arrays)


if __name__ == "__main__":
    main()
