"""CARMEN-Q: causal audit-return quantum-memory benchmarks.

The top-level API exposes concise names for routine use while retaining the
long-form scientific function names used in the accompanying manuscript.
"""

from .audit_return import (
    BenchmarkCounts,
    CertificationResult,
    FrontierPoint,
    PhenomenologicalNoise,
    PowerPlan,
    certify_classical_memory,
    classical_memory_bound,
    classical_memory_frontier,
    collective_classical_record_bound,
    plan_experiment,
    return_curve,
    score,
    simulate_counts,
    weighted_hoeffding_radius,
)
from .protocol import (
    NoiseModel,
    ProtocolConfig,
    ProtocolResult,
    conditional_record_information,
    environment_conditional_information,
    run_protocol,
)
from .common_instrument import (
    BasisInstrumentReconstruction,
    BasisPovmReconstruction,
    CommonInstrumentProjection,
    FlaggedTraceNormCut,
    comparison_scale_grid,
    common_instrument_witness_lipschitz_constants,
    conditioned_outputs,
    flagged_trace_norm_cut,
    project_to_common_instrument,
    reconstruct_common_instrument_from_basis,
    reconstruct_effective_povm_from_basis,
    robust_common_instrument_witness_bound,
    scan_flagged_trace_norm_cuts,
)
from .order_sensitive import (
    GROUPED_CHECK_MATRIX,
    INTERLEAVED_BALANCED_COUNTEREXAMPLE,
    INTERLEAVED_CHECK_MATRIX,
    INTERLEAVED_ORDER_GAP_WEIGHT_THRESHOLD,
    INTERLEAVED_PERFECT_AUDIT_ENDPOINT,
    GroupedFrontierPoint,
    InterleavedCandidatePoint,
    InterleavedCompactCandidatePoint,
    InterleavedFourEffectCandidatePoint,
    PerfectAuditEndpoint,
    StoredCounterexamplePoint,
    full_crossing_cuts,
    full_crossing_perfect_audit_return_bound,
    full_rank_block_packing_number,
    full_rank_block_approximate_audit_return_bound,
    full_rank_block_perfect_audit_return_bound,
    gf2_rank,
    grouped_frontier,
    interleaved_best_known_lower_bound,
    interleaved_candidate_lower_bound,
    interleaved_candidate_scores,
    interleaved_compact_lower_bound,
    interleaved_four_effect_lower_bound,
    interleaved_return_upper_bound,
    interleaved_support_upper_bound,
    ordered_check_perfect_audit_return_bound,
    rank_two_static_qubit_support,
    trellis_connectivity_profile,
    trellis_connectivity_tau,
)

# Concise public aliases. The descriptive originals remain part of the API.
streaming_bound = classical_memory_bound
collective_bound = collective_classical_record_bound
certify = certify_classical_memory
plan = plan_experiment

__all__ = [
    "BenchmarkCounts",
    "BasisInstrumentReconstruction",
    "BasisPovmReconstruction",
    "CertificationResult",
    "CommonInstrumentProjection",
    "FrontierPoint",
    "FlaggedTraceNormCut",
    "GROUPED_CHECK_MATRIX",
    "GroupedFrontierPoint",
    "INTERLEAVED_BALANCED_COUNTEREXAMPLE",
    "INTERLEAVED_CHECK_MATRIX",
    "INTERLEAVED_ORDER_GAP_WEIGHT_THRESHOLD",
    "INTERLEAVED_PERFECT_AUDIT_ENDPOINT",
    "InterleavedCandidatePoint",
    "InterleavedCompactCandidatePoint",
    "InterleavedFourEffectCandidatePoint",
    "NoiseModel",
    "PhenomenologicalNoise",
    "PowerPlan",
    "PerfectAuditEndpoint",
    "ProtocolConfig",
    "ProtocolResult",
    "StoredCounterexamplePoint",
    "certify",
    "certify_classical_memory",
    "classical_memory_bound",
    "classical_memory_frontier",
    "collective_bound",
    "collective_classical_record_bound",
    "comparison_scale_grid",
    "common_instrument_witness_lipschitz_constants",
    "conditioned_outputs",
    "conditional_record_information",
    "environment_conditional_information",
    "flagged_trace_norm_cut",
    "full_crossing_cuts",
    "full_crossing_perfect_audit_return_bound",
    "full_rank_block_packing_number",
    "full_rank_block_approximate_audit_return_bound",
    "full_rank_block_perfect_audit_return_bound",
    "gf2_rank",
    "grouped_frontier",
    "interleaved_best_known_lower_bound",
    "interleaved_candidate_lower_bound",
    "interleaved_candidate_scores",
    "interleaved_compact_lower_bound",
    "interleaved_four_effect_lower_bound",
    "interleaved_return_upper_bound",
    "interleaved_support_upper_bound",
    "ordered_check_perfect_audit_return_bound",
    "plan",
    "plan_experiment",
    "project_to_common_instrument",
    "reconstruct_common_instrument_from_basis",
    "reconstruct_effective_povm_from_basis",
    "robust_common_instrument_witness_bound",
    "return_curve",
    "rank_two_static_qubit_support",
    "run_protocol",
    "score",
    "simulate_counts",
    "scan_flagged_trace_norm_cuts",
    "streaming_bound",
    "trellis_connectivity_profile",
    "trellis_connectivity_tau",
    "weighted_hoeffding_radius",
]

__version__ = "2.2.0"
