import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 201 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row207 : Fin 3173 := ⟨207, by decide⟩
private def row301 : Fin 3173 := ⟨301, by decide⟩
private def row458 : Fin 3173 := ⟨458, by decide⟩
private def row474 : Fin 3173 := ⟨474, by decide⟩
private def row497 : Fin 3173 := ⟨497, by decide⟩
private def row498 : Fin 3173 := ⟨498, by decide⟩
private def row759 : Fin 3173 := ⟨759, by decide⟩
private def row760 : Fin 3173 := ⟨760, by decide⟩

def source15818ObjectiveCoord201 : ℚ := q 0 1

def source15818Column201 : Array (RayEntry 3173) := #[
  { row := row207, value := q (-1) 1 },
  { row := row301, value := q 1 1 },
  { row := row458, value := q 4654212870180819 9007199254740992 },
  { row := row474, value := q (-1166755391775585) 2251799813685248 },
  { row := row497, value := q 1166755391775585 2251799813685248 },
  { row := row498, value := q (-4654212870180819) 9007199254740992 },
  { row := row759, value := q (-5404319552844595) 9007199254740992 },
  { row := row760, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue201 : ℚ :=
  source15818Column201.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord201

theorem source15818StationarityValue201Zero :
    source15818StationarityValue201 = 0 := by
  decide +kernel

end CarmenQExact
