import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity232
import CarmenQExact.Source15818Stationarity233
import CarmenQExact.Source15818Stationarity234
import CarmenQExact.Source15818Stationarity235

/-!
# Stationarity bridge shard 58 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn232 :
    stationarityAt source15818Data 232 = 0 := by
  change source15818StationarityValue232 = 0
  exact source15818StationarityValue232Zero

theorem source15818StationarityColumn233 :
    stationarityAt source15818Data 233 = 0 := by
  change source15818StationarityValue233 = 0
  exact source15818StationarityValue233Zero

theorem source15818StationarityColumn234 :
    stationarityAt source15818Data 234 = 0 := by
  change source15818StationarityValue234 = 0
  exact source15818StationarityValue234Zero

theorem source15818StationarityColumn235 :
    stationarityAt source15818Data 235 = 0 := by
  change source15818StationarityValue235 = 0
  exact source15818StationarityValue235Zero

end CarmenQExact
