import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 255 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row261 : Fin 3173 := ⟨261, by decide⟩
private def row777 : Fin 3173 := ⟨777, by decide⟩
private def row778 : Fin 3173 := ⟨778, by decide⟩
private def row779 : Fin 3173 := ⟨779, by decide⟩
private def row780 : Fin 3173 := ⟨780, by decide⟩

def source15818ObjectiveCoord255 : ℚ := q 0 1

def source15818Column255 : Array (RayEntry 3173) := #[
  { row := row261, value := q (-1) 1 },
  { row := row777, value := q 1 1 },
  { row := row778, value := q 1 1 },
  { row := row779, value := q (-5404319552844595) 9007199254740992 },
  { row := row780, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue255 : ℚ :=
  source15818Column255.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord255

theorem source15818StationarityValue255Zero :
    source15818StationarityValue255 = 0 := by
  decide +kernel

end CarmenQExact
