import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 205 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row211 : Fin 3173 := ⟨211, by decide⟩
private def row305 : Fin 3173 := ⟨305, by decide⟩
private def row462 : Fin 3173 := ⟨462, by decide⟩
private def row478 : Fin 3173 := ⟨478, by decide⟩
private def row499 : Fin 3173 := ⟨499, by decide⟩
private def row500 : Fin 3173 := ⟨500, by decide⟩
private def row757 : Fin 3173 := ⟨757, by decide⟩
private def row758 : Fin 3173 := ⟨758, by decide⟩

def source15818ObjectiveCoord205 : ℚ := q 0 1

def source15818Column205 : Array (RayEntry 3173) := #[
  { row := row211, value := q (-1) 1 },
  { row := row305, value := q 1 1 },
  { row := row462, value := q 4654212870180819 9007199254740992 },
  { row := row478, value := q (-4667021567102341) 9007199254740992 },
  { row := row499, value := q 4667021567102341 9007199254740992 },
  { row := row500, value := q (-4654212870180819) 9007199254740992 },
  { row := row757, value := q (-5404319552844595) 9007199254740992 },
  { row := row758, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue205 : ℚ :=
  source15818Column205.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord205

theorem source15818StationarityValue205Zero :
    source15818StationarityValue205 = 0 := by
  decide +kernel

end CarmenQExact
