import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity144
import CarmenQExact.Source15818Stationarity145
import CarmenQExact.Source15818Stationarity146
import CarmenQExact.Source15818Stationarity147

/-!
# Stationarity bridge shard 36 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn144 :
    stationarityAt source15818Data 144 = 0 := by
  change source15818StationarityValue144 = 0
  exact source15818StationarityValue144Zero

theorem source15818StationarityColumn145 :
    stationarityAt source15818Data 145 = 0 := by
  change source15818StationarityValue145 = 0
  exact source15818StationarityValue145Zero

theorem source15818StationarityColumn146 :
    stationarityAt source15818Data 146 = 0 := by
  change source15818StationarityValue146 = 0
  exact source15818StationarityValue146Zero

theorem source15818StationarityColumn147 :
    stationarityAt source15818Data 147 = 0 := by
  change source15818StationarityValue147 = 0
  exact source15818StationarityValue147Zero

end CarmenQExact
