import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity266
import CarmenQExact.Source15818Stationarity267
import CarmenQExact.Source15818Stationarity268
import CarmenQExact.Source15818Stationarity269

/-!
# Stationarity bridge shard 69 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn266 :
    stationarityAt source15818Data 266 = 0 := by
  change source15818StationarityValue266 = 0
  exact source15818StationarityValue266Zero

theorem source15818StationarityColumn267 :
    stationarityAt source15818Data 267 = 0 := by
  change source15818StationarityValue267 = 0
  exact source15818StationarityValue267Zero

theorem source15818StationarityColumn268 :
    stationarityAt source15818Data 268 = 0 := by
  change source15818StationarityValue268 = 0
  exact source15818StationarityValue268Zero

theorem source15818StationarityColumn269 :
    stationarityAt source15818Data 269 = 0 := by
  change source15818StationarityValue269 = 0
  exact source15818StationarityValue269Zero

end CarmenQExact
