import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 261 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row267 : Fin 3173 := ⟨267, by decide⟩
private def row795 : Fin 3173 := ⟨795, by decide⟩
private def row796 : Fin 3173 := ⟨796, by decide⟩
private def row797 : Fin 3173 := ⟨797, by decide⟩
private def row798 : Fin 3173 := ⟨798, by decide⟩

def source15818ObjectiveCoord261 : ℚ := q 0 1

def source15818Column261 : Array (RayEntry 3173) := #[
  { row := row267, value := q (-1) 1 },
  { row := row795, value := q 1 1 },
  { row := row796, value := q 1 1 },
  { row := row797, value := q (-5404319552844595) 9007199254740992 },
  { row := row798, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue261 : ℚ :=
  source15818Column261.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord261

theorem source15818StationarityValue261Zero :
    source15818StationarityValue261 = 0 := by
  decide +kernel

end CarmenQExact
