import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity196
import CarmenQExact.Source15818Stationarity197
import CarmenQExact.Source15818Stationarity198
import CarmenQExact.Source15818Stationarity199

/-!
# Stationarity bridge shard 49 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn196 :
    stationarityAt source15818Data 196 = 0 := by
  change source15818StationarityValue196 = 0
  exact source15818StationarityValue196Zero

theorem source15818StationarityColumn197 :
    stationarityAt source15818Data 197 = 0 := by
  change source15818StationarityValue197 = 0
  exact source15818StationarityValue197Zero

theorem source15818StationarityColumn198 :
    stationarityAt source15818Data 198 = 0 := by
  change source15818StationarityValue198 = 0
  exact source15818StationarityValue198Zero

theorem source15818StationarityColumn199 :
    stationarityAt source15818Data 199 = 0 := by
  change source15818StationarityValue199 = 0
  exact source15818StationarityValue199Zero

end CarmenQExact
