import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 235 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row241 : Fin 3173 := ⟨241, by decide⟩
private def row574 : Fin 3173 := ⟨574, by decide⟩
private def row575 : Fin 3173 := ⟨575, by decide⟩
private def row582 : Fin 3173 := ⟨582, by decide⟩
private def row875 : Fin 3173 := ⟨875, by decide⟩

def source15818ObjectiveCoord235 : ℚ := q 0 1

def source15818Column235 : Array (RayEntry 3173) := #[
  { row := row241, value := q (-1) 1 },
  { row := row574, value := q (-1) 1 },
  { row := row575, value := q (-1) 1 },
  { row := row582, value := q 1 1 },
  { row := row875, value := q (-1) 1 },
]

def source15818StationarityValue235 : ℚ :=
  source15818Column235.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord235

theorem source15818StationarityValue235Zero :
    source15818StationarityValue235 = 0 := by
  decide +kernel

end CarmenQExact
