import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 202 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row208 : Fin 3173 := ⟨208, by decide⟩
private def row302 : Fin 3173 := ⟨302, by decide⟩
private def row459 : Fin 3173 := ⟨459, by decide⟩
private def row475 : Fin 3173 := ⟨475, by decide⟩
private def row505 : Fin 3173 := ⟨505, by decide⟩
private def row506 : Fin 3173 := ⟨506, by decide⟩
private def row757 : Fin 3173 := ⟨757, by decide⟩
private def row758 : Fin 3173 := ⟨758, by decide⟩
private def row759 : Fin 3173 := ⟨759, by decide⟩
private def row760 : Fin 3173 := ⟨760, by decide⟩
private def row761 : Fin 3173 := ⟨761, by decide⟩
private def row762 : Fin 3173 := ⟨762, by decide⟩

def source15818ObjectiveCoord202 : ℚ := q 0 1

def source15818Column202 : Array (RayEntry 3173) := #[
  { row := row208, value := q (-1) 1 },
  { row := row302, value := q 1 1 },
  { row := row459, value := q 4654212870180819 9007199254740992 },
  { row := row475, value := q (-1166755391775585) 2251799813685248 },
  { row := row505, value := q 1166755391775585 2251799813685248 },
  { row := row506, value := q (-4654212870180819) 9007199254740992 },
  { row := row757, value := q 5404319552844595 9007199254740992 },
  { row := row758, value := q 2476979795053773 4503599627370496 },
  { row := row759, value := q 5404319552844595 9007199254740992 },
  { row := row760, value := q 2476979795053773 4503599627370496 },
  { row := row761, value := q 5404319552844595 9007199254740992 },
  { row := row762, value := q 2476979795053773 4503599627370496 },
]

def source15818StationarityValue202 : ℚ :=
  source15818Column202.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord202

theorem source15818StationarityValue202Zero :
    source15818StationarityValue202 = 0 := by
  decide +kernel

end CarmenQExact
