import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity160
import CarmenQExact.Source15818Stationarity161
import CarmenQExact.Source15818Stationarity162
import CarmenQExact.Source15818Stationarity163

/-!
# Stationarity bridge shard 40 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn160 :
    stationarityAt source15818Data 160 = 0 := by
  change source15818StationarityValue160 = 0
  exact source15818StationarityValue160Zero

theorem source15818StationarityColumn161 :
    stationarityAt source15818Data 161 = 0 := by
  change source15818StationarityValue161 = 0
  exact source15818StationarityValue161Zero

theorem source15818StationarityColumn162 :
    stationarityAt source15818Data 162 = 0 := by
  change source15818StationarityValue162 = 0
  exact source15818StationarityValue162Zero

theorem source15818StationarityColumn163 :
    stationarityAt source15818Data 163 = 0 := by
  change source15818StationarityValue163 = 0
  exact source15818StationarityValue163Zero

end CarmenQExact
