import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity40
import CarmenQExact.Source15818Stationarity41
import CarmenQExact.Source15818Stationarity42
import CarmenQExact.Source15818Stationarity43

/-!
# Stationarity bridge shard 10 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn040 :
    stationarityAt source15818Data 40 = 0 := by
  change source15818StationarityValue040 = 0
  exact source15818StationarityValue040Zero

theorem source15818StationarityColumn041 :
    stationarityAt source15818Data 41 = 0 := by
  change source15818StationarityValue041 = 0
  exact source15818StationarityValue041Zero

theorem source15818StationarityColumn042 :
    stationarityAt source15818Data 42 = 0 := by
  change source15818StationarityValue042 = 0
  exact source15818StationarityValue042Zero

theorem source15818StationarityColumn043 :
    stationarityAt source15818Data 43 = 0 := by
  change source15818StationarityValue043 = 0
  exact source15818StationarityValue043Zero

end CarmenQExact
