import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity112
import CarmenQExact.Source15818Stationarity113
import CarmenQExact.Source15818Stationarity114
import CarmenQExact.Source15818Stationarity115

/-!
# Stationarity bridge shard 28 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn112 :
    stationarityAt source15818Data 112 = 0 := by
  change source15818StationarityValue112 = 0
  exact source15818StationarityValue112Zero

theorem source15818StationarityColumn113 :
    stationarityAt source15818Data 113 = 0 := by
  change source15818StationarityValue113 = 0
  exact source15818StationarityValue113Zero

theorem source15818StationarityColumn114 :
    stationarityAt source15818Data 114 = 0 := by
  change source15818StationarityValue114 = 0
  exact source15818StationarityValue114Zero

theorem source15818StationarityColumn115 :
    stationarityAt source15818Data 115 = 0 := by
  change source15818StationarityValue115 = 0
  exact source15818StationarityValue115Zero

end CarmenQExact
