import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 184 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row190 : Fin 3173 := ⟨190, by decide⟩
private def row284 : Fin 3173 := ⟨284, by decide⟩
private def row393 : Fin 3173 := ⟨393, by decide⟩
private def row409 : Fin 3173 := ⟨409, by decide⟩
private def row425 : Fin 3173 := ⟨425, by decide⟩
private def row426 : Fin 3173 := ⟨426, by decide⟩
private def row751 : Fin 3173 := ⟨751, by decide⟩
private def row752 : Fin 3173 := ⟨752, by decide⟩

def source15818ObjectiveCoord184 : ℚ := q 0 1

def source15818Column184 : Array (RayEntry 3173) := #[
  { row := row190, value := q (-1) 1 },
  { row := row284, value := q 1 1 },
  { row := row393, value := q 77829474067439 140737488355328 },
  { row := row409, value := q (-4993843966331245) 9007199254740992 },
  { row := row425, value := q 4993843966331245 9007199254740992 },
  { row := row426, value := q (-77829474067439) 140737488355328 },
  { row := row751, value := q (-5404319552844595) 9007199254740992 },
  { row := row752, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue184 : ℚ :=
  source15818Column184.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord184

theorem source15818StationarityValue184Zero :
    source15818StationarityValue184 = 0 := by
  decide +kernel

end CarmenQExact
