import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 251 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row257 : Fin 3173 := ⟨257, by decide⟩
private def row765 : Fin 3173 := ⟨765, by decide⟩
private def row766 : Fin 3173 := ⟨766, by decide⟩
private def row767 : Fin 3173 := ⟨767, by decide⟩
private def row768 : Fin 3173 := ⟨768, by decide⟩

def source15818ObjectiveCoord251 : ℚ := q 0 1

def source15818Column251 : Array (RayEntry 3173) := #[
  { row := row257, value := q (-1) 1 },
  { row := row765, value := q 1 1 },
  { row := row766, value := q 1 1 },
  { row := row767, value := q (-5404319552844595) 9007199254740992 },
  { row := row768, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue251 : ℚ :=
  source15818Column251.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord251

theorem source15818StationarityValue251Zero :
    source15818StationarityValue251 = 0 := by
  decide +kernel

end CarmenQExact
