import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity152
import CarmenQExact.Source15818Stationarity153
import CarmenQExact.Source15818Stationarity154
import CarmenQExact.Source15818Stationarity155

/-!
# Stationarity bridge shard 38 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn152 :
    stationarityAt source15818Data 152 = 0 := by
  change source15818StationarityValue152 = 0
  exact source15818StationarityValue152Zero

theorem source15818StationarityColumn153 :
    stationarityAt source15818Data 153 = 0 := by
  change source15818StationarityValue153 = 0
  exact source15818StationarityValue153Zero

theorem source15818StationarityColumn154 :
    stationarityAt source15818Data 154 = 0 := by
  change source15818StationarityValue154 = 0
  exact source15818StationarityValue154Zero

theorem source15818StationarityColumn155 :
    stationarityAt source15818Data 155 = 0 := by
  change source15818StationarityValue155 = 0
  exact source15818StationarityValue155Zero

end CarmenQExact
