import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 228 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row234 : Fin 3173 := ⟨234, by decide⟩
private def row558 : Fin 3173 := ⟨558, by decide⟩
private def row559 : Fin 3173 := ⟨559, by decide⟩
private def row564 : Fin 3173 := ⟨564, by decide⟩
private def row846 : Fin 3173 := ⟨846, by decide⟩

def source15818ObjectiveCoord228 : ℚ := q 0 1

def source15818Column228 : Array (RayEntry 3173) := #[
  { row := row234, value := q (-1) 1 },
  { row := row558, value := q (-1) 1 },
  { row := row559, value := q (-1) 1 },
  { row := row564, value := q 1 1 },
  { row := row846, value := q (-1) 1 },
]

def source15818StationarityValue228 : ℚ :=
  source15818Column228.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord228

theorem source15818StationarityValue228Zero :
    source15818StationarityValue228 = 0 := by
  decide +kernel

end CarmenQExact
