import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 170 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row176 : Fin 3173 := ⟨176, by decide⟩
private def row270 : Fin 3173 := ⟨270, by decide⟩
private def row331 : Fin 3173 := ⟨331, by decide⟩
private def row347 : Fin 3173 := ⟨347, by decide⟩
private def row377 : Fin 3173 := ⟨377, by decide⟩
private def row378 : Fin 3173 := ⟨378, by decide⟩
private def row747 : Fin 3173 := ⟨747, by decide⟩
private def row748 : Fin 3173 := ⟨748, by decide⟩

def source15818ObjectiveCoord170 : ℚ := q 0 1

def source15818Column170 : Array (RayEntry 3173) := #[
  { row := row176, value := q (-1) 1 },
  { row := row270, value := q 1 1 },
  { row := row331, value := q 261175671186813 281474976710656 },
  { row := row347, value := q (-2093748593682989) 2251799813685248 },
  { row := row377, value := q 2093748593682989 2251799813685248 },
  { row := row378, value := q (-261175671186813) 281474976710656 },
  { row := row747, value := q (-5404319552844595) 9007199254740992 },
  { row := row748, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue170 : ℚ :=
  source15818Column170.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord170

theorem source15818StationarityValue170Zero :
    source15818StationarityValue170 = 0 := by
  decide +kernel

end CarmenQExact
