import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity258
import CarmenQExact.Source15818Stationarity259
import CarmenQExact.Source15818Stationarity260
import CarmenQExact.Source15818Stationarity261

/-!
# Stationarity bridge shard 67 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn258 :
    stationarityAt source15818Data 258 = 0 := by
  change source15818StationarityValue258 = 0
  exact source15818StationarityValue258Zero

theorem source15818StationarityColumn259 :
    stationarityAt source15818Data 259 = 0 := by
  change source15818StationarityValue259 = 0
  exact source15818StationarityValue259Zero

theorem source15818StationarityColumn260 :
    stationarityAt source15818Data 260 = 0 := by
  change source15818StationarityValue260 = 0
  exact source15818StationarityValue260Zero

theorem source15818StationarityColumn261 :
    stationarityAt source15818Data 261 = 0 := by
  change source15818StationarityValue261 = 0
  exact source15818StationarityValue261Zero

end CarmenQExact
