import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 253 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row259 : Fin 3173 := ⟨259, by decide⟩
private def row771 : Fin 3173 := ⟨771, by decide⟩
private def row772 : Fin 3173 := ⟨772, by decide⟩
private def row773 : Fin 3173 := ⟨773, by decide⟩
private def row774 : Fin 3173 := ⟨774, by decide⟩

def source15818ObjectiveCoord253 : ℚ := q 0 1

def source15818Column253 : Array (RayEntry 3173) := #[
  { row := row259, value := q (-1) 1 },
  { row := row771, value := q 1 1 },
  { row := row772, value := q 1 1 },
  { row := row773, value := q (-5404319552844595) 9007199254740992 },
  { row := row774, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue253 : ℚ :=
  source15818Column253.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord253

theorem source15818StationarityValue253Zero :
    source15818StationarityValue253 = 0 := by
  decide +kernel

end CarmenQExact
