import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 243 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row249 : Fin 3173 := ⟨249, by decide⟩
private def row592 : Fin 3173 := ⟨592, by decide⟩
private def row593 : Fin 3173 := ⟨593, by decide⟩
private def row600 : Fin 3173 := ⟨600, by decide⟩
private def row907 : Fin 3173 := ⟨907, by decide⟩

def source15818ObjectiveCoord243 : ℚ := q 0 1

def source15818Column243 : Array (RayEntry 3173) := #[
  { row := row249, value := q (-1) 1 },
  { row := row592, value := q (-1) 1 },
  { row := row593, value := q (-1) 1 },
  { row := row600, value := q 1 1 },
  { row := row907, value := q (-1) 1 },
]

def source15818StationarityValue243 : ℚ :=
  source15818Column243.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord243

theorem source15818StationarityValue243Zero :
    source15818StationarityValue243 = 0 := by
  decide +kernel

end CarmenQExact
