import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity236
import CarmenQExact.Source15818Stationarity237
import CarmenQExact.Source15818Stationarity238
import CarmenQExact.Source15818Stationarity239

/-!
# Stationarity bridge shard 59 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn236 :
    stationarityAt source15818Data 236 = 0 := by
  change source15818StationarityValue236 = 0
  exact source15818StationarityValue236Zero

theorem source15818StationarityColumn237 :
    stationarityAt source15818Data 237 = 0 := by
  change source15818StationarityValue237 = 0
  exact source15818StationarityValue237Zero

theorem source15818StationarityColumn238 :
    stationarityAt source15818Data 238 = 0 := by
  change source15818StationarityValue238 = 0
  exact source15818StationarityValue238Zero

theorem source15818StationarityColumn239 :
    stationarityAt source15818Data 239 = 0 := by
  change source15818StationarityValue239 = 0
  exact source15818StationarityValue239Zero

end CarmenQExact
