import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity180
import CarmenQExact.Source15818Stationarity181
import CarmenQExact.Source15818Stationarity182
import CarmenQExact.Source15818Stationarity183

/-!
# Stationarity bridge shard 45 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn180 :
    stationarityAt source15818Data 180 = 0 := by
  change source15818StationarityValue180 = 0
  exact source15818StationarityValue180Zero

theorem source15818StationarityColumn181 :
    stationarityAt source15818Data 181 = 0 := by
  change source15818StationarityValue181 = 0
  exact source15818StationarityValue181Zero

theorem source15818StationarityColumn182 :
    stationarityAt source15818Data 182 = 0 := by
  change source15818StationarityValue182 = 0
  exact source15818StationarityValue182Zero

theorem source15818StationarityColumn183 :
    stationarityAt source15818Data 183 = 0 := by
  change source15818StationarityValue183 = 0
  exact source15818StationarityValue183Zero

end CarmenQExact
