import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity220
import CarmenQExact.Source15818Stationarity221
import CarmenQExact.Source15818Stationarity222
import CarmenQExact.Source15818Stationarity223

/-!
# Stationarity bridge shard 55 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn220 :
    stationarityAt source15818Data 220 = 0 := by
  change source15818StationarityValue220 = 0
  exact source15818StationarityValue220Zero

theorem source15818StationarityColumn221 :
    stationarityAt source15818Data 221 = 0 := by
  change source15818StationarityValue221 = 0
  exact source15818StationarityValue221Zero

theorem source15818StationarityColumn222 :
    stationarityAt source15818Data 222 = 0 := by
  change source15818StationarityValue222 = 0
  exact source15818StationarityValue222Zero

theorem source15818StationarityColumn223 :
    stationarityAt source15818Data 223 = 0 := by
  change source15818StationarityValue223 = 0
  exact source15818StationarityValue223Zero

end CarmenQExact
