import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 197 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row203 : Fin 3173 := ⟨203, by decide⟩
private def row297 : Fin 3173 := ⟨297, by decide⟩
private def row406 : Fin 3173 := ⟨406, by decide⟩
private def row422 : Fin 3173 := ⟨422, by decide⟩
private def row439 : Fin 3173 := ⟨439, by decide⟩
private def row440 : Fin 3173 := ⟨440, by decide⟩
private def row753 : Fin 3173 := ⟨753, by decide⟩
private def row754 : Fin 3173 := ⟨754, by decide⟩

def source15818ObjectiveCoord197 : ℚ := q 0 1

def source15818Column197 : Array (RayEntry 3173) := #[
  { row := row203, value := q (-1) 1 },
  { row := row297, value := q 1 1 },
  { row := row406, value := q 77829474067439 140737488355328 },
  { row := row422, value := q (-1248460991582811) 2251799813685248 },
  { row := row439, value := q 1248460991582811 2251799813685248 },
  { row := row440, value := q (-77829474067439) 140737488355328 },
  { row := row753, value := q (-5404319552844595) 9007199254740992 },
  { row := row754, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue197 : ℚ :=
  source15818Column197.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord197

theorem source15818StationarityValue197Zero :
    source15818StationarityValue197 = 0 := by
  decide +kernel

end CarmenQExact
