import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 179 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row185 : Fin 3173 := ⟨185, by decide⟩
private def row279 : Fin 3173 := ⟨279, by decide⟩
private def row340 : Fin 3173 := ⟨340, by decide⟩
private def row356 : Fin 3173 := ⟨356, by decide⟩
private def row389 : Fin 3173 := ⟨389, by decide⟩
private def row390 : Fin 3173 := ⟨390, by decide⟩
private def row745 : Fin 3173 := ⟨745, by decide⟩
private def row746 : Fin 3173 := ⟨746, by decide⟩

def source15818ObjectiveCoord179 : ℚ := q 0 1

def source15818Column179 : Array (RayEntry 3173) := #[
  { row := row185, value := q (-1) 1 },
  { row := row279, value := q 1 1 },
  { row := row340, value := q 261175671186813 281474976710656 },
  { row := row356, value := q (-2093748593682989) 2251799813685248 },
  { row := row389, value := q 2093748593682989 2251799813685248 },
  { row := row390, value := q (-261175671186813) 281474976710656 },
  { row := row745, value := q (-5404319552844595) 9007199254740992 },
  { row := row746, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue179 : ℚ :=
  source15818Column179.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord179

theorem source15818StationarityValue179Zero :
    source15818StationarityValue179 = 0 := by
  decide +kernel

end CarmenQExact
