import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 224 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row230 : Fin 3173 := ⟨230, by decide⟩
private def row548 : Fin 3173 := ⟨548, by decide⟩
private def row549 : Fin 3173 := ⟨549, by decide⟩
private def row555 : Fin 3173 := ⟨555, by decide⟩
private def row830 : Fin 3173 := ⟨830, by decide⟩

def source15818ObjectiveCoord224 : ℚ := q 0 1

def source15818Column224 : Array (RayEntry 3173) := #[
  { row := row230, value := q (-1) 1 },
  { row := row548, value := q (-1) 1 },
  { row := row549, value := q (-1) 1 },
  { row := row555, value := q 1 1 },
  { row := row830, value := q (-1) 1 },
]

def source15818StationarityValue224 : ℚ :=
  source15818Column224.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord224

theorem source15818StationarityValue224Zero :
    source15818StationarityValue224 = 0 := by
  decide +kernel

end CarmenQExact
