import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 238 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row244 : Fin 3173 := ⟨244, by decide⟩
private def row580 : Fin 3173 := ⟨580, by decide⟩
private def row581 : Fin 3173 := ⟨581, by decide⟩
private def row582 : Fin 3173 := ⟨582, by decide⟩
private def row884 : Fin 3173 := ⟨884, by decide⟩

def source15818ObjectiveCoord238 : ℚ := q 0 1

def source15818Column238 : Array (RayEntry 3173) := #[
  { row := row244, value := q (-1) 1 },
  { row := row580, value := q (-1) 1 },
  { row := row581, value := q (-1) 1 },
  { row := row582, value := q 1 1 },
  { row := row884, value := q (-1) 1 },
]

def source15818StationarityValue238 : ℚ :=
  source15818Column238.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord238

theorem source15818StationarityValue238Zero :
    source15818StationarityValue238 = 0 := by
  decide +kernel

end CarmenQExact
