import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity92
import CarmenQExact.Source15818Stationarity93
import CarmenQExact.Source15818Stationarity94
import CarmenQExact.Source15818Stationarity95

/-!
# Stationarity bridge shard 23 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn092 :
    stationarityAt source15818Data 92 = 0 := by
  change source15818StationarityValue092 = 0
  exact source15818StationarityValue092Zero

theorem source15818StationarityColumn093 :
    stationarityAt source15818Data 93 = 0 := by
  change source15818StationarityValue093 = 0
  exact source15818StationarityValue093Zero

theorem source15818StationarityColumn094 :
    stationarityAt source15818Data 94 = 0 := by
  change source15818StationarityValue094 = 0
  exact source15818StationarityValue094Zero

theorem source15818StationarityColumn095 :
    stationarityAt source15818Data 95 = 0 := by
  change source15818StationarityValue095 = 0
  exact source15818StationarityValue095Zero

end CarmenQExact
