import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 263 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row3 : Fin 3173 := ⟨3, by decide⟩
private def row4 : Fin 3173 := ⟨4, by decide⟩
private def row564 : Fin 3173 := ⟨564, by decide⟩
private def row573 : Fin 3173 := ⟨573, by decide⟩
private def row582 : Fin 3173 := ⟨582, by decide⟩
private def row600 : Fin 3173 := ⟨600, by decide⟩
private def row801 : Fin 3173 := ⟨801, by decide⟩
private def row841 : Fin 3173 := ⟨841, by decide⟩
private def row855 : Fin 3173 := ⟨855, by decide⟩
private def row857 : Fin 3173 := ⟨857, by decide⟩
private def row871 : Fin 3173 := ⟨871, by decide⟩
private def row873 : Fin 3173 := ⟨873, by decide⟩
private def row887 : Fin 3173 := ⟨887, by decide⟩
private def row889 : Fin 3173 := ⟨889, by decide⟩
private def row905 : Fin 3173 := ⟨905, by decide⟩
private def row919 : Fin 3173 := ⟨919, by decide⟩
private def row921 : Fin 3173 := ⟨921, by decide⟩

def source15818ObjectiveCoord263 : ℚ := q 0 1

def source15818Column263 : Array (RayEntry 3173) := #[
  { row := row3, value := q 1 1 },
  { row := row4, value := q 1 1 },
  { row := row564, value := q 77236096414237 140737488355328 },
  { row := row573, value := q (-1993014084204605) 18014398509481984 },
  { row := row582, value := q (-3793696303756565) 18014398509481984 },
  { row := row600, value := q 1327096525091787 2251799813685248 },
  { row := row801, value := q (-1) 1 },
  { row := row841, value := q (-1) 1 },
  { row := row855, value := q 77236096414237 140737488355328 },
  { row := row857, value := q (-1) 1 },
  { row := row871, value := q (-1993014084204605) 18014398509481984 },
  { row := row873, value := q 2381816649896375 4503599627370496 },
  { row := row887, value := q (-3793696303756565) 18014398509481984 },
  { row := row889, value := q (-3772333662396479) 18014398509481984 },
  { row := row905, value := q (-16661540748777) 70368744177664 },
  { row := row919, value := q 1327096525091787 2251799813685248 },
  { row := row921, value := q (-4876063988843295) 9007199254740992 },
]

def source15818StationarityValue263 : ℚ :=
  source15818Column263.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord263

theorem source15818StationarityValue263Zero :
    source15818StationarityValue263 = 0 := by
  decide +kernel

end CarmenQExact
