import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 203 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row209 : Fin 3173 := ⟨209, by decide⟩
private def row303 : Fin 3173 := ⟨303, by decide⟩
private def row460 : Fin 3173 := ⟨460, by decide⟩
private def row476 : Fin 3173 := ⟨476, by decide⟩
private def row513 : Fin 3173 := ⟨513, by decide⟩
private def row514 : Fin 3173 := ⟨514, by decide⟩
private def row761 : Fin 3173 := ⟨761, by decide⟩
private def row762 : Fin 3173 := ⟨762, by decide⟩

def source15818ObjectiveCoord203 : ℚ := q 0 1

def source15818Column203 : Array (RayEntry 3173) := #[
  { row := row209, value := q (-1) 1 },
  { row := row303, value := q 1 1 },
  { row := row460, value := q 4654212870180819 9007199254740992 },
  { row := row476, value := q (-4667021567102341) 9007199254740992 },
  { row := row513, value := q 4667021567102341 9007199254740992 },
  { row := row514, value := q (-4654212870180819) 9007199254740992 },
  { row := row761, value := q (-5404319552844595) 9007199254740992 },
  { row := row762, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue203 : ℚ :=
  source15818Column203.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord203

theorem source15818StationarityValue203Zero :
    source15818StationarityValue203 = 0 := by
  decide +kernel

end CarmenQExact
