import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 195 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row201 : Fin 3173 := ⟨201, by decide⟩
private def row295 : Fin 3173 := ⟨295, by decide⟩
private def row404 : Fin 3173 := ⟨404, by decide⟩
private def row420 : Fin 3173 := ⟨420, by decide⟩
private def row453 : Fin 3173 := ⟨453, by decide⟩
private def row454 : Fin 3173 := ⟨454, by decide⟩
private def row751 : Fin 3173 := ⟨751, by decide⟩
private def row752 : Fin 3173 := ⟨752, by decide⟩
private def row753 : Fin 3173 := ⟨753, by decide⟩
private def row754 : Fin 3173 := ⟨754, by decide⟩
private def row755 : Fin 3173 := ⟨755, by decide⟩
private def row756 : Fin 3173 := ⟨756, by decide⟩

def source15818ObjectiveCoord195 : ℚ := q 0 1

def source15818Column195 : Array (RayEntry 3173) := #[
  { row := row201, value := q (-1) 1 },
  { row := row295, value := q 1 1 },
  { row := row404, value := q 77829474067439 140737488355328 },
  { row := row420, value := q (-4993843966331245) 9007199254740992 },
  { row := row453, value := q 4993843966331245 9007199254740992 },
  { row := row454, value := q (-77829474067439) 140737488355328 },
  { row := row751, value := q 5404319552844595 9007199254740992 },
  { row := row752, value := q 2476979795053773 4503599627370496 },
  { row := row753, value := q 5404319552844595 9007199254740992 },
  { row := row754, value := q 2476979795053773 4503599627370496 },
  { row := row755, value := q 5404319552844595 9007199254740992 },
  { row := row756, value := q 2476979795053773 4503599627370496 },
]

def source15818StationarityValue195 : ℚ :=
  source15818Column195.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord195

theorem source15818StationarityValue195Zero :
    source15818StationarityValue195 = 0 := by
  decide +kernel

end CarmenQExact
