import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity20
import CarmenQExact.Source15818Stationarity21
import CarmenQExact.Source15818Stationarity22
import CarmenQExact.Source15818Stationarity23

/-!
# Stationarity bridge shard 05 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn020 :
    stationarityAt source15818Data 20 = 0 := by
  change source15818StationarityValue020 = 0
  exact source15818StationarityValue020Zero

theorem source15818StationarityColumn021 :
    stationarityAt source15818Data 21 = 0 := by
  change source15818StationarityValue021 = 0
  exact source15818StationarityValue021Zero

theorem source15818StationarityColumn022 :
    stationarityAt source15818Data 22 = 0 := by
  change source15818StationarityValue022 = 0
  exact source15818StationarityValue022Zero

theorem source15818StationarityColumn023 :
    stationarityAt source15818Data 23 = 0 := by
  change source15818StationarityValue023 = 0
  exact source15818StationarityValue023Zero

end CarmenQExact
