import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 217 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row1 : Fin 3173 := ⟨1, by decide⟩
private def row223 : Fin 3173 := ⟨223, by decide⟩
private def row317 : Fin 3173 := ⟨317, by decide⟩
private def row320 : Fin 3173 := ⟨320, by decide⟩
private def row322 : Fin 3173 := ⟨322, by decide⟩
private def row323 : Fin 3173 := ⟨323, by decide⟩
private def row327 : Fin 3173 := ⟨327, by decide⟩
private def row328 : Fin 3173 := ⟨328, by decide⟩
private def row425 : Fin 3173 := ⟨425, by decide⟩
private def row426 : Fin 3173 := ⟨426, by decide⟩
private def row427 : Fin 3173 := ⟨427, by decide⟩
private def row428 : Fin 3173 := ⟨428, by decide⟩
private def row429 : Fin 3173 := ⟨429, by decide⟩
private def row430 : Fin 3173 := ⟨430, by decide⟩
private def row431 : Fin 3173 := ⟨431, by decide⟩
private def row432 : Fin 3173 := ⟨432, by decide⟩
private def row433 : Fin 3173 := ⟨433, by decide⟩
private def row434 : Fin 3173 := ⟨434, by decide⟩
private def row435 : Fin 3173 := ⟨435, by decide⟩
private def row436 : Fin 3173 := ⟨436, by decide⟩
private def row437 : Fin 3173 := ⟨437, by decide⟩
private def row438 : Fin 3173 := ⟨438, by decide⟩
private def row439 : Fin 3173 := ⟨439, by decide⟩
private def row440 : Fin 3173 := ⟨440, by decide⟩
private def row441 : Fin 3173 := ⟨441, by decide⟩
private def row442 : Fin 3173 := ⟨442, by decide⟩
private def row443 : Fin 3173 := ⟨443, by decide⟩
private def row444 : Fin 3173 := ⟨444, by decide⟩
private def row445 : Fin 3173 := ⟨445, by decide⟩
private def row446 : Fin 3173 := ⟨446, by decide⟩
private def row447 : Fin 3173 := ⟨447, by decide⟩
private def row448 : Fin 3173 := ⟨448, by decide⟩
private def row449 : Fin 3173 := ⟨449, by decide⟩
private def row450 : Fin 3173 := ⟨450, by decide⟩
private def row451 : Fin 3173 := ⟨451, by decide⟩
private def row452 : Fin 3173 := ⟨452, by decide⟩
private def row453 : Fin 3173 := ⟨453, by decide⟩
private def row454 : Fin 3173 := ⟨454, by decide⟩
private def row455 : Fin 3173 := ⟨455, by decide⟩
private def row456 : Fin 3173 := ⟨456, by decide⟩
private def row772 : Fin 3173 := ⟨772, by decide⟩
private def row776 : Fin 3173 := ⟨776, by decide⟩
private def row782 : Fin 3173 := ⟨782, by decide⟩
private def row790 : Fin 3173 := ⟨790, by decide⟩

def source15818ObjectiveCoord217 : ℚ := q 0 1

def source15818Column217 : Array (RayEntry 3173) := #[
  { row := row1, value := q 1 1 },
  { row := row223, value := q (-1) 1 },
  { row := row317, value := q (-1) 1 },
  { row := row320, value := q 1 1 },
  { row := row322, value := q 1 1 },
  { row := row323, value := q (-1) 1 },
  { row := row327, value := q (-1) 1 },
  { row := row328, value := q 1 1 },
  { row := row425, value := q 1 1 },
  { row := row426, value := q (-1) 1 },
  { row := row427, value := q 1 1 },
  { row := row428, value := q (-1) 1 },
  { row := row429, value := q 1 1 },
  { row := row430, value := q (-1) 1 },
  { row := row431, value := q 1 1 },
  { row := row432, value := q (-1) 1 },
  { row := row433, value := q 1 2 },
  { row := row434, value := q (-1) 2 },
  { row := row435, value := q 1 2 },
  { row := row436, value := q (-1) 2 },
  { row := row437, value := q 1 2 },
  { row := row438, value := q (-1) 2 },
  { row := row439, value := q 1 2 },
  { row := row440, value := q (-1) 2 },
  { row := row441, value := q 6004799503160661 18014398509481984 },
  { row := row442, value := q (-6004799503160661) 18014398509481984 },
  { row := row443, value := q 6004799503160661 18014398509481984 },
  { row := row444, value := q (-6004799503160661) 18014398509481984 },
  { row := row445, value := q 6004799503160661 18014398509481984 },
  { row := row446, value := q (-6004799503160661) 18014398509481984 },
  { row := row447, value := q 6004799503160661 18014398509481984 },
  { row := row448, value := q (-6004799503160661) 18014398509481984 },
  { row := row449, value := q 1 4 },
  { row := row450, value := q (-1) 4 },
  { row := row451, value := q 1 4 },
  { row := row452, value := q (-1) 4 },
  { row := row453, value := q 1 4 },
  { row := row454, value := q (-1) 4 },
  { row := row455, value := q 1 4 },
  { row := row456, value := q (-1) 4 },
  { row := row772, value := q (-1) 1 },
  { row := row776, value := q 1 1 },
  { row := row782, value := q 1 1 },
  { row := row790, value := q (-1) 1 },
]

def source15818StationarityValue217 : ℚ :=
  source15818Column217.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord217

theorem source15818StationarityValue217Zero :
    source15818StationarityValue217 = 0 := by
  decide +kernel

end CarmenQExact
