import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity247

/-!
# Stationarity bridge shard 62 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn247 :
    stationarityAt source15818Data 247 = 0 := by
  change source15818StationarityValue247 = 0
  exact source15818StationarityValue247Zero

end CarmenQExact
