import CarmenQExact.Source15818Nonnegative00
import CarmenQExact.Source15818Nonnegative01
import CarmenQExact.Source15818Nonnegative02
import CarmenQExact.Source15818Nonnegative03
import CarmenQExact.Source15818Nonnegative04
import CarmenQExact.Source15818Nonnegative05
import CarmenQExact.Source15818Nonnegative06
import CarmenQExact.Source15818Nonnegative07
import CarmenQExact.Source15818Nonnegative08
import CarmenQExact.Source15818Nonnegative09
import CarmenQExact.Source15818Nonnegative10
import CarmenQExact.Source15818Nonnegative11
import CarmenQExact.Source15818Nonnegative12

/-!
# Aggregate nonnegative cone for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818Nonnegative :
    rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      source15818Data.zeroDim source15818Data.nonnegativeDim := by
  change rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
    6 793
  have h00 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 64 :=
    source15818NonnegativeShard00
  have h01 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 128 := by
    exact rationalNonnegativeSegment_append
      (rationalDualAt source15818Data.dual) 6 64 64
      h00 source15818NonnegativeShard01
  have h02 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 192 := by
    exact rationalNonnegativeSegment_append
      (rationalDualAt source15818Data.dual) 6 128 64
      h01 source15818NonnegativeShard02
  have h03 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 256 := by
    exact rationalNonnegativeSegment_append
      (rationalDualAt source15818Data.dual) 6 192 64
      h02 source15818NonnegativeShard03
  have h04 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 320 := by
    exact rationalNonnegativeSegment_append
      (rationalDualAt source15818Data.dual) 6 256 64
      h03 source15818NonnegativeShard04
  have h05 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 384 := by
    exact rationalNonnegativeSegment_append
      (rationalDualAt source15818Data.dual) 6 320 64
      h04 source15818NonnegativeShard05
  have h06 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 448 := by
    exact rationalNonnegativeSegment_append
      (rationalDualAt source15818Data.dual) 6 384 64
      h05 source15818NonnegativeShard06
  have h07 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 512 := by
    exact rationalNonnegativeSegment_append
      (rationalDualAt source15818Data.dual) 6 448 64
      h06 source15818NonnegativeShard07
  have h08 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 576 := by
    exact rationalNonnegativeSegment_append
      (rationalDualAt source15818Data.dual) 6 512 64
      h07 source15818NonnegativeShard08
  have h09 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 640 := by
    exact rationalNonnegativeSegment_append
      (rationalDualAt source15818Data.dual) 6 576 64
      h08 source15818NonnegativeShard09
  have h10 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 704 := by
    exact rationalNonnegativeSegment_append
      (rationalDualAt source15818Data.dual) 6 640 64
      h09 source15818NonnegativeShard10
  have h11 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 768 := by
    exact rationalNonnegativeSegment_append
      (rationalDualAt source15818Data.dual) 6 704 64
      h10 source15818NonnegativeShard11
  have h12 : rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      6 793 := by
    exact rationalNonnegativeSegment_append
      (rationalDualAt source15818Data.dual) 6 768 25
      h11 source15818NonnegativeShard12
  exact h12

end CarmenQExact
