import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity08
import CarmenQExact.Source15818Stationarity09
import CarmenQExact.Source15818Stationarity10
import CarmenQExact.Source15818Stationarity11

/-!
# Stationarity bridge shard 02 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn008 :
    stationarityAt source15818Data 8 = 0 := by
  change source15818StationarityValue008 = 0
  exact source15818StationarityValue008Zero

theorem source15818StationarityColumn009 :
    stationarityAt source15818Data 9 = 0 := by
  change source15818StationarityValue009 = 0
  exact source15818StationarityValue009Zero

theorem source15818StationarityColumn010 :
    stationarityAt source15818Data 10 = 0 := by
  change source15818StationarityValue010 = 0
  exact source15818StationarityValue010Zero

theorem source15818StationarityColumn011 :
    stationarityAt source15818Data 11 = 0 := by
  change source15818StationarityValue011 = 0
  exact source15818StationarityValue011Zero

end CarmenQExact
