import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 172 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row178 : Fin 3173 := ⟨178, by decide⟩
private def row272 : Fin 3173 := ⟨272, by decide⟩
private def row333 : Fin 3173 := ⟨333, by decide⟩
private def row349 : Fin 3173 := ⟨349, by decide⟩
private def row363 : Fin 3173 := ⟨363, by decide⟩
private def row364 : Fin 3173 := ⟨364, by decide⟩
private def row745 : Fin 3173 := ⟨745, by decide⟩
private def row746 : Fin 3173 := ⟨746, by decide⟩

def source15818ObjectiveCoord172 : ℚ := q 0 1

def source15818Column172 : Array (RayEntry 3173) := #[
  { row := row178, value := q (-1) 1 },
  { row := row272, value := q 1 1 },
  { row := row333, value := q 261175671186813 281474976710656 },
  { row := row349, value := q (-8374994374731957) 9007199254740992 },
  { row := row363, value := q 8374994374731957 9007199254740992 },
  { row := row364, value := q (-261175671186813) 281474976710656 },
  { row := row745, value := q (-5404319552844595) 9007199254740992 },
  { row := row746, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue172 : ℚ :=
  source15818Column172.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord172

theorem source15818StationarityValue172Zero :
    source15818StationarityValue172 = 0 := by
  decide +kernel

end CarmenQExact
