import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity60
import CarmenQExact.Source15818Stationarity61
import CarmenQExact.Source15818Stationarity62
import CarmenQExact.Source15818Stationarity63

/-!
# Stationarity bridge shard 15 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn060 :
    stationarityAt source15818Data 60 = 0 := by
  change source15818StationarityValue060 = 0
  exact source15818StationarityValue060Zero

theorem source15818StationarityColumn061 :
    stationarityAt source15818Data 61 = 0 := by
  change source15818StationarityValue061 = 0
  exact source15818StationarityValue061Zero

theorem source15818StationarityColumn062 :
    stationarityAt source15818Data 62 = 0 := by
  change source15818StationarityValue062 = 0
  exact source15818StationarityValue062Zero

theorem source15818StationarityColumn063 :
    stationarityAt source15818Data 63 = 0 := by
  change source15818StationarityValue063 = 0
  exact source15818StationarityValue063Zero

end CarmenQExact
