import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 212 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row218 : Fin 3173 := ⟨218, by decide⟩
private def row312 : Fin 3173 := ⟨312, by decide⟩
private def row469 : Fin 3173 := ⟨469, by decide⟩
private def row485 : Fin 3173 := ⟨485, by decide⟩
private def row495 : Fin 3173 := ⟨495, by decide⟩
private def row496 : Fin 3173 := ⟨496, by decide⟩
private def row761 : Fin 3173 := ⟨761, by decide⟩
private def row762 : Fin 3173 := ⟨762, by decide⟩

def source15818ObjectiveCoord212 : ℚ := q 0 1

def source15818Column212 : Array (RayEntry 3173) := #[
  { row := row218, value := q (-1) 1 },
  { row := row312, value := q 1 1 },
  { row := row469, value := q 4654212870180819 9007199254740992 },
  { row := row485, value := q (-4667021567102341) 9007199254740992 },
  { row := row495, value := q 4667021567102341 9007199254740992 },
  { row := row496, value := q (-4654212870180819) 9007199254740992 },
  { row := row761, value := q (-5404319552844595) 9007199254740992 },
  { row := row762, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue212 : ℚ :=
  source15818Column212.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord212

theorem source15818StationarityValue212Zero :
    source15818StationarityValue212 = 0 := by
  decide +kernel

end CarmenQExact
