import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 210 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row216 : Fin 3173 := ⟨216, by decide⟩
private def row310 : Fin 3173 := ⟨310, by decide⟩
private def row467 : Fin 3173 := ⟨467, by decide⟩
private def row483 : Fin 3173 := ⟨483, by decide⟩
private def row509 : Fin 3173 := ⟨509, by decide⟩
private def row510 : Fin 3173 := ⟨510, by decide⟩
private def row757 : Fin 3173 := ⟨757, by decide⟩
private def row758 : Fin 3173 := ⟨758, by decide⟩

def source15818ObjectiveCoord210 : ℚ := q 0 1

def source15818Column210 : Array (RayEntry 3173) := #[
  { row := row216, value := q (-1) 1 },
  { row := row310, value := q 1 1 },
  { row := row467, value := q 4654212870180819 9007199254740992 },
  { row := row483, value := q (-1166755391775585) 2251799813685248 },
  { row := row509, value := q 1166755391775585 2251799813685248 },
  { row := row510, value := q (-4654212870180819) 9007199254740992 },
  { row := row757, value := q (-5404319552844595) 9007199254740992 },
  { row := row758, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue210 : ℚ :=
  source15818Column210.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord210

theorem source15818StationarityValue210Zero :
    source15818StationarityValue210 = 0 := by
  decide +kernel

end CarmenQExact
