import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 209 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row215 : Fin 3173 := ⟨215, by decide⟩
private def row309 : Fin 3173 := ⟨309, by decide⟩
private def row466 : Fin 3173 := ⟨466, by decide⟩
private def row482 : Fin 3173 := ⟨482, by decide⟩
private def row501 : Fin 3173 := ⟨501, by decide⟩
private def row502 : Fin 3173 := ⟨502, by decide⟩
private def row761 : Fin 3173 := ⟨761, by decide⟩
private def row762 : Fin 3173 := ⟨762, by decide⟩

def source15818ObjectiveCoord209 : ℚ := q 0 1

def source15818Column209 : Array (RayEntry 3173) := #[
  { row := row215, value := q (-1) 1 },
  { row := row309, value := q 1 1 },
  { row := row466, value := q 4654212870180819 9007199254740992 },
  { row := row482, value := q (-1166755391775585) 2251799813685248 },
  { row := row501, value := q 1166755391775585 2251799813685248 },
  { row := row502, value := q (-4654212870180819) 9007199254740992 },
  { row := row761, value := q (-5404319552844595) 9007199254740992 },
  { row := row762, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue209 : ℚ :=
  source15818Column209.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord209

theorem source15818StationarityValue209Zero :
    source15818StationarityValue209 = 0 := by
  decide +kernel

end CarmenQExact
