import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 189 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row195 : Fin 3173 := ⟨195, by decide⟩
private def row289 : Fin 3173 := ⟨289, by decide⟩
private def row398 : Fin 3173 := ⟨398, by decide⟩
private def row414 : Fin 3173 := ⟨414, by decide⟩
private def row435 : Fin 3173 := ⟨435, by decide⟩
private def row436 : Fin 3173 := ⟨436, by decide⟩
private def row751 : Fin 3173 := ⟨751, by decide⟩
private def row752 : Fin 3173 := ⟨752, by decide⟩

def source15818ObjectiveCoord189 : ℚ := q 0 1

def source15818Column189 : Array (RayEntry 3173) := #[
  { row := row195, value := q (-1) 1 },
  { row := row289, value := q 1 1 },
  { row := row398, value := q 77829474067439 140737488355328 },
  { row := row414, value := q (-1248460991582811) 2251799813685248 },
  { row := row435, value := q 1248460991582811 2251799813685248 },
  { row := row436, value := q (-77829474067439) 140737488355328 },
  { row := row751, value := q (-5404319552844595) 9007199254740992 },
  { row := row752, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue189 : ℚ :=
  source15818Column189.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord189

theorem source15818StationarityValue189Zero :
    source15818StationarityValue189 = 0 := by
  decide +kernel

end CarmenQExact
