import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity48
import CarmenQExact.Source15818Stationarity49
import CarmenQExact.Source15818Stationarity50
import CarmenQExact.Source15818Stationarity51

/-!
# Stationarity bridge shard 12 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn048 :
    stationarityAt source15818Data 48 = 0 := by
  change source15818StationarityValue048 = 0
  exact source15818StationarityValue048Zero

theorem source15818StationarityColumn049 :
    stationarityAt source15818Data 49 = 0 := by
  change source15818StationarityValue049 = 0
  exact source15818StationarityValue049Zero

theorem source15818StationarityColumn050 :
    stationarityAt source15818Data 50 = 0 := by
  change source15818StationarityValue050 = 0
  exact source15818StationarityValue050Zero

theorem source15818StationarityColumn051 :
    stationarityAt source15818Data 51 = 0 := by
  change source15818StationarityValue051 = 0
  exact source15818StationarityValue051Zero

end CarmenQExact
