import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 158 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row164 : Fin 3173 := ⟨164, by decide⟩
private def row745 : Fin 3173 := ⟨745, by decide⟩
private def row746 : Fin 3173 := ⟨746, by decide⟩
private def row747 : Fin 3173 := ⟨747, by decide⟩
private def row748 : Fin 3173 := ⟨748, by decide⟩
private def row749 : Fin 3173 := ⟨749, by decide⟩
private def row750 : Fin 3173 := ⟨750, by decide⟩
private def row751 : Fin 3173 := ⟨751, by decide⟩
private def row752 : Fin 3173 := ⟨752, by decide⟩
private def row753 : Fin 3173 := ⟨753, by decide⟩
private def row754 : Fin 3173 := ⟨754, by decide⟩
private def row755 : Fin 3173 := ⟨755, by decide⟩
private def row756 : Fin 3173 := ⟨756, by decide⟩
private def row757 : Fin 3173 := ⟨757, by decide⟩
private def row758 : Fin 3173 := ⟨758, by decide⟩
private def row759 : Fin 3173 := ⟨759, by decide⟩
private def row760 : Fin 3173 := ⟨760, by decide⟩
private def row761 : Fin 3173 := ⟨761, by decide⟩
private def row762 : Fin 3173 := ⟨762, by decide⟩
private def row767 : Fin 3173 := ⟨767, by decide⟩
private def row768 : Fin 3173 := ⟨768, by decide⟩
private def row773 : Fin 3173 := ⟨773, by decide⟩
private def row774 : Fin 3173 := ⟨774, by decide⟩
private def row779 : Fin 3173 := ⟨779, by decide⟩
private def row780 : Fin 3173 := ⟨780, by decide⟩
private def row785 : Fin 3173 := ⟨785, by decide⟩
private def row786 : Fin 3173 := ⟨786, by decide⟩
private def row791 : Fin 3173 := ⟨791, by decide⟩
private def row792 : Fin 3173 := ⟨792, by decide⟩
private def row797 : Fin 3173 := ⟨797, by decide⟩
private def row798 : Fin 3173 := ⟨798, by decide⟩
private def row3144 : Fin 3173 := ⟨3144, by decide⟩

def source15818ObjectiveCoord158 : ℚ := q (-2026619832316723) 36028797018963968

def source15818Column158 : Array (RayEntry 3173) := #[
  { row := row164, value := q (-1) 1 },
  { row := row745, value := q 3602879701896397 72057594037927936 },
  { row := row746, value := q 2026619832316723 36028797018963968 },
  { row := row747, value := q 3602879701896397 72057594037927936 },
  { row := row748, value := q 2026619832316723 36028797018963968 },
  { row := row749, value := q 3602879701896397 72057594037927936 },
  { row := row750, value := q 2026619832316723 36028797018963968 },
  { row := row751, value := q 3602879701896397 72057594037927936 },
  { row := row752, value := q 2026619832316723 36028797018963968 },
  { row := row753, value := q 3602879701896397 72057594037927936 },
  { row := row754, value := q 2026619832316723 36028797018963968 },
  { row := row755, value := q 3602879701896397 72057594037927936 },
  { row := row756, value := q 2026619832316723 36028797018963968 },
  { row := row757, value := q 3602879701896397 72057594037927936 },
  { row := row758, value := q 2026619832316723 36028797018963968 },
  { row := row759, value := q 3602879701896397 72057594037927936 },
  { row := row760, value := q 2026619832316723 36028797018963968 },
  { row := row761, value := q 3602879701896397 72057594037927936 },
  { row := row762, value := q 2026619832316723 36028797018963968 },
  { row := row767, value := q 3602879701896397 72057594037927936 },
  { row := row768, value := q 2026619832316723 36028797018963968 },
  { row := row773, value := q 3602879701896397 72057594037927936 },
  { row := row774, value := q 2026619832316723 36028797018963968 },
  { row := row779, value := q 3602879701896397 72057594037927936 },
  { row := row780, value := q 2026619832316723 36028797018963968 },
  { row := row785, value := q 3602879701896397 72057594037927936 },
  { row := row786, value := q 2026619832316723 36028797018963968 },
  { row := row791, value := q 3602879701896397 72057594037927936 },
  { row := row792, value := q 2026619832316723 36028797018963968 },
  { row := row797, value := q 3602879701896397 72057594037927936 },
  { row := row798, value := q 2026619832316723 36028797018963968 },
  { row := row3144, value := q (-2) 1 },
]

def source15818StationarityValue158 : ℚ :=
  source15818Column158.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord158

theorem source15818StationarityValue158Zero :
    source15818StationarityValue158 = 0 := by
  decide +kernel

end CarmenQExact
