import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity12
import CarmenQExact.Source15818Stationarity13
import CarmenQExact.Source15818Stationarity14
import CarmenQExact.Source15818Stationarity15

/-!
# Stationarity bridge shard 03 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn012 :
    stationarityAt source15818Data 12 = 0 := by
  change source15818StationarityValue012 = 0
  exact source15818StationarityValue012Zero

theorem source15818StationarityColumn013 :
    stationarityAt source15818Data 13 = 0 := by
  change source15818StationarityValue013 = 0
  exact source15818StationarityValue013Zero

theorem source15818StationarityColumn014 :
    stationarityAt source15818Data 14 = 0 := by
  change source15818StationarityValue014 = 0
  exact source15818StationarityValue014Zero

theorem source15818StationarityColumn015 :
    stationarityAt source15818Data 15 = 0 := by
  change source15818StationarityValue015 = 0
  exact source15818StationarityValue015Zero

end CarmenQExact
