import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 196 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row202 : Fin 3173 := ⟨202, by decide⟩
private def row296 : Fin 3173 := ⟨296, by decide⟩
private def row405 : Fin 3173 := ⟨405, by decide⟩
private def row421 : Fin 3173 := ⟨421, by decide⟩
private def row431 : Fin 3173 := ⟨431, by decide⟩
private def row432 : Fin 3173 := ⟨432, by decide⟩
private def row755 : Fin 3173 := ⟨755, by decide⟩
private def row756 : Fin 3173 := ⟨756, by decide⟩

def source15818ObjectiveCoord196 : ℚ := q 0 1

def source15818Column196 : Array (RayEntry 3173) := #[
  { row := row202, value := q (-1) 1 },
  { row := row296, value := q 1 1 },
  { row := row405, value := q 77829474067439 140737488355328 },
  { row := row421, value := q (-1248460991582811) 2251799813685248 },
  { row := row431, value := q 1248460991582811 2251799813685248 },
  { row := row432, value := q (-77829474067439) 140737488355328 },
  { row := row755, value := q (-5404319552844595) 9007199254740992 },
  { row := row756, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue196 : ℚ :=
  source15818Column196.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord196

theorem source15818StationarityValue196Zero :
    source15818StationarityValue196 = 0 := by
  decide +kernel

end CarmenQExact
