import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 234 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row240 : Fin 3173 := ⟨240, by decide⟩
private def row571 : Fin 3173 := ⟨571, by decide⟩
private def row572 : Fin 3173 := ⟨572, by decide⟩
private def row573 : Fin 3173 := ⟨573, by decide⟩
private def row868 : Fin 3173 := ⟨868, by decide⟩

def source15818ObjectiveCoord234 : ℚ := q 0 1

def source15818Column234 : Array (RayEntry 3173) := #[
  { row := row240, value := q (-1) 1 },
  { row := row571, value := q (-1) 1 },
  { row := row572, value := q (-1) 1 },
  { row := row573, value := q 1 1 },
  { row := row868, value := q (-1) 1 },
]

def source15818StationarityValue234 : ℚ :=
  source15818Column234.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord234

theorem source15818StationarityValue234Zero :
    source15818StationarityValue234 = 0 := by
  decide +kernel

end CarmenQExact
