import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity200
import CarmenQExact.Source15818Stationarity201
import CarmenQExact.Source15818Stationarity202
import CarmenQExact.Source15818Stationarity203

/-!
# Stationarity bridge shard 50 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn200 :
    stationarityAt source15818Data 200 = 0 := by
  change source15818StationarityValue200 = 0
  exact source15818StationarityValue200Zero

theorem source15818StationarityColumn201 :
    stationarityAt source15818Data 201 = 0 := by
  change source15818StationarityValue201 = 0
  exact source15818StationarityValue201Zero

theorem source15818StationarityColumn202 :
    stationarityAt source15818Data 202 = 0 := by
  change source15818StationarityValue202 = 0
  exact source15818StationarityValue202Zero

theorem source15818StationarityColumn203 :
    stationarityAt source15818Data 203 = 0 := by
  change source15818StationarityValue203 = 0
  exact source15818StationarityValue203Zero

end CarmenQExact
