import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity249

/-!
# Stationarity bridge shard 64 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn249 :
    stationarityAt source15818Data 249 = 0 := by
  change source15818StationarityValue249 = 0
  exact source15818StationarityValue249Zero

end CarmenQExact
