import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity80
import CarmenQExact.Source15818Stationarity81
import CarmenQExact.Source15818Stationarity82
import CarmenQExact.Source15818Stationarity83

/-!
# Stationarity bridge shard 20 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn080 :
    stationarityAt source15818Data 80 = 0 := by
  change source15818StationarityValue080 = 0
  exact source15818StationarityValue080Zero

theorem source15818StationarityColumn081 :
    stationarityAt source15818Data 81 = 0 := by
  change source15818StationarityValue081 = 0
  exact source15818StationarityValue081Zero

theorem source15818StationarityColumn082 :
    stationarityAt source15818Data 82 = 0 := by
  change source15818StationarityValue082 = 0
  exact source15818StationarityValue082Zero

theorem source15818StationarityColumn083 :
    stationarityAt source15818Data 83 = 0 := by
  change source15818StationarityValue083 = 0
  exact source15818StationarityValue083Zero

end CarmenQExact
