import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 190 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row196 : Fin 3173 := ⟨196, by decide⟩
private def row290 : Fin 3173 := ⟨290, by decide⟩
private def row399 : Fin 3173 := ⟨399, by decide⟩
private def row415 : Fin 3173 := ⟨415, by decide⟩
private def row443 : Fin 3173 := ⟨443, by decide⟩
private def row444 : Fin 3173 := ⟨444, by decide⟩
private def row755 : Fin 3173 := ⟨755, by decide⟩
private def row756 : Fin 3173 := ⟨756, by decide⟩

def source15818ObjectiveCoord190 : ℚ := q 0 1

def source15818Column190 : Array (RayEntry 3173) := #[
  { row := row196, value := q (-1) 1 },
  { row := row290, value := q 1 1 },
  { row := row399, value := q 77829474067439 140737488355328 },
  { row := row415, value := q (-4993843966331245) 9007199254740992 },
  { row := row443, value := q 4993843966331245 9007199254740992 },
  { row := row444, value := q (-77829474067439) 140737488355328 },
  { row := row755, value := q (-5404319552844595) 9007199254740992 },
  { row := row756, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue190 : ℚ :=
  source15818Column190.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord190

theorem source15818StationarityValue190Zero :
    source15818StationarityValue190 = 0 := by
  decide +kernel

end CarmenQExact
