import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 252 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row258 : Fin 3173 := ⟨258, by decide⟩
private def row769 : Fin 3173 := ⟨769, by decide⟩
private def row770 : Fin 3173 := ⟨770, by decide⟩
private def row773 : Fin 3173 := ⟨773, by decide⟩
private def row774 : Fin 3173 := ⟨774, by decide⟩

def source15818ObjectiveCoord252 : ℚ := q 0 1

def source15818Column252 : Array (RayEntry 3173) := #[
  { row := row258, value := q (-1) 1 },
  { row := row769, value := q 1 1 },
  { row := row770, value := q 1 1 },
  { row := row773, value := q (-5404319552844595) 9007199254740992 },
  { row := row774, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue252 : ℚ :=
  source15818Column252.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord252

theorem source15818StationarityValue252Zero :
    source15818StationarityValue252 = 0 := by
  decide +kernel

end CarmenQExact
