import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity192
import CarmenQExact.Source15818Stationarity193
import CarmenQExact.Source15818Stationarity194
import CarmenQExact.Source15818Stationarity195

/-!
# Stationarity bridge shard 48 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn192 :
    stationarityAt source15818Data 192 = 0 := by
  change source15818StationarityValue192 = 0
  exact source15818StationarityValue192Zero

theorem source15818StationarityColumn193 :
    stationarityAt source15818Data 193 = 0 := by
  change source15818StationarityValue193 = 0
  exact source15818StationarityValue193Zero

theorem source15818StationarityColumn194 :
    stationarityAt source15818Data 194 = 0 := by
  change source15818StationarityValue194 = 0
  exact source15818StationarityValue194Zero

theorem source15818StationarityColumn195 :
    stationarityAt source15818Data 195 = 0 := by
  change source15818StationarityValue195 = 0
  exact source15818StationarityValue195Zero

end CarmenQExact
