import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity100
import CarmenQExact.Source15818Stationarity101
import CarmenQExact.Source15818Stationarity102
import CarmenQExact.Source15818Stationarity103

/-!
# Stationarity bridge shard 25 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn100 :
    stationarityAt source15818Data 100 = 0 := by
  change source15818StationarityValue100 = 0
  exact source15818StationarityValue100Zero

theorem source15818StationarityColumn101 :
    stationarityAt source15818Data 101 = 0 := by
  change source15818StationarityValue101 = 0
  exact source15818StationarityValue101Zero

theorem source15818StationarityColumn102 :
    stationarityAt source15818Data 102 = 0 := by
  change source15818StationarityValue102 = 0
  exact source15818StationarityValue102Zero

theorem source15818StationarityColumn103 :
    stationarityAt source15818Data 103 = 0 := by
  change source15818StationarityValue103 = 0
  exact source15818StationarityValue103Zero

end CarmenQExact
