import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 242 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row248 : Fin 3173 := ⟨248, by decide⟩
private def row589 : Fin 3173 := ⟨589, by decide⟩
private def row590 : Fin 3173 := ⟨590, by decide⟩
private def row591 : Fin 3173 := ⟨591, by decide⟩
private def row900 : Fin 3173 := ⟨900, by decide⟩

def source15818ObjectiveCoord242 : ℚ := q 0 1

def source15818Column242 : Array (RayEntry 3173) := #[
  { row := row248, value := q (-1) 1 },
  { row := row589, value := q (-1) 1 },
  { row := row590, value := q (-1) 1 },
  { row := row591, value := q 1 1 },
  { row := row900, value := q (-1) 1 },
]

def source15818StationarityValue242 : ℚ :=
  source15818Column242.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord242

theorem source15818StationarityValue242Zero :
    source15818StationarityValue242 = 0 := by
  decide +kernel

end CarmenQExact
