import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 229 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row235 : Fin 3173 := ⟨235, by decide⟩
private def row560 : Fin 3173 := ⟨560, by decide⟩
private def row561 : Fin 3173 := ⟨561, by decide⟩
private def row564 : Fin 3173 := ⟨564, by decide⟩
private def row849 : Fin 3173 := ⟨849, by decide⟩

def source15818ObjectiveCoord229 : ℚ := q 0 1

def source15818Column229 : Array (RayEntry 3173) := #[
  { row := row235, value := q (-1) 1 },
  { row := row560, value := q (-1) 1 },
  { row := row561, value := q (-1) 1 },
  { row := row564, value := q 1 1 },
  { row := row849, value := q (-1) 1 },
]

def source15818StationarityValue229 : ℚ :=
  source15818Column229.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord229

theorem source15818StationarityValue229Zero :
    source15818StationarityValue229 = 0 := by
  decide +kernel

end CarmenQExact
