import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity104
import CarmenQExact.Source15818Stationarity105
import CarmenQExact.Source15818Stationarity106
import CarmenQExact.Source15818Stationarity107

/-!
# Stationarity bridge shard 26 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn104 :
    stationarityAt source15818Data 104 = 0 := by
  change source15818StationarityValue104 = 0
  exact source15818StationarityValue104Zero

theorem source15818StationarityColumn105 :
    stationarityAt source15818Data 105 = 0 := by
  change source15818StationarityValue105 = 0
  exact source15818StationarityValue105Zero

theorem source15818StationarityColumn106 :
    stationarityAt source15818Data 106 = 0 := by
  change source15818StationarityValue106 = 0
  exact source15818StationarityValue106Zero

theorem source15818StationarityColumn107 :
    stationarityAt source15818Data 107 = 0 := by
  change source15818StationarityValue107 = 0
  exact source15818StationarityValue107Zero

end CarmenQExact
