import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity228
import CarmenQExact.Source15818Stationarity229
import CarmenQExact.Source15818Stationarity230
import CarmenQExact.Source15818Stationarity231

/-!
# Stationarity bridge shard 57 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn228 :
    stationarityAt source15818Data 228 = 0 := by
  change source15818StationarityValue228 = 0
  exact source15818StationarityValue228Zero

theorem source15818StationarityColumn229 :
    stationarityAt source15818Data 229 = 0 := by
  change source15818StationarityValue229 = 0
  exact source15818StationarityValue229Zero

theorem source15818StationarityColumn230 :
    stationarityAt source15818Data 230 = 0 := by
  change source15818StationarityValue230 = 0
  exact source15818StationarityValue230Zero

theorem source15818StationarityColumn231 :
    stationarityAt source15818Data 231 = 0 := by
  change source15818StationarityValue231 = 0
  exact source15818StationarityValue231Zero

end CarmenQExact
