import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 180 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row186 : Fin 3173 := ⟨186, by decide⟩
private def row280 : Fin 3173 := ⟨280, by decide⟩
private def row341 : Fin 3173 := ⟨341, by decide⟩
private def row357 : Fin 3173 := ⟨357, by decide⟩
private def row367 : Fin 3173 := ⟨367, by decide⟩
private def row368 : Fin 3173 := ⟨368, by decide⟩
private def row749 : Fin 3173 := ⟨749, by decide⟩
private def row750 : Fin 3173 := ⟨750, by decide⟩

def source15818ObjectiveCoord180 : ℚ := q 0 1

def source15818Column180 : Array (RayEntry 3173) := #[
  { row := row186, value := q (-1) 1 },
  { row := row280, value := q 1 1 },
  { row := row341, value := q 261175671186813 281474976710656 },
  { row := row357, value := q (-2093748593682989) 2251799813685248 },
  { row := row367, value := q 2093748593682989 2251799813685248 },
  { row := row368, value := q (-261175671186813) 281474976710656 },
  { row := row749, value := q (-5404319552844595) 9007199254740992 },
  { row := row750, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue180 : ℚ :=
  source15818Column180.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord180

theorem source15818StationarityValue180Zero :
    source15818StationarityValue180 = 0 := by
  decide +kernel

end CarmenQExact
