import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity168
import CarmenQExact.Source15818Stationarity169
import CarmenQExact.Source15818Stationarity170
import CarmenQExact.Source15818Stationarity171

/-!
# Stationarity bridge shard 42 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn168 :
    stationarityAt source15818Data 168 = 0 := by
  change source15818StationarityValue168 = 0
  exact source15818StationarityValue168Zero

theorem source15818StationarityColumn169 :
    stationarityAt source15818Data 169 = 0 := by
  change source15818StationarityValue169 = 0
  exact source15818StationarityValue169Zero

theorem source15818StationarityColumn170 :
    stationarityAt source15818Data 170 = 0 := by
  change source15818StationarityValue170 = 0
  exact source15818StationarityValue170Zero

theorem source15818StationarityColumn171 :
    stationarityAt source15818Data 171 = 0 := by
  change source15818StationarityValue171 = 0
  exact source15818StationarityValue171Zero

end CarmenQExact
