import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity108
import CarmenQExact.Source15818Stationarity109
import CarmenQExact.Source15818Stationarity110
import CarmenQExact.Source15818Stationarity111

/-!
# Stationarity bridge shard 27 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn108 :
    stationarityAt source15818Data 108 = 0 := by
  change source15818StationarityValue108 = 0
  exact source15818StationarityValue108Zero

theorem source15818StationarityColumn109 :
    stationarityAt source15818Data 109 = 0 := by
  change source15818StationarityValue109 = 0
  exact source15818StationarityValue109Zero

theorem source15818StationarityColumn110 :
    stationarityAt source15818Data 110 = 0 := by
  change source15818StationarityValue110 = 0
  exact source15818StationarityValue110Zero

theorem source15818StationarityColumn111 :
    stationarityAt source15818Data 111 = 0 := by
  change source15818StationarityValue111 = 0
  exact source15818StationarityValue111Zero

end CarmenQExact
