import CarmenQExact.Source15818Data

/-!
# Top-level index check for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818IndicesOK :
    indicesOK source15818Data = true := by
  decide +kernel

end CarmenQExact
