import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity270
import CarmenQExact.Source15818Stationarity271
import CarmenQExact.Source15818Stationarity272
import CarmenQExact.Source15818Stationarity273

/-!
# Stationarity bridge shard 70 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn270 :
    stationarityAt source15818Data 270 = 0 := by
  change source15818StationarityValue270 = 0
  exact source15818StationarityValue270Zero

theorem source15818StationarityColumn271 :
    stationarityAt source15818Data 271 = 0 := by
  change source15818StationarityValue271 = 0
  exact source15818StationarityValue271Zero

theorem source15818StationarityColumn272 :
    stationarityAt source15818Data 272 = 0 := by
  change source15818StationarityValue272 = 0
  exact source15818StationarityValue272Zero

theorem source15818StationarityColumn273 :
    stationarityAt source15818Data 273 = 0 := by
  change source15818StationarityValue273 = 0
  exact source15818StationarityValue273Zero

end CarmenQExact
