import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity244
import CarmenQExact.Source15818Stationarity245
import CarmenQExact.Source15818Stationarity246

/-!
# Stationarity bridge shard 61 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn244 :
    stationarityAt source15818Data 244 = 0 := by
  change source15818StationarityValue244 = 0
  exact source15818StationarityValue244Zero

theorem source15818StationarityColumn245 :
    stationarityAt source15818Data 245 = 0 := by
  change source15818StationarityValue245 = 0
  exact source15818StationarityValue245Zero

theorem source15818StationarityColumn246 :
    stationarityAt source15818Data 246 = 0 := by
  change source15818StationarityValue246 = 0
  exact source15818StationarityValue246Zero

end CarmenQExact
