import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity262
import CarmenQExact.Source15818Stationarity263
import CarmenQExact.Source15818Stationarity264
import CarmenQExact.Source15818Stationarity265

/-!
# Stationarity bridge shard 68 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn262 :
    stationarityAt source15818Data 262 = 0 := by
  change source15818StationarityValue262 = 0
  exact source15818StationarityValue262Zero

theorem source15818StationarityColumn263 :
    stationarityAt source15818Data 263 = 0 := by
  change source15818StationarityValue263 = 0
  exact source15818StationarityValue263Zero

theorem source15818StationarityColumn264 :
    stationarityAt source15818Data 264 = 0 := by
  change source15818StationarityValue264 = 0
  exact source15818StationarityValue264Zero

theorem source15818StationarityColumn265 :
    stationarityAt source15818Data 265 = 0 := by
  change source15818StationarityValue265 = 0
  exact source15818StationarityValue265Zero

end CarmenQExact
