import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity172
import CarmenQExact.Source15818Stationarity173
import CarmenQExact.Source15818Stationarity174
import CarmenQExact.Source15818Stationarity175

/-!
# Stationarity bridge shard 43 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn172 :
    stationarityAt source15818Data 172 = 0 := by
  change source15818StationarityValue172 = 0
  exact source15818StationarityValue172Zero

theorem source15818StationarityColumn173 :
    stationarityAt source15818Data 173 = 0 := by
  change source15818StationarityValue173 = 0
  exact source15818StationarityValue173Zero

theorem source15818StationarityColumn174 :
    stationarityAt source15818Data 174 = 0 := by
  change source15818StationarityValue174 = 0
  exact source15818StationarityValue174Zero

theorem source15818StationarityColumn175 :
    stationarityAt source15818Data 175 = 0 := by
  change source15818StationarityValue175 = 0
  exact source15818StationarityValue175Zero

end CarmenQExact
