import CarmenQExact.Source15818Data

/-!
# Lorentz-cone shard 24 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818SocShard24 :
    rationalLorentzBlocks (rationalDualAt source15818Data.dual)
      3113 [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3] := by
  apply socBlocksOK_sound
  decide +kernel

end CarmenQExact
