import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 204 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row210 : Fin 3173 := ⟨210, by decide⟩
private def row304 : Fin 3173 := ⟨304, by decide⟩
private def row461 : Fin 3173 := ⟨461, by decide⟩
private def row477 : Fin 3173 := ⟨477, by decide⟩
private def row491 : Fin 3173 := ⟨491, by decide⟩
private def row492 : Fin 3173 := ⟨492, by decide⟩
private def row759 : Fin 3173 := ⟨759, by decide⟩
private def row760 : Fin 3173 := ⟨760, by decide⟩

def source15818ObjectiveCoord204 : ℚ := q 0 1

def source15818Column204 : Array (RayEntry 3173) := #[
  { row := row210, value := q (-1) 1 },
  { row := row304, value := q 1 1 },
  { row := row461, value := q 4654212870180819 9007199254740992 },
  { row := row477, value := q (-4667021567102341) 9007199254740992 },
  { row := row491, value := q 4667021567102341 9007199254740992 },
  { row := row492, value := q (-4654212870180819) 9007199254740992 },
  { row := row759, value := q (-5404319552844595) 9007199254740992 },
  { row := row760, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue204 : ℚ :=
  source15818Column204.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord204

theorem source15818StationarityValue204Zero :
    source15818StationarityValue204 = 0 := by
  decide +kernel

end CarmenQExact
