import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity140
import CarmenQExact.Source15818Stationarity141
import CarmenQExact.Source15818Stationarity142
import CarmenQExact.Source15818Stationarity143

/-!
# Stationarity bridge shard 35 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn140 :
    stationarityAt source15818Data 140 = 0 := by
  change source15818StationarityValue140 = 0
  exact source15818StationarityValue140Zero

theorem source15818StationarityColumn141 :
    stationarityAt source15818Data 141 = 0 := by
  change source15818StationarityValue141 = 0
  exact source15818StationarityValue141Zero

theorem source15818StationarityColumn142 :
    stationarityAt source15818Data 142 = 0 := by
  change source15818StationarityValue142 = 0
  exact source15818StationarityValue142Zero

theorem source15818StationarityColumn143 :
    stationarityAt source15818Data 143 = 0 := by
  change source15818StationarityValue143 = 0
  exact source15818StationarityValue143Zero

end CarmenQExact
