import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 258 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row264 : Fin 3173 := ⟨264, by decide⟩
private def row787 : Fin 3173 := ⟨787, by decide⟩
private def row788 : Fin 3173 := ⟨788, by decide⟩
private def row791 : Fin 3173 := ⟨791, by decide⟩
private def row792 : Fin 3173 := ⟨792, by decide⟩

def source15818ObjectiveCoord258 : ℚ := q 0 1

def source15818Column258 : Array (RayEntry 3173) := #[
  { row := row264, value := q (-1) 1 },
  { row := row787, value := q 1 1 },
  { row := row788, value := q 1 1 },
  { row := row791, value := q (-5404319552844595) 9007199254740992 },
  { row := row792, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue258 : ℚ :=
  source15818Column258.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord258

theorem source15818StationarityValue258Zero :
    source15818StationarityValue258 = 0 := by
  decide +kernel

end CarmenQExact
