import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity184
import CarmenQExact.Source15818Stationarity185
import CarmenQExact.Source15818Stationarity186
import CarmenQExact.Source15818Stationarity187

/-!
# Stationarity bridge shard 46 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn184 :
    stationarityAt source15818Data 184 = 0 := by
  change source15818StationarityValue184 = 0
  exact source15818StationarityValue184Zero

theorem source15818StationarityColumn185 :
    stationarityAt source15818Data 185 = 0 := by
  change source15818StationarityValue185 = 0
  exact source15818StationarityValue185Zero

theorem source15818StationarityColumn186 :
    stationarityAt source15818Data 186 = 0 := by
  change source15818StationarityValue186 = 0
  exact source15818StationarityValue186Zero

theorem source15818StationarityColumn187 :
    stationarityAt source15818Data 187 = 0 := by
  change source15818StationarityValue187 = 0
  exact source15818StationarityValue187Zero

end CarmenQExact
