import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 245 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row251 : Fin 3173 := ⟨251, by decide⟩
private def row596 : Fin 3173 := ⟨596, by decide⟩
private def row597 : Fin 3173 := ⟨597, by decide⟩
private def row600 : Fin 3173 := ⟨600, by decide⟩
private def row913 : Fin 3173 := ⟨913, by decide⟩

def source15818ObjectiveCoord245 : ℚ := q 0 1

def source15818Column245 : Array (RayEntry 3173) := #[
  { row := row251, value := q (-1) 1 },
  { row := row596, value := q (-1) 1 },
  { row := row597, value := q (-1) 1 },
  { row := row600, value := q 1 1 },
  { row := row913, value := q (-1) 1 },
]

def source15818StationarityValue245 : ℚ :=
  source15818Column245.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord245

theorem source15818StationarityValue245Zero :
    source15818StationarityValue245 = 0 := by
  decide +kernel

end CarmenQExact
