import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 185 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row191 : Fin 3173 := ⟨191, by decide⟩
private def row285 : Fin 3173 := ⟨285, by decide⟩
private def row394 : Fin 3173 := ⟨394, by decide⟩
private def row410 : Fin 3173 := ⟨410, by decide⟩
private def row433 : Fin 3173 := ⟨433, by decide⟩
private def row434 : Fin 3173 := ⟨434, by decide⟩
private def row751 : Fin 3173 := ⟨751, by decide⟩
private def row752 : Fin 3173 := ⟨752, by decide⟩
private def row753 : Fin 3173 := ⟨753, by decide⟩
private def row754 : Fin 3173 := ⟨754, by decide⟩
private def row755 : Fin 3173 := ⟨755, by decide⟩
private def row756 : Fin 3173 := ⟨756, by decide⟩

def source15818ObjectiveCoord185 : ℚ := q 0 1

def source15818Column185 : Array (RayEntry 3173) := #[
  { row := row191, value := q (-1) 1 },
  { row := row285, value := q 1 1 },
  { row := row394, value := q 77829474067439 140737488355328 },
  { row := row410, value := q (-1248460991582811) 2251799813685248 },
  { row := row433, value := q 1248460991582811 2251799813685248 },
  { row := row434, value := q (-77829474067439) 140737488355328 },
  { row := row751, value := q 5404319552844595 9007199254740992 },
  { row := row752, value := q 2476979795053773 4503599627370496 },
  { row := row753, value := q 5404319552844595 9007199254740992 },
  { row := row754, value := q 2476979795053773 4503599627370496 },
  { row := row755, value := q 5404319552844595 9007199254740992 },
  { row := row756, value := q 2476979795053773 4503599627370496 },
]

def source15818StationarityValue185 : ℚ :=
  source15818Column185.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord185

theorem source15818StationarityValue185Zero :
    source15818StationarityValue185 = 0 := by
  decide +kernel

end CarmenQExact
