import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity208
import CarmenQExact.Source15818Stationarity209
import CarmenQExact.Source15818Stationarity210
import CarmenQExact.Source15818Stationarity211

/-!
# Stationarity bridge shard 52 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn208 :
    stationarityAt source15818Data 208 = 0 := by
  change source15818StationarityValue208 = 0
  exact source15818StationarityValue208Zero

theorem source15818StationarityColumn209 :
    stationarityAt source15818Data 209 = 0 := by
  change source15818StationarityValue209 = 0
  exact source15818StationarityValue209Zero

theorem source15818StationarityColumn210 :
    stationarityAt source15818Data 210 = 0 := by
  change source15818StationarityValue210 = 0
  exact source15818StationarityValue210Zero

theorem source15818StationarityColumn211 :
    stationarityAt source15818Data 211 = 0 := by
  change source15818StationarityValue211 = 0
  exact source15818StationarityValue211Zero

end CarmenQExact
