import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 206 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row212 : Fin 3173 := ⟨212, by decide⟩
private def row306 : Fin 3173 := ⟨306, by decide⟩
private def row463 : Fin 3173 := ⟨463, by decide⟩
private def row479 : Fin 3173 := ⟨479, by decide⟩
private def row507 : Fin 3173 := ⟨507, by decide⟩
private def row508 : Fin 3173 := ⟨508, by decide⟩
private def row761 : Fin 3173 := ⟨761, by decide⟩
private def row762 : Fin 3173 := ⟨762, by decide⟩

def source15818ObjectiveCoord206 : ℚ := q 0 1

def source15818Column206 : Array (RayEntry 3173) := #[
  { row := row212, value := q (-1) 1 },
  { row := row306, value := q 1 1 },
  { row := row463, value := q 4654212870180819 9007199254740992 },
  { row := row479, value := q (-1166755391775585) 2251799813685248 },
  { row := row507, value := q 1166755391775585 2251799813685248 },
  { row := row508, value := q (-4654212870180819) 9007199254740992 },
  { row := row761, value := q (-5404319552844595) 9007199254740992 },
  { row := row762, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue206 : ℚ :=
  source15818Column206.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord206

theorem source15818StationarityValue206Zero :
    source15818StationarityValue206 = 0 := by
  decide +kernel

end CarmenQExact
