import Mathlib.Tactic.IntervalCases
import CarmenQExact.Source15818StationarityBridge00
import CarmenQExact.Source15818StationarityBridge01
import CarmenQExact.Source15818StationarityBridge02
import CarmenQExact.Source15818StationarityBridge03
import CarmenQExact.Source15818StationarityBridge04
import CarmenQExact.Source15818StationarityBridge05
import CarmenQExact.Source15818StationarityBridge06
import CarmenQExact.Source15818StationarityBridge07
import CarmenQExact.Source15818StationarityBridge08
import CarmenQExact.Source15818StationarityBridge09
import CarmenQExact.Source15818StationarityBridge10
import CarmenQExact.Source15818StationarityBridge11
import CarmenQExact.Source15818StationarityBridge12
import CarmenQExact.Source15818StationarityBridge13
import CarmenQExact.Source15818StationarityBridge14
import CarmenQExact.Source15818StationarityBridge15
import CarmenQExact.Source15818StationarityBridge16
import CarmenQExact.Source15818StationarityBridge17
import CarmenQExact.Source15818StationarityBridge18
import CarmenQExact.Source15818StationarityBridge19
import CarmenQExact.Source15818StationarityBridge20
import CarmenQExact.Source15818StationarityBridge21
import CarmenQExact.Source15818StationarityBridge22
import CarmenQExact.Source15818StationarityBridge23
import CarmenQExact.Source15818StationarityBridge24
import CarmenQExact.Source15818StationarityBridge25
import CarmenQExact.Source15818StationarityBridge26
import CarmenQExact.Source15818StationarityBridge27
import CarmenQExact.Source15818StationarityBridge28
import CarmenQExact.Source15818StationarityBridge29
import CarmenQExact.Source15818StationarityBridge30
import CarmenQExact.Source15818StationarityBridge31
import CarmenQExact.Source15818StationarityBridge32
import CarmenQExact.Source15818StationarityBridge33
import CarmenQExact.Source15818StationarityBridge34
import CarmenQExact.Source15818StationarityBridge35
import CarmenQExact.Source15818StationarityBridge36
import CarmenQExact.Source15818StationarityBridge37
import CarmenQExact.Source15818StationarityBridge38
import CarmenQExact.Source15818StationarityBridge39
import CarmenQExact.Source15818StationarityBridge40
import CarmenQExact.Source15818StationarityBridge41
import CarmenQExact.Source15818StationarityBridge42
import CarmenQExact.Source15818StationarityBridge43
import CarmenQExact.Source15818StationarityBridge44
import CarmenQExact.Source15818StationarityBridge45
import CarmenQExact.Source15818StationarityBridge46
import CarmenQExact.Source15818StationarityBridge47
import CarmenQExact.Source15818StationarityBridge48
import CarmenQExact.Source15818StationarityBridge49
import CarmenQExact.Source15818StationarityBridge50
import CarmenQExact.Source15818StationarityBridge51
import CarmenQExact.Source15818StationarityBridge52
import CarmenQExact.Source15818StationarityBridge53
import CarmenQExact.Source15818StationarityBridge54
import CarmenQExact.Source15818StationarityBridge55
import CarmenQExact.Source15818StationarityBridge56
import CarmenQExact.Source15818StationarityBridge57
import CarmenQExact.Source15818StationarityBridge58
import CarmenQExact.Source15818StationarityBridge59
import CarmenQExact.Source15818StationarityBridge60
import CarmenQExact.Source15818StationarityBridge61
import CarmenQExact.Source15818StationarityBridge62
import CarmenQExact.Source15818StationarityBridge63
import CarmenQExact.Source15818StationarityBridge64
import CarmenQExact.Source15818StationarityBridge65
import CarmenQExact.Source15818StationarityBridge66
import CarmenQExact.Source15818StationarityBridge67
import CarmenQExact.Source15818StationarityBridge68
import CarmenQExact.Source15818StationarityBridge69
import CarmenQExact.Source15818StationarityBridge70

/-!
# Aggregate stationarity for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818Stationarity :
    ∀ column, column < source15818Data.variableCount →
      stationarityAt source15818Data column = 0 := by
  intro column hcolumn
  change column < 274 at hcolumn
  interval_cases column
  · exact source15818StationarityColumn000
  · exact source15818StationarityColumn001
  · exact source15818StationarityColumn002
  · exact source15818StationarityColumn003
  · exact source15818StationarityColumn004
  · exact source15818StationarityColumn005
  · exact source15818StationarityColumn006
  · exact source15818StationarityColumn007
  · exact source15818StationarityColumn008
  · exact source15818StationarityColumn009
  · exact source15818StationarityColumn010
  · exact source15818StationarityColumn011
  · exact source15818StationarityColumn012
  · exact source15818StationarityColumn013
  · exact source15818StationarityColumn014
  · exact source15818StationarityColumn015
  · exact source15818StationarityColumn016
  · exact source15818StationarityColumn017
  · exact source15818StationarityColumn018
  · exact source15818StationarityColumn019
  · exact source15818StationarityColumn020
  · exact source15818StationarityColumn021
  · exact source15818StationarityColumn022
  · exact source15818StationarityColumn023
  · exact source15818StationarityColumn024
  · exact source15818StationarityColumn025
  · exact source15818StationarityColumn026
  · exact source15818StationarityColumn027
  · exact source15818StationarityColumn028
  · exact source15818StationarityColumn029
  · exact source15818StationarityColumn030
  · exact source15818StationarityColumn031
  · exact source15818StationarityColumn032
  · exact source15818StationarityColumn033
  · exact source15818StationarityColumn034
  · exact source15818StationarityColumn035
  · exact source15818StationarityColumn036
  · exact source15818StationarityColumn037
  · exact source15818StationarityColumn038
  · exact source15818StationarityColumn039
  · exact source15818StationarityColumn040
  · exact source15818StationarityColumn041
  · exact source15818StationarityColumn042
  · exact source15818StationarityColumn043
  · exact source15818StationarityColumn044
  · exact source15818StationarityColumn045
  · exact source15818StationarityColumn046
  · exact source15818StationarityColumn047
  · exact source15818StationarityColumn048
  · exact source15818StationarityColumn049
  · exact source15818StationarityColumn050
  · exact source15818StationarityColumn051
  · exact source15818StationarityColumn052
  · exact source15818StationarityColumn053
  · exact source15818StationarityColumn054
  · exact source15818StationarityColumn055
  · exact source15818StationarityColumn056
  · exact source15818StationarityColumn057
  · exact source15818StationarityColumn058
  · exact source15818StationarityColumn059
  · exact source15818StationarityColumn060
  · exact source15818StationarityColumn061
  · exact source15818StationarityColumn062
  · exact source15818StationarityColumn063
  · exact source15818StationarityColumn064
  · exact source15818StationarityColumn065
  · exact source15818StationarityColumn066
  · exact source15818StationarityColumn067
  · exact source15818StationarityColumn068
  · exact source15818StationarityColumn069
  · exact source15818StationarityColumn070
  · exact source15818StationarityColumn071
  · exact source15818StationarityColumn072
  · exact source15818StationarityColumn073
  · exact source15818StationarityColumn074
  · exact source15818StationarityColumn075
  · exact source15818StationarityColumn076
  · exact source15818StationarityColumn077
  · exact source15818StationarityColumn078
  · exact source15818StationarityColumn079
  · exact source15818StationarityColumn080
  · exact source15818StationarityColumn081
  · exact source15818StationarityColumn082
  · exact source15818StationarityColumn083
  · exact source15818StationarityColumn084
  · exact source15818StationarityColumn085
  · exact source15818StationarityColumn086
  · exact source15818StationarityColumn087
  · exact source15818StationarityColumn088
  · exact source15818StationarityColumn089
  · exact source15818StationarityColumn090
  · exact source15818StationarityColumn091
  · exact source15818StationarityColumn092
  · exact source15818StationarityColumn093
  · exact source15818StationarityColumn094
  · exact source15818StationarityColumn095
  · exact source15818StationarityColumn096
  · exact source15818StationarityColumn097
  · exact source15818StationarityColumn098
  · exact source15818StationarityColumn099
  · exact source15818StationarityColumn100
  · exact source15818StationarityColumn101
  · exact source15818StationarityColumn102
  · exact source15818StationarityColumn103
  · exact source15818StationarityColumn104
  · exact source15818StationarityColumn105
  · exact source15818StationarityColumn106
  · exact source15818StationarityColumn107
  · exact source15818StationarityColumn108
  · exact source15818StationarityColumn109
  · exact source15818StationarityColumn110
  · exact source15818StationarityColumn111
  · exact source15818StationarityColumn112
  · exact source15818StationarityColumn113
  · exact source15818StationarityColumn114
  · exact source15818StationarityColumn115
  · exact source15818StationarityColumn116
  · exact source15818StationarityColumn117
  · exact source15818StationarityColumn118
  · exact source15818StationarityColumn119
  · exact source15818StationarityColumn120
  · exact source15818StationarityColumn121
  · exact source15818StationarityColumn122
  · exact source15818StationarityColumn123
  · exact source15818StationarityColumn124
  · exact source15818StationarityColumn125
  · exact source15818StationarityColumn126
  · exact source15818StationarityColumn127
  · exact source15818StationarityColumn128
  · exact source15818StationarityColumn129
  · exact source15818StationarityColumn130
  · exact source15818StationarityColumn131
  · exact source15818StationarityColumn132
  · exact source15818StationarityColumn133
  · exact source15818StationarityColumn134
  · exact source15818StationarityColumn135
  · exact source15818StationarityColumn136
  · exact source15818StationarityColumn137
  · exact source15818StationarityColumn138
  · exact source15818StationarityColumn139
  · exact source15818StationarityColumn140
  · exact source15818StationarityColumn141
  · exact source15818StationarityColumn142
  · exact source15818StationarityColumn143
  · exact source15818StationarityColumn144
  · exact source15818StationarityColumn145
  · exact source15818StationarityColumn146
  · exact source15818StationarityColumn147
  · exact source15818StationarityColumn148
  · exact source15818StationarityColumn149
  · exact source15818StationarityColumn150
  · exact source15818StationarityColumn151
  · exact source15818StationarityColumn152
  · exact source15818StationarityColumn153
  · exact source15818StationarityColumn154
  · exact source15818StationarityColumn155
  · exact source15818StationarityColumn156
  · exact source15818StationarityColumn157
  · exact source15818StationarityColumn158
  · exact source15818StationarityColumn159
  · exact source15818StationarityColumn160
  · exact source15818StationarityColumn161
  · exact source15818StationarityColumn162
  · exact source15818StationarityColumn163
  · exact source15818StationarityColumn164
  · exact source15818StationarityColumn165
  · exact source15818StationarityColumn166
  · exact source15818StationarityColumn167
  · exact source15818StationarityColumn168
  · exact source15818StationarityColumn169
  · exact source15818StationarityColumn170
  · exact source15818StationarityColumn171
  · exact source15818StationarityColumn172
  · exact source15818StationarityColumn173
  · exact source15818StationarityColumn174
  · exact source15818StationarityColumn175
  · exact source15818StationarityColumn176
  · exact source15818StationarityColumn177
  · exact source15818StationarityColumn178
  · exact source15818StationarityColumn179
  · exact source15818StationarityColumn180
  · exact source15818StationarityColumn181
  · exact source15818StationarityColumn182
  · exact source15818StationarityColumn183
  · exact source15818StationarityColumn184
  · exact source15818StationarityColumn185
  · exact source15818StationarityColumn186
  · exact source15818StationarityColumn187
  · exact source15818StationarityColumn188
  · exact source15818StationarityColumn189
  · exact source15818StationarityColumn190
  · exact source15818StationarityColumn191
  · exact source15818StationarityColumn192
  · exact source15818StationarityColumn193
  · exact source15818StationarityColumn194
  · exact source15818StationarityColumn195
  · exact source15818StationarityColumn196
  · exact source15818StationarityColumn197
  · exact source15818StationarityColumn198
  · exact source15818StationarityColumn199
  · exact source15818StationarityColumn200
  · exact source15818StationarityColumn201
  · exact source15818StationarityColumn202
  · exact source15818StationarityColumn203
  · exact source15818StationarityColumn204
  · exact source15818StationarityColumn205
  · exact source15818StationarityColumn206
  · exact source15818StationarityColumn207
  · exact source15818StationarityColumn208
  · exact source15818StationarityColumn209
  · exact source15818StationarityColumn210
  · exact source15818StationarityColumn211
  · exact source15818StationarityColumn212
  · exact source15818StationarityColumn213
  · exact source15818StationarityColumn214
  · exact source15818StationarityColumn215
  · exact source15818StationarityColumn216
  · exact source15818StationarityColumn217
  · exact source15818StationarityColumn218
  · exact source15818StationarityColumn219
  · exact source15818StationarityColumn220
  · exact source15818StationarityColumn221
  · exact source15818StationarityColumn222
  · exact source15818StationarityColumn223
  · exact source15818StationarityColumn224
  · exact source15818StationarityColumn225
  · exact source15818StationarityColumn226
  · exact source15818StationarityColumn227
  · exact source15818StationarityColumn228
  · exact source15818StationarityColumn229
  · exact source15818StationarityColumn230
  · exact source15818StationarityColumn231
  · exact source15818StationarityColumn232
  · exact source15818StationarityColumn233
  · exact source15818StationarityColumn234
  · exact source15818StationarityColumn235
  · exact source15818StationarityColumn236
  · exact source15818StationarityColumn237
  · exact source15818StationarityColumn238
  · exact source15818StationarityColumn239
  · exact source15818StationarityColumn240
  · exact source15818StationarityColumn241
  · exact source15818StationarityColumn242
  · exact source15818StationarityColumn243
  · exact source15818StationarityColumn244
  · exact source15818StationarityColumn245
  · exact source15818StationarityColumn246
  · exact source15818StationarityColumn247
  · exact source15818StationarityColumn248
  · exact source15818StationarityColumn249
  · exact source15818StationarityColumn250
  · exact source15818StationarityColumn251
  · exact source15818StationarityColumn252
  · exact source15818StationarityColumn253
  · exact source15818StationarityColumn254
  · exact source15818StationarityColumn255
  · exact source15818StationarityColumn256
  · exact source15818StationarityColumn257
  · exact source15818StationarityColumn258
  · exact source15818StationarityColumn259
  · exact source15818StationarityColumn260
  · exact source15818StationarityColumn261
  · exact source15818StationarityColumn262
  · exact source15818StationarityColumn263
  · exact source15818StationarityColumn264
  · exact source15818StationarityColumn265
  · exact source15818StationarityColumn266
  · exact source15818StationarityColumn267
  · exact source15818StationarityColumn268
  · exact source15818StationarityColumn269
  · exact source15818StationarityColumn270
  · exact source15818StationarityColumn271
  · exact source15818StationarityColumn272
  · exact source15818StationarityColumn273

end CarmenQExact
