import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity120
import CarmenQExact.Source15818Stationarity121
import CarmenQExact.Source15818Stationarity122
import CarmenQExact.Source15818Stationarity123

/-!
# Stationarity bridge shard 30 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn120 :
    stationarityAt source15818Data 120 = 0 := by
  change source15818StationarityValue120 = 0
  exact source15818StationarityValue120Zero

theorem source15818StationarityColumn121 :
    stationarityAt source15818Data 121 = 0 := by
  change source15818StationarityValue121 = 0
  exact source15818StationarityValue121Zero

theorem source15818StationarityColumn122 :
    stationarityAt source15818Data 122 = 0 := by
  change source15818StationarityValue122 = 0
  exact source15818StationarityValue122Zero

theorem source15818StationarityColumn123 :
    stationarityAt source15818Data 123 = 0 := by
  change source15818StationarityValue123 = 0
  exact source15818StationarityValue123Zero

end CarmenQExact
