import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity56
import CarmenQExact.Source15818Stationarity57
import CarmenQExact.Source15818Stationarity58
import CarmenQExact.Source15818Stationarity59

/-!
# Stationarity bridge shard 14 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn056 :
    stationarityAt source15818Data 56 = 0 := by
  change source15818StationarityValue056 = 0
  exact source15818StationarityValue056Zero

theorem source15818StationarityColumn057 :
    stationarityAt source15818Data 57 = 0 := by
  change source15818StationarityValue057 = 0
  exact source15818StationarityValue057Zero

theorem source15818StationarityColumn058 :
    stationarityAt source15818Data 58 = 0 := by
  change source15818StationarityValue058 = 0
  exact source15818StationarityValue058Zero

theorem source15818StationarityColumn059 :
    stationarityAt source15818Data 59 = 0 := by
  change source15818StationarityValue059 = 0
  exact source15818StationarityValue059Zero

end CarmenQExact
