import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 246 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row252 : Fin 3173 := ⟨252, by decide⟩
private def row598 : Fin 3173 := ⟨598, by decide⟩
private def row599 : Fin 3173 := ⟨599, by decide⟩
private def row600 : Fin 3173 := ⟨600, by decide⟩
private def row916 : Fin 3173 := ⟨916, by decide⟩

def source15818ObjectiveCoord246 : ℚ := q 0 1

def source15818Column246 : Array (RayEntry 3173) := #[
  { row := row252, value := q (-1) 1 },
  { row := row598, value := q (-1) 1 },
  { row := row599, value := q (-1) 1 },
  { row := row600, value := q 1 1 },
  { row := row916, value := q (-1) 1 },
]

def source15818StationarityValue246 : ℚ :=
  source15818Column246.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord246

theorem source15818StationarityValue246Zero :
    source15818StationarityValue246 = 0 := by
  decide +kernel

end CarmenQExact
