import CarmenQExact.EncodedWeakDuality
import CarmenQExact.Source15818Exact

/-!
# Decoded consequences for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

open scoped BigOperators

theorem source15818DecodedWeakDuality
    (point : Fin source15818Data.variableCount → ℝ)
    (slack : Fin source15818Data.rows → ℝ)
    (feasible : CanonicalFeasible
      (decodedMatrix source15818Data) (decodedRight source15818Data)
      point slack)
    (hslack : ProductConePoint (extendFin slack)
      source15818Data.zeroDim source15818Data.nonnegativeDim
      source15818Data.socSizes.toList) :
    -(∑ column, decodedObjective source15818Data column * point column) ≤
      (certifiedUpper source15818Data : ℝ) :=
  exactCertificate_decoded_weak_duality
    source15818Data source15818Exact point slack feasible hslack

theorem source15818DecodedStrictTarget
    (point : Fin source15818Data.variableCount → ℝ)
    (slack : Fin source15818Data.rows → ℝ)
    (feasible : CanonicalFeasible
      (decodedMatrix source15818Data) (decodedRight source15818Data)
      point slack)
    (hslack : ProductConePoint (extendFin slack)
      source15818Data.zeroDim source15818Data.nonnegativeDim
      source15818Data.socSizes.toList) :
    -(∑ column, decodedObjective source15818Data column * point column) <
      (source15818Data.target : ℝ) :=
  exactCertificate_decoded_strict_target
    source15818Data source15818Exact point slack feasible hslack

end CarmenQExact
