import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 181 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row187 : Fin 3173 := ⟨187, by decide⟩
private def row281 : Fin 3173 := ⟨281, by decide⟩
private def row342 : Fin 3173 := ⟨342, by decide⟩
private def row358 : Fin 3173 := ⟨358, by decide⟩
private def row375 : Fin 3173 := ⟨375, by decide⟩
private def row376 : Fin 3173 := ⟨376, by decide⟩
private def row747 : Fin 3173 := ⟨747, by decide⟩
private def row748 : Fin 3173 := ⟨748, by decide⟩

def source15818ObjectiveCoord181 : ℚ := q 0 1

def source15818Column181 : Array (RayEntry 3173) := #[
  { row := row187, value := q (-1) 1 },
  { row := row281, value := q 1 1 },
  { row := row342, value := q 261175671186813 281474976710656 },
  { row := row358, value := q (-2093748593682989) 2251799813685248 },
  { row := row375, value := q 2093748593682989 2251799813685248 },
  { row := row376, value := q (-261175671186813) 281474976710656 },
  { row := row747, value := q (-5404319552844595) 9007199254740992 },
  { row := row748, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue181 : ℚ :=
  source15818Column181.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord181

theorem source15818StationarityValue181Zero :
    source15818StationarityValue181 = 0 := by
  decide +kernel

end CarmenQExact
