import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 225 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row231 : Fin 3173 := ⟨231, by decide⟩
private def row550 : Fin 3173 := ⟨550, by decide⟩
private def row551 : Fin 3173 := ⟨551, by decide⟩
private def row555 : Fin 3173 := ⟨555, by decide⟩
private def row833 : Fin 3173 := ⟨833, by decide⟩

def source15818ObjectiveCoord225 : ℚ := q 0 1

def source15818Column225 : Array (RayEntry 3173) := #[
  { row := row231, value := q (-1) 1 },
  { row := row550, value := q (-1) 1 },
  { row := row551, value := q (-1) 1 },
  { row := row555, value := q 1 1 },
  { row := row833, value := q (-1) 1 },
]

def source15818StationarityValue225 : ℚ :=
  source15818Column225.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord225

theorem source15818StationarityValue225Zero :
    source15818StationarityValue225 = 0 := by
  decide +kernel

end CarmenQExact
