import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 192 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row198 : Fin 3173 := ⟨198, by decide⟩
private def row292 : Fin 3173 := ⟨292, by decide⟩
private def row401 : Fin 3173 := ⟨401, by decide⟩
private def row417 : Fin 3173 := ⟨417, by decide⟩
private def row429 : Fin 3173 := ⟨429, by decide⟩
private def row430 : Fin 3173 := ⟨430, by decide⟩
private def row753 : Fin 3173 := ⟨753, by decide⟩
private def row754 : Fin 3173 := ⟨754, by decide⟩

def source15818ObjectiveCoord192 : ℚ := q 0 1

def source15818Column192 : Array (RayEntry 3173) := #[
  { row := row198, value := q (-1) 1 },
  { row := row292, value := q 1 1 },
  { row := row401, value := q 77829474067439 140737488355328 },
  { row := row417, value := q (-4993843966331245) 9007199254740992 },
  { row := row429, value := q 4993843966331245 9007199254740992 },
  { row := row430, value := q (-77829474067439) 140737488355328 },
  { row := row753, value := q (-5404319552844595) 9007199254740992 },
  { row := row754, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue192 : ℚ :=
  source15818Column192.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord192

theorem source15818StationarityValue192Zero :
    source15818StationarityValue192 = 0 := by
  decide +kernel

end CarmenQExact
