import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 211 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row217 : Fin 3173 := ⟨217, by decide⟩
private def row311 : Fin 3173 := ⟨311, by decide⟩
private def row468 : Fin 3173 := ⟨468, by decide⟩
private def row484 : Fin 3173 := ⟨484, by decide⟩
private def row517 : Fin 3173 := ⟨517, by decide⟩
private def row518 : Fin 3173 := ⟨518, by decide⟩
private def row759 : Fin 3173 := ⟨759, by decide⟩
private def row760 : Fin 3173 := ⟨760, by decide⟩

def source15818ObjectiveCoord211 : ℚ := q 0 1

def source15818Column211 : Array (RayEntry 3173) := #[
  { row := row217, value := q (-1) 1 },
  { row := row311, value := q 1 1 },
  { row := row468, value := q 4654212870180819 9007199254740992 },
  { row := row484, value := q (-4667021567102341) 9007199254740992 },
  { row := row517, value := q 4667021567102341 9007199254740992 },
  { row := row518, value := q (-4654212870180819) 9007199254740992 },
  { row := row759, value := q (-5404319552844595) 9007199254740992 },
  { row := row760, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue211 : ℚ :=
  source15818Column211.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord211

theorem source15818StationarityValue211Zero :
    source15818StationarityValue211 = 0 := by
  decide +kernel

end CarmenQExact
