import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity88
import CarmenQExact.Source15818Stationarity89
import CarmenQExact.Source15818Stationarity90
import CarmenQExact.Source15818Stationarity91

/-!
# Stationarity bridge shard 22 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn088 :
    stationarityAt source15818Data 88 = 0 := by
  change source15818StationarityValue088 = 0
  exact source15818StationarityValue088Zero

theorem source15818StationarityColumn089 :
    stationarityAt source15818Data 89 = 0 := by
  change source15818StationarityValue089 = 0
  exact source15818StationarityValue089Zero

theorem source15818StationarityColumn090 :
    stationarityAt source15818Data 90 = 0 := by
  change source15818StationarityValue090 = 0
  exact source15818StationarityValue090Zero

theorem source15818StationarityColumn091 :
    stationarityAt source15818Data 91 = 0 := by
  change source15818StationarityValue091 = 0
  exact source15818StationarityValue091Zero

end CarmenQExact
