import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 227 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row233 : Fin 3173 := ⟨233, by decide⟩
private def row556 : Fin 3173 := ⟨556, by decide⟩
private def row557 : Fin 3173 := ⟨557, by decide⟩
private def row564 : Fin 3173 := ⟨564, by decide⟩
private def row843 : Fin 3173 := ⟨843, by decide⟩

def source15818ObjectiveCoord227 : ℚ := q 0 1

def source15818Column227 : Array (RayEntry 3173) := #[
  { row := row233, value := q (-1) 1 },
  { row := row556, value := q (-1) 1 },
  { row := row557, value := q (-1) 1 },
  { row := row564, value := q 1 1 },
  { row := row843, value := q (-1) 1 },
]

def source15818StationarityValue227 : ℚ :=
  source15818Column227.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord227

theorem source15818StationarityValue227Zero :
    source15818StationarityValue227 = 0 := by
  decide +kernel

end CarmenQExact
