import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity128
import CarmenQExact.Source15818Stationarity129
import CarmenQExact.Source15818Stationarity130
import CarmenQExact.Source15818Stationarity131

/-!
# Stationarity bridge shard 32 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn128 :
    stationarityAt source15818Data 128 = 0 := by
  change source15818StationarityValue128 = 0
  exact source15818StationarityValue128Zero

theorem source15818StationarityColumn129 :
    stationarityAt source15818Data 129 = 0 := by
  change source15818StationarityValue129 = 0
  exact source15818StationarityValue129Zero

theorem source15818StationarityColumn130 :
    stationarityAt source15818Data 130 = 0 := by
  change source15818StationarityValue130 = 0
  exact source15818StationarityValue130Zero

theorem source15818StationarityColumn131 :
    stationarityAt source15818Data 131 = 0 := by
  change source15818StationarityValue131 = 0
  exact source15818StationarityValue131Zero

end CarmenQExact
