import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 177 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row183 : Fin 3173 := ⟨183, by decide⟩
private def row277 : Fin 3173 := ⟨277, by decide⟩
private def row338 : Fin 3173 := ⟨338, by decide⟩
private def row354 : Fin 3173 := ⟨354, by decide⟩
private def row373 : Fin 3173 := ⟨373, by decide⟩
private def row374 : Fin 3173 := ⟨374, by decide⟩
private def row749 : Fin 3173 := ⟨749, by decide⟩
private def row750 : Fin 3173 := ⟨750, by decide⟩

def source15818ObjectiveCoord177 : ℚ := q 0 1

def source15818Column177 : Array (RayEntry 3173) := #[
  { row := row183, value := q (-1) 1 },
  { row := row277, value := q 1 1 },
  { row := row338, value := q 261175671186813 281474976710656 },
  { row := row354, value := q (-2093748593682989) 2251799813685248 },
  { row := row373, value := q 2093748593682989 2251799813685248 },
  { row := row374, value := q (-261175671186813) 281474976710656 },
  { row := row749, value := q (-5404319552844595) 9007199254740992 },
  { row := row750, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue177 : ℚ :=
  source15818Column177.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord177

theorem source15818StationarityValue177Zero :
    source15818StationarityValue177 = 0 := by
  decide +kernel

end CarmenQExact
