import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 219 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row225 : Fin 3173 := ⟨225, by decide⟩
private def row536 : Fin 3173 := ⟨536, by decide⟩
private def row537 : Fin 3173 := ⟨537, by decide⟩
private def row545 : Fin 3173 := ⟨545, by decide⟩
private def row815 : Fin 3173 := ⟨815, by decide⟩

def source15818ObjectiveCoord219 : ℚ := q 0 1

def source15818Column219 : Array (RayEntry 3173) := #[
  { row := row225, value := q (-1) 1 },
  { row := row536, value := q (-1) 1 },
  { row := row537, value := q (-1) 1 },
  { row := row545, value := q 1 1 },
  { row := row815, value := q (-1) 1 },
]

def source15818StationarityValue219 : ℚ :=
  source15818Column219.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord219

theorem source15818StationarityValue219Zero :
    source15818StationarityValue219 = 0 := by
  decide +kernel

end CarmenQExact
