import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 193 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row199 : Fin 3173 := ⟨199, by decide⟩
private def row293 : Fin 3173 := ⟨293, by decide⟩
private def row402 : Fin 3173 := ⟨402, by decide⟩
private def row418 : Fin 3173 := ⟨418, by decide⟩
private def row437 : Fin 3173 := ⟨437, by decide⟩
private def row438 : Fin 3173 := ⟨438, by decide⟩
private def row755 : Fin 3173 := ⟨755, by decide⟩
private def row756 : Fin 3173 := ⟨756, by decide⟩

def source15818ObjectiveCoord193 : ℚ := q 0 1

def source15818Column193 : Array (RayEntry 3173) := #[
  { row := row199, value := q (-1) 1 },
  { row := row293, value := q 1 1 },
  { row := row402, value := q 77829474067439 140737488355328 },
  { row := row418, value := q (-1248460991582811) 2251799813685248 },
  { row := row437, value := q 1248460991582811 2251799813685248 },
  { row := row438, value := q (-77829474067439) 140737488355328 },
  { row := row755, value := q (-5404319552844595) 9007199254740992 },
  { row := row756, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue193 : ℚ :=
  source15818Column193.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord193

theorem source15818StationarityValue193Zero :
    source15818StationarityValue193 = 0 := by
  decide +kernel

end CarmenQExact
