import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 256 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row262 : Fin 3173 := ⟨262, by decide⟩
private def row781 : Fin 3173 := ⟨781, by decide⟩
private def row782 : Fin 3173 := ⟨782, by decide⟩
private def row785 : Fin 3173 := ⟨785, by decide⟩
private def row786 : Fin 3173 := ⟨786, by decide⟩

def source15818ObjectiveCoord256 : ℚ := q 0 1

def source15818Column256 : Array (RayEntry 3173) := #[
  { row := row262, value := q (-1) 1 },
  { row := row781, value := q 1 1 },
  { row := row782, value := q 1 1 },
  { row := row785, value := q (-5404319552844595) 9007199254740992 },
  { row := row786, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue256 : ℚ :=
  source15818Column256.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord256

theorem source15818StationarityValue256Zero :
    source15818StationarityValue256 = 0 := by
  decide +kernel

end CarmenQExact
