import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 187 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row193 : Fin 3173 := ⟨193, by decide⟩
private def row287 : Fin 3173 := ⟨287, by decide⟩
private def row396 : Fin 3173 := ⟨396, by decide⟩
private def row412 : Fin 3173 := ⟨412, by decide⟩
private def row449 : Fin 3173 := ⟨449, by decide⟩
private def row450 : Fin 3173 := ⟨450, by decide⟩
private def row755 : Fin 3173 := ⟨755, by decide⟩
private def row756 : Fin 3173 := ⟨756, by decide⟩

def source15818ObjectiveCoord187 : ℚ := q 0 1

def source15818Column187 : Array (RayEntry 3173) := #[
  { row := row193, value := q (-1) 1 },
  { row := row287, value := q 1 1 },
  { row := row396, value := q 77829474067439 140737488355328 },
  { row := row412, value := q (-1248460991582811) 2251799813685248 },
  { row := row449, value := q 1248460991582811 2251799813685248 },
  { row := row450, value := q (-77829474067439) 140737488355328 },
  { row := row755, value := q (-5404319552844595) 9007199254740992 },
  { row := row756, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue187 : ℚ :=
  source15818Column187.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord187

theorem source15818StationarityValue187Zero :
    source15818StationarityValue187 = 0 := by
  decide +kernel

end CarmenQExact
