import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity148
import CarmenQExact.Source15818Stationarity149
import CarmenQExact.Source15818Stationarity150
import CarmenQExact.Source15818Stationarity151

/-!
# Stationarity bridge shard 37 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn148 :
    stationarityAt source15818Data 148 = 0 := by
  change source15818StationarityValue148 = 0
  exact source15818StationarityValue148Zero

theorem source15818StationarityColumn149 :
    stationarityAt source15818Data 149 = 0 := by
  change source15818StationarityValue149 = 0
  exact source15818StationarityValue149Zero

theorem source15818StationarityColumn150 :
    stationarityAt source15818Data 150 = 0 := by
  change source15818StationarityValue150 = 0
  exact source15818StationarityValue150Zero

theorem source15818StationarityColumn151 :
    stationarityAt source15818Data 151 = 0 := by
  change source15818StationarityValue151 = 0
  exact source15818StationarityValue151Zero

end CarmenQExact
