import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 183 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row189 : Fin 3173 := ⟨189, by decide⟩
private def row283 : Fin 3173 := ⟨283, by decide⟩
private def row344 : Fin 3173 := ⟨344, by decide⟩
private def row360 : Fin 3173 := ⟨360, by decide⟩
private def row391 : Fin 3173 := ⟨391, by decide⟩
private def row392 : Fin 3173 := ⟨392, by decide⟩
private def row745 : Fin 3173 := ⟨745, by decide⟩
private def row746 : Fin 3173 := ⟨746, by decide⟩
private def row747 : Fin 3173 := ⟨747, by decide⟩
private def row748 : Fin 3173 := ⟨748, by decide⟩
private def row749 : Fin 3173 := ⟨749, by decide⟩
private def row750 : Fin 3173 := ⟨750, by decide⟩

def source15818ObjectiveCoord183 : ℚ := q 0 1

def source15818Column183 : Array (RayEntry 3173) := #[
  { row := row189, value := q (-1) 1 },
  { row := row283, value := q 1 1 },
  { row := row344, value := q 261175671186813 281474976710656 },
  { row := row360, value := q (-8374994374731957) 9007199254740992 },
  { row := row391, value := q 8374994374731957 9007199254740992 },
  { row := row392, value := q (-261175671186813) 281474976710656 },
  { row := row745, value := q 5404319552844595 9007199254740992 },
  { row := row746, value := q 2476979795053773 4503599627370496 },
  { row := row747, value := q 5404319552844595 9007199254740992 },
  { row := row748, value := q 2476979795053773 4503599627370496 },
  { row := row749, value := q 5404319552844595 9007199254740992 },
  { row := row750, value := q 2476979795053773 4503599627370496 },
]

def source15818StationarityValue183 : ℚ :=
  source15818Column183.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord183

theorem source15818StationarityValue183Zero :
    source15818StationarityValue183 = 0 := by
  decide +kernel

end CarmenQExact
