import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 241 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row247 : Fin 3173 := ⟨247, by decide⟩
private def row587 : Fin 3173 := ⟨587, by decide⟩
private def row588 : Fin 3173 := ⟨588, by decide⟩
private def row591 : Fin 3173 := ⟨591, by decide⟩
private def row897 : Fin 3173 := ⟨897, by decide⟩

def source15818ObjectiveCoord241 : ℚ := q 0 1

def source15818Column241 : Array (RayEntry 3173) := #[
  { row := row247, value := q (-1) 1 },
  { row := row587, value := q (-1) 1 },
  { row := row588, value := q (-1) 1 },
  { row := row591, value := q 1 1 },
  { row := row897, value := q (-1) 1 },
]

def source15818StationarityValue241 : ℚ :=
  source15818Column241.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord241

theorem source15818StationarityValue241Zero :
    source15818StationarityValue241 = 0 := by
  decide +kernel

end CarmenQExact
