import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 231 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row237 : Fin 3173 := ⟨237, by decide⟩
private def row565 : Fin 3173 := ⟨565, by decide⟩
private def row566 : Fin 3173 := ⟨566, by decide⟩
private def row573 : Fin 3173 := ⟨573, by decide⟩
private def row859 : Fin 3173 := ⟨859, by decide⟩

def source15818ObjectiveCoord231 : ℚ := q 0 1

def source15818Column231 : Array (RayEntry 3173) := #[
  { row := row237, value := q (-1) 1 },
  { row := row565, value := q (-1) 1 },
  { row := row566, value := q (-1) 1 },
  { row := row573, value := q 1 1 },
  { row := row859, value := q (-1) 1 },
]

def source15818StationarityValue231 : ℚ :=
  source15818Column231.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord231

theorem source15818StationarityValue231Zero :
    source15818StationarityValue231 = 0 := by
  decide +kernel

end CarmenQExact
