import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity04
import CarmenQExact.Source15818Stationarity05
import CarmenQExact.Source15818Stationarity06
import CarmenQExact.Source15818Stationarity07

/-!
# Stationarity bridge shard 01 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn004 :
    stationarityAt source15818Data 4 = 0 := by
  change source15818StationarityValue004 = 0
  exact source15818StationarityValue004Zero

theorem source15818StationarityColumn005 :
    stationarityAt source15818Data 5 = 0 := by
  change source15818StationarityValue005 = 0
  exact source15818StationarityValue005Zero

theorem source15818StationarityColumn006 :
    stationarityAt source15818Data 6 = 0 := by
  change source15818StationarityValue006 = 0
  exact source15818StationarityValue006Zero

theorem source15818StationarityColumn007 :
    stationarityAt source15818Data 7 = 0 := by
  change source15818StationarityValue007 = 0
  exact source15818StationarityValue007Zero

end CarmenQExact
