import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 237 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row243 : Fin 3173 := ⟨243, by decide⟩
private def row578 : Fin 3173 := ⟨578, by decide⟩
private def row579 : Fin 3173 := ⟨579, by decide⟩
private def row582 : Fin 3173 := ⟨582, by decide⟩
private def row881 : Fin 3173 := ⟨881, by decide⟩

def source15818ObjectiveCoord237 : ℚ := q 0 1

def source15818Column237 : Array (RayEntry 3173) := #[
  { row := row243, value := q (-1) 1 },
  { row := row578, value := q (-1) 1 },
  { row := row579, value := q (-1) 1 },
  { row := row582, value := q 1 1 },
  { row := row881, value := q (-1) 1 },
]

def source15818StationarityValue237 : ℚ :=
  source15818Column237.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord237

theorem source15818StationarityValue237Zero :
    source15818StationarityValue237 = 0 := by
  decide +kernel

end CarmenQExact
