import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity68
import CarmenQExact.Source15818Stationarity69
import CarmenQExact.Source15818Stationarity70
import CarmenQExact.Source15818Stationarity71

/-!
# Stationarity bridge shard 17 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn068 :
    stationarityAt source15818Data 68 = 0 := by
  change source15818StationarityValue068 = 0
  exact source15818StationarityValue068Zero

theorem source15818StationarityColumn069 :
    stationarityAt source15818Data 69 = 0 := by
  change source15818StationarityValue069 = 0
  exact source15818StationarityValue069Zero

theorem source15818StationarityColumn070 :
    stationarityAt source15818Data 70 = 0 := by
  change source15818StationarityValue070 = 0
  exact source15818StationarityValue070Zero

theorem source15818StationarityColumn071 :
    stationarityAt source15818Data 71 = 0 := by
  change source15818StationarityValue071 = 0
  exact source15818StationarityValue071Zero

end CarmenQExact
