import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 239 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row245 : Fin 3173 := ⟨245, by decide⟩
private def row583 : Fin 3173 := ⟨583, by decide⟩
private def row584 : Fin 3173 := ⟨584, by decide⟩
private def row591 : Fin 3173 := ⟨591, by decide⟩
private def row891 : Fin 3173 := ⟨891, by decide⟩

def source15818ObjectiveCoord239 : ℚ := q 0 1

def source15818Column239 : Array (RayEntry 3173) := #[
  { row := row245, value := q (-1) 1 },
  { row := row583, value := q (-1) 1 },
  { row := row584, value := q (-1) 1 },
  { row := row591, value := q 1 1 },
  { row := row891, value := q (-1) 1 },
]

def source15818StationarityValue239 : ℚ :=
  source15818Column239.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord239

theorem source15818StationarityValue239Zero :
    source15818StationarityValue239 = 0 := by
  decide +kernel

end CarmenQExact
