import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity36
import CarmenQExact.Source15818Stationarity37
import CarmenQExact.Source15818Stationarity38
import CarmenQExact.Source15818Stationarity39

/-!
# Stationarity bridge shard 09 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn036 :
    stationarityAt source15818Data 36 = 0 := by
  change source15818StationarityValue036 = 0
  exact source15818StationarityValue036Zero

theorem source15818StationarityColumn037 :
    stationarityAt source15818Data 37 = 0 := by
  change source15818StationarityValue037 = 0
  exact source15818StationarityValue037Zero

theorem source15818StationarityColumn038 :
    stationarityAt source15818Data 38 = 0 := by
  change source15818StationarityValue038 = 0
  exact source15818StationarityValue038Zero

theorem source15818StationarityColumn039 :
    stationarityAt source15818Data 39 = 0 := by
  change source15818StationarityValue039 = 0
  exact source15818StationarityValue039Zero

end CarmenQExact
