import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity156
import CarmenQExact.Source15818Stationarity157
import CarmenQExact.Source15818Stationarity158
import CarmenQExact.Source15818Stationarity159

/-!
# Stationarity bridge shard 39 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn156 :
    stationarityAt source15818Data 156 = 0 := by
  change source15818StationarityValue156 = 0
  exact source15818StationarityValue156Zero

theorem source15818StationarityColumn157 :
    stationarityAt source15818Data 157 = 0 := by
  change source15818StationarityValue157 = 0
  exact source15818StationarityValue157Zero

theorem source15818StationarityColumn158 :
    stationarityAt source15818Data 158 = 0 := by
  change source15818StationarityValue158 = 0
  exact source15818StationarityValue158Zero

theorem source15818StationarityColumn159 :
    stationarityAt source15818Data 159 = 0 := by
  change source15818StationarityValue159 = 0
  exact source15818StationarityValue159Zero

end CarmenQExact
