import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity224
import CarmenQExact.Source15818Stationarity225
import CarmenQExact.Source15818Stationarity226
import CarmenQExact.Source15818Stationarity227

/-!
# Stationarity bridge shard 56 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn224 :
    stationarityAt source15818Data 224 = 0 := by
  change source15818StationarityValue224 = 0
  exact source15818StationarityValue224Zero

theorem source15818StationarityColumn225 :
    stationarityAt source15818Data 225 = 0 := by
  change source15818StationarityValue225 = 0
  exact source15818StationarityValue225Zero

theorem source15818StationarityColumn226 :
    stationarityAt source15818Data 226 = 0 := by
  change source15818StationarityValue226 = 0
  exact source15818StationarityValue226Zero

theorem source15818StationarityColumn227 :
    stationarityAt source15818Data 227 = 0 := by
  change source15818StationarityValue227 = 0
  exact source15818StationarityValue227Zero

end CarmenQExact
