import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 254 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row260 : Fin 3173 := ⟨260, by decide⟩
private def row775 : Fin 3173 := ⟨775, by decide⟩
private def row776 : Fin 3173 := ⟨776, by decide⟩
private def row779 : Fin 3173 := ⟨779, by decide⟩
private def row780 : Fin 3173 := ⟨780, by decide⟩

def source15818ObjectiveCoord254 : ℚ := q 0 1

def source15818Column254 : Array (RayEntry 3173) := #[
  { row := row260, value := q (-1) 1 },
  { row := row775, value := q 1 1 },
  { row := row776, value := q 1 1 },
  { row := row779, value := q (-5404319552844595) 9007199254740992 },
  { row := row780, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue254 : ℚ :=
  source15818Column254.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord254

theorem source15818StationarityValue254Zero :
    source15818StationarityValue254 = 0 := by
  decide +kernel

end CarmenQExact
