import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity164
import CarmenQExact.Source15818Stationarity165
import CarmenQExact.Source15818Stationarity166
import CarmenQExact.Source15818Stationarity167

/-!
# Stationarity bridge shard 41 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn164 :
    stationarityAt source15818Data 164 = 0 := by
  change source15818StationarityValue164 = 0
  exact source15818StationarityValue164Zero

theorem source15818StationarityColumn165 :
    stationarityAt source15818Data 165 = 0 := by
  change source15818StationarityValue165 = 0
  exact source15818StationarityValue165Zero

theorem source15818StationarityColumn166 :
    stationarityAt source15818Data 166 = 0 := by
  change source15818StationarityValue166 = 0
  exact source15818StationarityValue166Zero

theorem source15818StationarityColumn167 :
    stationarityAt source15818Data 167 = 0 := by
  change source15818StationarityValue167 = 0
  exact source15818StationarityValue167Zero

end CarmenQExact
