import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 232 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row238 : Fin 3173 := ⟨238, by decide⟩
private def row567 : Fin 3173 := ⟨567, by decide⟩
private def row568 : Fin 3173 := ⟨568, by decide⟩
private def row573 : Fin 3173 := ⟨573, by decide⟩
private def row862 : Fin 3173 := ⟨862, by decide⟩

def source15818ObjectiveCoord232 : ℚ := q 0 1

def source15818Column232 : Array (RayEntry 3173) := #[
  { row := row238, value := q (-1) 1 },
  { row := row567, value := q (-1) 1 },
  { row := row568, value := q (-1) 1 },
  { row := row573, value := q 1 1 },
  { row := row862, value := q (-1) 1 },
]

def source15818StationarityValue232 : ℚ :=
  source15818Column232.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord232

theorem source15818StationarityValue232Zero :
    source15818StationarityValue232 = 0 := by
  decide +kernel

end CarmenQExact
