import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 265 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row2 : Fin 3173 := ⟨2, by decide⟩
private def row554 : Fin 3173 := ⟨554, by decide⟩
private def row555 : Fin 3173 := ⟨555, by decide⟩
private def row564 : Fin 3173 := ⟨564, by decide⟩
private def row573 : Fin 3173 := ⟨573, by decide⟩
private def row582 : Fin 3173 := ⟨582, by decide⟩
private def row600 : Fin 3173 := ⟨600, by decide⟩
private def row804 : Fin 3173 := ⟨804, by decide⟩
private def row839 : Fin 3173 := ⟨839, by decide⟩
private def row840 : Fin 3173 := ⟨840, by decide⟩
private def row855 : Fin 3173 := ⟨855, by decide⟩
private def row856 : Fin 3173 := ⟨856, by decide⟩
private def row871 : Fin 3173 := ⟨871, by decide⟩
private def row872 : Fin 3173 := ⟨872, by decide⟩
private def row887 : Fin 3173 := ⟨887, by decide⟩
private def row888 : Fin 3173 := ⟨888, by decide⟩
private def row919 : Fin 3173 := ⟨919, by decide⟩
private def row920 : Fin 3173 := ⟨920, by decide⟩

def source15818ObjectiveCoord265 : ℚ := q 0 1

def source15818Column265 : Array (RayEntry 3173) := #[
  { row := row2, value := q 1 1 },
  { row := row554, value := q 1 1 },
  { row := row555, value := q 1 1 },
  { row := row564, value := q 77236096414237 140737488355328 },
  { row := row573, value := q 5817075445605485 18014398509481984 },
  { row := row582, value := q 420249975707923 4503599627370496 },
  { row := row600, value := q (-5871014167978597) 18014398509481984 },
  { row := row804, value := q (-1) 1 },
  { row := row839, value := q 1 1 },
  { row := row840, value := q 1 1 },
  { row := row855, value := q 77236096414237 140737488355328 },
  { row := row856, value := q 1 1 },
  { row := row871, value := q 5817075445605485 18014398509481984 },
  { row := row872, value := q (-6951886220902455) 18014398509481984 },
  { row := row887, value := q 420249975707923 4503599627370496 },
  { row := row888, value := q (-3343068085686235) 9007199254740992 },
  { row := row919, value := q (-5871014167978597) 18014398509481984 },
  { row := row920, value := q (-5392870869074357) 9007199254740992 },
]

def source15818StationarityValue265 : ℚ :=
  source15818Column265.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord265

theorem source15818StationarityValue265Zero :
    source15818StationarityValue265 = 0 := by
  decide +kernel

end CarmenQExact
