import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 176 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row182 : Fin 3173 := ⟨182, by decide⟩
private def row276 : Fin 3173 := ⟨276, by decide⟩
private def row337 : Fin 3173 := ⟨337, by decide⟩
private def row353 : Fin 3173 := ⟨353, by decide⟩
private def row365 : Fin 3173 := ⟨365, by decide⟩
private def row366 : Fin 3173 := ⟨366, by decide⟩
private def row747 : Fin 3173 := ⟨747, by decide⟩
private def row748 : Fin 3173 := ⟨748, by decide⟩

def source15818ObjectiveCoord176 : ℚ := q 0 1

def source15818Column176 : Array (RayEntry 3173) := #[
  { row := row182, value := q (-1) 1 },
  { row := row276, value := q 1 1 },
  { row := row337, value := q 261175671186813 281474976710656 },
  { row := row353, value := q (-2093748593682989) 2251799813685248 },
  { row := row365, value := q 2093748593682989 2251799813685248 },
  { row := row366, value := q (-261175671186813) 281474976710656 },
  { row := row747, value := q (-5404319552844595) 9007199254740992 },
  { row := row748, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue176 : ℚ :=
  source15818Column176.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord176

theorem source15818StationarityValue176Zero :
    source15818StationarityValue176 = 0 := by
  decide +kernel

end CarmenQExact
