import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity84
import CarmenQExact.Source15818Stationarity85
import CarmenQExact.Source15818Stationarity86
import CarmenQExact.Source15818Stationarity87

/-!
# Stationarity bridge shard 21 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn084 :
    stationarityAt source15818Data 84 = 0 := by
  change source15818StationarityValue084 = 0
  exact source15818StationarityValue084Zero

theorem source15818StationarityColumn085 :
    stationarityAt source15818Data 85 = 0 := by
  change source15818StationarityValue085 = 0
  exact source15818StationarityValue085Zero

theorem source15818StationarityColumn086 :
    stationarityAt source15818Data 86 = 0 := by
  change source15818StationarityValue086 = 0
  exact source15818StationarityValue086Zero

theorem source15818StationarityColumn087 :
    stationarityAt source15818Data 87 = 0 := by
  change source15818StationarityValue087 = 0
  exact source15818StationarityValue087Zero

end CarmenQExact
