import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity28
import CarmenQExact.Source15818Stationarity29
import CarmenQExact.Source15818Stationarity30
import CarmenQExact.Source15818Stationarity31

/-!
# Stationarity bridge shard 07 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn028 :
    stationarityAt source15818Data 28 = 0 := by
  change source15818StationarityValue028 = 0
  exact source15818StationarityValue028Zero

theorem source15818StationarityColumn029 :
    stationarityAt source15818Data 29 = 0 := by
  change source15818StationarityValue029 = 0
  exact source15818StationarityValue029Zero

theorem source15818StationarityColumn030 :
    stationarityAt source15818Data 30 = 0 := by
  change source15818StationarityValue030 = 0
  exact source15818StationarityValue030Zero

theorem source15818StationarityColumn031 :
    stationarityAt source15818Data 31 = 0 := by
  change source15818StationarityValue031 = 0
  exact source15818StationarityValue031Zero

end CarmenQExact
