import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 199 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row205 : Fin 3173 := ⟨205, by decide⟩
private def row299 : Fin 3173 := ⟨299, by decide⟩
private def row408 : Fin 3173 := ⟨408, by decide⟩
private def row424 : Fin 3173 := ⟨424, by decide⟩
private def row455 : Fin 3173 := ⟨455, by decide⟩
private def row456 : Fin 3173 := ⟨456, by decide⟩
private def row751 : Fin 3173 := ⟨751, by decide⟩
private def row752 : Fin 3173 := ⟨752, by decide⟩

def source15818ObjectiveCoord199 : ℚ := q 0 1

def source15818Column199 : Array (RayEntry 3173) := #[
  { row := row205, value := q (-1) 1 },
  { row := row299, value := q 1 1 },
  { row := row408, value := q 77829474067439 140737488355328 },
  { row := row424, value := q (-4993843966331245) 9007199254740992 },
  { row := row455, value := q 4993843966331245 9007199254740992 },
  { row := row456, value := q (-77829474067439) 140737488355328 },
  { row := row751, value := q (-5404319552844595) 9007199254740992 },
  { row := row752, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue199 : ℚ :=
  source15818Column199.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord199

theorem source15818StationarityValue199Zero :
    source15818StationarityValue199 = 0 := by
  decide +kernel

end CarmenQExact
