import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 200 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row206 : Fin 3173 := ⟨206, by decide⟩
private def row300 : Fin 3173 := ⟨300, by decide⟩
private def row457 : Fin 3173 := ⟨457, by decide⟩
private def row473 : Fin 3173 := ⟨473, by decide⟩
private def row489 : Fin 3173 := ⟨489, by decide⟩
private def row490 : Fin 3173 := ⟨490, by decide⟩
private def row757 : Fin 3173 := ⟨757, by decide⟩
private def row758 : Fin 3173 := ⟨758, by decide⟩

def source15818ObjectiveCoord200 : ℚ := q 0 1

def source15818Column200 : Array (RayEntry 3173) := #[
  { row := row206, value := q (-1) 1 },
  { row := row300, value := q 1 1 },
  { row := row457, value := q 4654212870180819 9007199254740992 },
  { row := row473, value := q (-4667021567102341) 9007199254740992 },
  { row := row489, value := q 4667021567102341 9007199254740992 },
  { row := row490, value := q (-4654212870180819) 9007199254740992 },
  { row := row757, value := q (-5404319552844595) 9007199254740992 },
  { row := row758, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue200 : ℚ :=
  source15818Column200.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord200

theorem source15818StationarityValue200Zero :
    source15818StationarityValue200 = 0 := by
  decide +kernel

end CarmenQExact
