import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 178 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row184 : Fin 3173 := ⟨184, by decide⟩
private def row278 : Fin 3173 := ⟨278, by decide⟩
private def row339 : Fin 3173 := ⟨339, by decide⟩
private def row355 : Fin 3173 := ⟨355, by decide⟩
private def row381 : Fin 3173 := ⟨381, by decide⟩
private def row382 : Fin 3173 := ⟨382, by decide⟩
private def row745 : Fin 3173 := ⟨745, by decide⟩
private def row746 : Fin 3173 := ⟨746, by decide⟩
private def row747 : Fin 3173 := ⟨747, by decide⟩
private def row748 : Fin 3173 := ⟨748, by decide⟩
private def row749 : Fin 3173 := ⟨749, by decide⟩
private def row750 : Fin 3173 := ⟨750, by decide⟩

def source15818ObjectiveCoord178 : ℚ := q 0 1

def source15818Column178 : Array (RayEntry 3173) := #[
  { row := row184, value := q (-1) 1 },
  { row := row278, value := q 1 1 },
  { row := row339, value := q 261175671186813 281474976710656 },
  { row := row355, value := q (-2093748593682989) 2251799813685248 },
  { row := row381, value := q 2093748593682989 2251799813685248 },
  { row := row382, value := q (-261175671186813) 281474976710656 },
  { row := row745, value := q 5404319552844595 9007199254740992 },
  { row := row746, value := q 2476979795053773 4503599627370496 },
  { row := row747, value := q 5404319552844595 9007199254740992 },
  { row := row748, value := q 2476979795053773 4503599627370496 },
  { row := row749, value := q 5404319552844595 9007199254740992 },
  { row := row750, value := q 2476979795053773 4503599627370496 },
]

def source15818StationarityValue178 : ℚ :=
  source15818Column178.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord178

theorem source15818StationarityValue178Zero :
    source15818StationarityValue178 = 0 := by
  decide +kernel

end CarmenQExact
