import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 222 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row228 : Fin 3173 := ⟨228, by decide⟩
private def row542 : Fin 3173 := ⟨542, by decide⟩
private def row543 : Fin 3173 := ⟨543, by decide⟩
private def row545 : Fin 3173 := ⟨545, by decide⟩
private def row824 : Fin 3173 := ⟨824, by decide⟩

def source15818ObjectiveCoord222 : ℚ := q 0 1

def source15818Column222 : Array (RayEntry 3173) := #[
  { row := row228, value := q (-1) 1 },
  { row := row542, value := q (-1) 1 },
  { row := row543, value := q (-1) 1 },
  { row := row545, value := q 1 1 },
  { row := row824, value := q (-1) 1 },
]

def source15818StationarityValue222 : ℚ :=
  source15818Column222.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord222

theorem source15818StationarityValue222Zero :
    source15818StationarityValue222 = 0 := by
  decide +kernel

end CarmenQExact
