import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity240
import CarmenQExact.Source15818Stationarity241
import CarmenQExact.Source15818Stationarity242
import CarmenQExact.Source15818Stationarity243

/-!
# Stationarity bridge shard 60 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn240 :
    stationarityAt source15818Data 240 = 0 := by
  change source15818StationarityValue240 = 0
  exact source15818StationarityValue240Zero

theorem source15818StationarityColumn241 :
    stationarityAt source15818Data 241 = 0 := by
  change source15818StationarityValue241 = 0
  exact source15818StationarityValue241Zero

theorem source15818StationarityColumn242 :
    stationarityAt source15818Data 242 = 0 := by
  change source15818StationarityValue242 = 0
  exact source15818StationarityValue242Zero

theorem source15818StationarityColumn243 :
    stationarityAt source15818Data 243 = 0 := by
  change source15818StationarityValue243 = 0
  exact source15818StationarityValue243Zero

end CarmenQExact
