import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity44
import CarmenQExact.Source15818Stationarity45
import CarmenQExact.Source15818Stationarity46
import CarmenQExact.Source15818Stationarity47

/-!
# Stationarity bridge shard 11 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn044 :
    stationarityAt source15818Data 44 = 0 := by
  change source15818StationarityValue044 = 0
  exact source15818StationarityValue044Zero

theorem source15818StationarityColumn045 :
    stationarityAt source15818Data 45 = 0 := by
  change source15818StationarityValue045 = 0
  exact source15818StationarityValue045Zero

theorem source15818StationarityColumn046 :
    stationarityAt source15818Data 46 = 0 := by
  change source15818StationarityValue046 = 0
  exact source15818StationarityValue046Zero

theorem source15818StationarityColumn047 :
    stationarityAt source15818Data 47 = 0 := by
  change source15818StationarityValue047 = 0
  exact source15818StationarityValue047Zero

end CarmenQExact
