import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity16
import CarmenQExact.Source15818Stationarity17
import CarmenQExact.Source15818Stationarity18
import CarmenQExact.Source15818Stationarity19

/-!
# Stationarity bridge shard 04 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn016 :
    stationarityAt source15818Data 16 = 0 := by
  change source15818StationarityValue016 = 0
  exact source15818StationarityValue016Zero

theorem source15818StationarityColumn017 :
    stationarityAt source15818Data 17 = 0 := by
  change source15818StationarityValue017 = 0
  exact source15818StationarityValue017Zero

theorem source15818StationarityColumn018 :
    stationarityAt source15818Data 18 = 0 := by
  change source15818StationarityValue018 = 0
  exact source15818StationarityValue018Zero

theorem source15818StationarityColumn019 :
    stationarityAt source15818Data 19 = 0 := by
  change source15818StationarityValue019 = 0
  exact source15818StationarityValue019Zero

end CarmenQExact
