import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 216 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row1 : Fin 3173 := ⟨1, by decide⟩
private def row222 : Fin 3173 := ⟨222, by decide⟩
private def row316 : Fin 3173 := ⟨316, by decide⟩
private def row319 : Fin 3173 := ⟨319, by decide⟩
private def row322 : Fin 3173 := ⟨322, by decide⟩
private def row324 : Fin 3173 := ⟨324, by decide⟩
private def row325 : Fin 3173 := ⟨325, by decide⟩
private def row326 : Fin 3173 := ⟨326, by decide⟩
private def row361 : Fin 3173 := ⟨361, by decide⟩
private def row362 : Fin 3173 := ⟨362, by decide⟩
private def row363 : Fin 3173 := ⟨363, by decide⟩
private def row364 : Fin 3173 := ⟨364, by decide⟩
private def row365 : Fin 3173 := ⟨365, by decide⟩
private def row366 : Fin 3173 := ⟨366, by decide⟩
private def row367 : Fin 3173 := ⟨367, by decide⟩
private def row368 : Fin 3173 := ⟨368, by decide⟩
private def row369 : Fin 3173 := ⟨369, by decide⟩
private def row370 : Fin 3173 := ⟨370, by decide⟩
private def row371 : Fin 3173 := ⟨371, by decide⟩
private def row372 : Fin 3173 := ⟨372, by decide⟩
private def row373 : Fin 3173 := ⟨373, by decide⟩
private def row374 : Fin 3173 := ⟨374, by decide⟩
private def row375 : Fin 3173 := ⟨375, by decide⟩
private def row376 : Fin 3173 := ⟨376, by decide⟩
private def row377 : Fin 3173 := ⟨377, by decide⟩
private def row378 : Fin 3173 := ⟨378, by decide⟩
private def row379 : Fin 3173 := ⟨379, by decide⟩
private def row380 : Fin 3173 := ⟨380, by decide⟩
private def row381 : Fin 3173 := ⟨381, by decide⟩
private def row382 : Fin 3173 := ⟨382, by decide⟩
private def row383 : Fin 3173 := ⟨383, by decide⟩
private def row384 : Fin 3173 := ⟨384, by decide⟩
private def row385 : Fin 3173 := ⟨385, by decide⟩
private def row386 : Fin 3173 := ⟨386, by decide⟩
private def row387 : Fin 3173 := ⟨387, by decide⟩
private def row388 : Fin 3173 := ⟨388, by decide⟩
private def row389 : Fin 3173 := ⟨389, by decide⟩
private def row390 : Fin 3173 := ⟨390, by decide⟩
private def row391 : Fin 3173 := ⟨391, by decide⟩
private def row392 : Fin 3173 := ⟨392, by decide⟩
private def row764 : Fin 3173 := ⟨764, by decide⟩
private def row770 : Fin 3173 := ⟨770, by decide⟩
private def row784 : Fin 3173 := ⟨784, by decide⟩
private def row796 : Fin 3173 := ⟨796, by decide⟩

def source15818ObjectiveCoord216 : ℚ := q 0 1

def source15818Column216 : Array (RayEntry 3173) := #[
  { row := row1, value := q 1 1 },
  { row := row222, value := q (-1) 1 },
  { row := row316, value := q (-1) 1 },
  { row := row319, value := q 1 1 },
  { row := row322, value := q (-1) 1 },
  { row := row324, value := q (-1) 1 },
  { row := row325, value := q (-1) 1 },
  { row := row326, value := q 1 1 },
  { row := row361, value := q 1 1 },
  { row := row362, value := q (-1) 1 },
  { row := row363, value := q 1 1 },
  { row := row364, value := q (-1) 1 },
  { row := row365, value := q 1 1 },
  { row := row366, value := q (-1) 1 },
  { row := row367, value := q 1 1 },
  { row := row368, value := q (-1) 1 },
  { row := row369, value := q 1 2 },
  { row := row370, value := q (-1) 2 },
  { row := row371, value := q 1 2 },
  { row := row372, value := q (-1) 2 },
  { row := row373, value := q 1 2 },
  { row := row374, value := q (-1) 2 },
  { row := row375, value := q 1 2 },
  { row := row376, value := q (-1) 2 },
  { row := row377, value := q 6004799503160661 18014398509481984 },
  { row := row378, value := q (-6004799503160661) 18014398509481984 },
  { row := row379, value := q 6004799503160661 18014398509481984 },
  { row := row380, value := q (-6004799503160661) 18014398509481984 },
  { row := row381, value := q 6004799503160661 18014398509481984 },
  { row := row382, value := q (-6004799503160661) 18014398509481984 },
  { row := row383, value := q 6004799503160661 18014398509481984 },
  { row := row384, value := q (-6004799503160661) 18014398509481984 },
  { row := row385, value := q 1 4 },
  { row := row386, value := q (-1) 4 },
  { row := row387, value := q 1 4 },
  { row := row388, value := q (-1) 4 },
  { row := row389, value := q 1 4 },
  { row := row390, value := q (-1) 4 },
  { row := row391, value := q 1 4 },
  { row := row392, value := q (-1) 4 },
  { row := row764, value := q 1 1 },
  { row := row770, value := q 1 1 },
  { row := row784, value := q (-1) 1 },
  { row := row796, value := q (-1) 1 },
]

def source15818StationarityValue216 : ℚ :=
  source15818Column216.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord216

theorem source15818StationarityValue216Zero :
    source15818StationarityValue216 = 0 := by
  decide +kernel

end CarmenQExact
