import CarmenQExact.Source15818Dimensions
import CarmenQExact.Source15818Indices
import CarmenQExact.Source15818DualCone
import CarmenQExact.Source15818Stationarity
import CarmenQExact.Source15818Upper

/-!
# Exact certificate for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

theorem source15818Exact : CertificateProof source15818Data :=
  { dimensions := source15818DimensionsOK
    indices := source15818IndicesOK
    dualCone := source15818DualCone
    stationarity := source15818Stationarity
    upper := source15818CertifiedUpperLtTarget }

end CarmenQExact
