import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 188 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row194 : Fin 3173 := ⟨194, by decide⟩
private def row288 : Fin 3173 := ⟨288, by decide⟩
private def row397 : Fin 3173 := ⟨397, by decide⟩
private def row413 : Fin 3173 := ⟨413, by decide⟩
private def row427 : Fin 3173 := ⟨427, by decide⟩
private def row428 : Fin 3173 := ⟨428, by decide⟩
private def row751 : Fin 3173 := ⟨751, by decide⟩
private def row752 : Fin 3173 := ⟨752, by decide⟩
private def row753 : Fin 3173 := ⟨753, by decide⟩
private def row754 : Fin 3173 := ⟨754, by decide⟩
private def row755 : Fin 3173 := ⟨755, by decide⟩
private def row756 : Fin 3173 := ⟨756, by decide⟩

def source15818ObjectiveCoord188 : ℚ := q 0 1

def source15818Column188 : Array (RayEntry 3173) := #[
  { row := row194, value := q (-1) 1 },
  { row := row288, value := q 1 1 },
  { row := row397, value := q 77829474067439 140737488355328 },
  { row := row413, value := q (-4993843966331245) 9007199254740992 },
  { row := row427, value := q 4993843966331245 9007199254740992 },
  { row := row428, value := q (-77829474067439) 140737488355328 },
  { row := row751, value := q 5404319552844595 9007199254740992 },
  { row := row752, value := q 2476979795053773 4503599627370496 },
  { row := row753, value := q 5404319552844595 9007199254740992 },
  { row := row754, value := q 2476979795053773 4503599627370496 },
  { row := row755, value := q 5404319552844595 9007199254740992 },
  { row := row756, value := q 2476979795053773 4503599627370496 },
]

def source15818StationarityValue188 : ℚ :=
  source15818Column188.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord188

theorem source15818StationarityValue188Zero :
    source15818StationarityValue188 = 0 := by
  decide +kernel

end CarmenQExact
