import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 218 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row1 : Fin 3173 := ⟨1, by decide⟩
private def row224 : Fin 3173 := ⟨224, by decide⟩
private def row318 : Fin 3173 := ⟨318, by decide⟩
private def row321 : Fin 3173 := ⟨321, by decide⟩
private def row323 : Fin 3173 := ⟨323, by decide⟩
private def row325 : Fin 3173 := ⟨325, by decide⟩
private def row326 : Fin 3173 := ⟨326, by decide⟩
private def row327 : Fin 3173 := ⟨327, by decide⟩
private def row328 : Fin 3173 := ⟨328, by decide⟩
private def row489 : Fin 3173 := ⟨489, by decide⟩
private def row490 : Fin 3173 := ⟨490, by decide⟩
private def row491 : Fin 3173 := ⟨491, by decide⟩
private def row492 : Fin 3173 := ⟨492, by decide⟩
private def row493 : Fin 3173 := ⟨493, by decide⟩
private def row494 : Fin 3173 := ⟨494, by decide⟩
private def row495 : Fin 3173 := ⟨495, by decide⟩
private def row496 : Fin 3173 := ⟨496, by decide⟩
private def row497 : Fin 3173 := ⟨497, by decide⟩
private def row498 : Fin 3173 := ⟨498, by decide⟩
private def row499 : Fin 3173 := ⟨499, by decide⟩
private def row500 : Fin 3173 := ⟨500, by decide⟩
private def row501 : Fin 3173 := ⟨501, by decide⟩
private def row502 : Fin 3173 := ⟨502, by decide⟩
private def row503 : Fin 3173 := ⟨503, by decide⟩
private def row504 : Fin 3173 := ⟨504, by decide⟩
private def row505 : Fin 3173 := ⟨505, by decide⟩
private def row506 : Fin 3173 := ⟨506, by decide⟩
private def row507 : Fin 3173 := ⟨507, by decide⟩
private def row508 : Fin 3173 := ⟨508, by decide⟩
private def row509 : Fin 3173 := ⟨509, by decide⟩
private def row510 : Fin 3173 := ⟨510, by decide⟩
private def row511 : Fin 3173 := ⟨511, by decide⟩
private def row512 : Fin 3173 := ⟨512, by decide⟩
private def row513 : Fin 3173 := ⟨513, by decide⟩
private def row514 : Fin 3173 := ⟨514, by decide⟩
private def row515 : Fin 3173 := ⟨515, by decide⟩
private def row516 : Fin 3173 := ⟨516, by decide⟩
private def row517 : Fin 3173 := ⟨517, by decide⟩
private def row518 : Fin 3173 := ⟨518, by decide⟩
private def row519 : Fin 3173 := ⟨519, by decide⟩
private def row520 : Fin 3173 := ⟨520, by decide⟩
private def row766 : Fin 3173 := ⟨766, by decide⟩
private def row778 : Fin 3173 := ⟨778, by decide⟩
private def row788 : Fin 3173 := ⟨788, by decide⟩
private def row794 : Fin 3173 := ⟨794, by decide⟩

def source15818ObjectiveCoord218 : ℚ := q 0 1

def source15818Column218 : Array (RayEntry 3173) := #[
  { row := row1, value := q 1 1 },
  { row := row224, value := q (-1) 1 },
  { row := row318, value := q (-1) 1 },
  { row := row321, value := q 1 1 },
  { row := row323, value := q 1 1 },
  { row := row325, value := q (-985) 512 },
  { row := row326, value := q 493 256 },
  { row := row327, value := q (-2579148085650963) 2251799813685248 },
  { row := row328, value := q 647125223355353 562949953421312 },
  { row := row489, value := q 1 1 },
  { row := row490, value := q (-1) 1 },
  { row := row491, value := q 1 1 },
  { row := row492, value := q (-1) 1 },
  { row := row493, value := q 1 1 },
  { row := row494, value := q (-1) 1 },
  { row := row495, value := q 1 1 },
  { row := row496, value := q (-1) 1 },
  { row := row497, value := q 1 2 },
  { row := row498, value := q (-1) 2 },
  { row := row499, value := q 1 2 },
  { row := row500, value := q (-1) 2 },
  { row := row501, value := q 1 2 },
  { row := row502, value := q (-1) 2 },
  { row := row503, value := q 1 2 },
  { row := row504, value := q (-1) 2 },
  { row := row505, value := q 3002399751580331 9007199254740992 },
  { row := row506, value := q (-3002399751580331) 9007199254740992 },
  { row := row507, value := q 3002399751580331 9007199254740992 },
  { row := row508, value := q (-3002399751580331) 9007199254740992 },
  { row := row509, value := q 3002399751580331 9007199254740992 },
  { row := row510, value := q (-3002399751580331) 9007199254740992 },
  { row := row511, value := q 3002399751580331 9007199254740992 },
  { row := row512, value := q (-3002399751580331) 9007199254740992 },
  { row := row513, value := q 1 4 },
  { row := row514, value := q (-1) 4 },
  { row := row515, value := q 1 4 },
  { row := row516, value := q (-1) 4 },
  { row := row517, value := q 1 4 },
  { row := row518, value := q (-1) 4 },
  { row := row519, value := q 1 4 },
  { row := row520, value := q (-1) 4 },
  { row := row766, value := q (-1) 1 },
  { row := row778, value := q (-1) 1 },
  { row := row788, value := q 1 1 },
  { row := row794, value := q 1 1 },
]

def source15818StationarityValue218 : ℚ :=
  source15818Column218.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord218

theorem source15818StationarityValue218Zero :
    source15818StationarityValue218 = 0 := by
  decide +kernel

end CarmenQExact
