import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 169 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row175 : Fin 3173 := ⟨175, by decide⟩
private def row269 : Fin 3173 := ⟨269, by decide⟩
private def row330 : Fin 3173 := ⟨330, by decide⟩
private def row346 : Fin 3173 := ⟨346, by decide⟩
private def row369 : Fin 3173 := ⟨369, by decide⟩
private def row370 : Fin 3173 := ⟨370, by decide⟩
private def row745 : Fin 3173 := ⟨745, by decide⟩
private def row746 : Fin 3173 := ⟨746, by decide⟩

def source15818ObjectiveCoord169 : ℚ := q 0 1

def source15818Column169 : Array (RayEntry 3173) := #[
  { row := row175, value := q (-1) 1 },
  { row := row269, value := q 1 1 },
  { row := row330, value := q 261175671186813 281474976710656 },
  { row := row346, value := q (-2093748593682989) 2251799813685248 },
  { row := row369, value := q 2093748593682989 2251799813685248 },
  { row := row370, value := q (-261175671186813) 281474976710656 },
  { row := row745, value := q (-5404319552844595) 9007199254740992 },
  { row := row746, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue169 : ℚ :=
  source15818Column169.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord169

theorem source15818StationarityValue169Zero :
    source15818StationarityValue169 = 0 := by
  decide +kernel

end CarmenQExact
