import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 270 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row544 : Fin 3173 := ⟨544, by decide⟩
private def row545 : Fin 3173 := ⟨545, by decide⟩
private def row555 : Fin 3173 := ⟨555, by decide⟩
private def row564 : Fin 3173 := ⟨564, by decide⟩
private def row573 : Fin 3173 := ⟨573, by decide⟩
private def row582 : Fin 3173 := ⟨582, by decide⟩
private def row600 : Fin 3173 := ⟨600, by decide⟩
private def row810 : Fin 3173 := ⟨810, by decide⟩
private def row839 : Fin 3173 := ⟨839, by decide⟩
private def row842 : Fin 3173 := ⟨842, by decide⟩
private def row855 : Fin 3173 := ⟨855, by decide⟩
private def row858 : Fin 3173 := ⟨858, by decide⟩
private def row871 : Fin 3173 := ⟨871, by decide⟩
private def row874 : Fin 3173 := ⟨874, by decide⟩
private def row887 : Fin 3173 := ⟨887, by decide⟩
private def row890 : Fin 3173 := ⟨890, by decide⟩
private def row906 : Fin 3173 := ⟨906, by decide⟩
private def row919 : Fin 3173 := ⟨919, by decide⟩
private def row922 : Fin 3173 := ⟨922, by decide⟩

def source15818ObjectiveCoord270 : ℚ := q 0 1

def source15818Column270 : Array (RayEntry 3173) := #[
  { row := row544, value := q 1 1 },
  { row := row545, value := q 1 1 },
  { row := row555, value := q 7461808180621107 18014398509481984 },
  { row := row564, value := q 6590813560681557 9007199254740992 },
  { row := row573, value := q 8545604522815913 18014398509481984 },
  { row := row582, value := q 3999055223702371 36028797018963968 },
  { row := row600, value := q 2783013294743753 9007199254740992 },
  { row := row810, value := q (-1) 1 },
  { row := row839, value := q 7461808180621107 18014398509481984 },
  { row := row842, value := q (-1) 1 },
  { row := row855, value := q 6590813560681557 9007199254740992 },
  { row := row858, value := q 1 1 },
  { row := row871, value := q 8545604522815913 18014398509481984 },
  { row := row874, value := q 1702117352237699 2251799813685248 },
  { row := row887, value := q 3999055223702371 36028797018963968 },
  { row := row890, value := q (-7953072375992153) 18014398509481984 },
  { row := row906, value := q 5447431651172879 9007199254740992 },
  { row := row919, value := q 2783013294743753 9007199254740992 },
  { row := row922, value := q 5112721889628029 9007199254740992 },
]

def source15818StationarityValue270 : ℚ :=
  source15818Column270.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord270

theorem source15818StationarityValue270Zero :
    source15818StationarityValue270 = 0 := by
  decide +kernel

end CarmenQExact
