import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity254
import CarmenQExact.Source15818Stationarity255
import CarmenQExact.Source15818Stationarity256
import CarmenQExact.Source15818Stationarity257

/-!
# Stationarity bridge shard 66 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn254 :
    stationarityAt source15818Data 254 = 0 := by
  change source15818StationarityValue254 = 0
  exact source15818StationarityValue254Zero

theorem source15818StationarityColumn255 :
    stationarityAt source15818Data 255 = 0 := by
  change source15818StationarityValue255 = 0
  exact source15818StationarityValue255Zero

theorem source15818StationarityColumn256 :
    stationarityAt source15818Data 256 = 0 := by
  change source15818StationarityValue256 = 0
  exact source15818StationarityValue256Zero

theorem source15818StationarityColumn257 :
    stationarityAt source15818Data 257 = 0 := by
  change source15818StationarityValue257 = 0
  exact source15818StationarityValue257Zero

end CarmenQExact
