import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity76
import CarmenQExact.Source15818Stationarity77
import CarmenQExact.Source15818Stationarity78
import CarmenQExact.Source15818Stationarity79

/-!
# Stationarity bridge shard 19 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn076 :
    stationarityAt source15818Data 76 = 0 := by
  change source15818StationarityValue076 = 0
  exact source15818StationarityValue076Zero

theorem source15818StationarityColumn077 :
    stationarityAt source15818Data 77 = 0 := by
  change source15818StationarityValue077 = 0
  exact source15818StationarityValue077Zero

theorem source15818StationarityColumn078 :
    stationarityAt source15818Data 78 = 0 := by
  change source15818StationarityValue078 = 0
  exact source15818StationarityValue078Zero

theorem source15818StationarityColumn079 :
    stationarityAt source15818Data 79 = 0 := by
  change source15818StationarityValue079 = 0
  exact source15818StationarityValue079Zero

end CarmenQExact
