import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 175 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row181 : Fin 3173 := ⟨181, by decide⟩
private def row275 : Fin 3173 := ⟨275, by decide⟩
private def row336 : Fin 3173 := ⟨336, by decide⟩
private def row352 : Fin 3173 := ⟨352, by decide⟩
private def row387 : Fin 3173 := ⟨387, by decide⟩
private def row388 : Fin 3173 := ⟨388, by decide⟩
private def row747 : Fin 3173 := ⟨747, by decide⟩
private def row748 : Fin 3173 := ⟨748, by decide⟩

def source15818ObjectiveCoord175 : ℚ := q 0 1

def source15818Column175 : Array (RayEntry 3173) := #[
  { row := row181, value := q (-1) 1 },
  { row := row275, value := q 1 1 },
  { row := row336, value := q 261175671186813 281474976710656 },
  { row := row352, value := q (-8374994374731957) 9007199254740992 },
  { row := row387, value := q 8374994374731957 9007199254740992 },
  { row := row388, value := q (-261175671186813) 281474976710656 },
  { row := row747, value := q (-5404319552844595) 9007199254740992 },
  { row := row748, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue175 : ℚ :=
  source15818Column175.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord175

theorem source15818StationarityValue175Zero :
    source15818StationarityValue175 = 0 := by
  decide +kernel

end CarmenQExact
