import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity136
import CarmenQExact.Source15818Stationarity137
import CarmenQExact.Source15818Stationarity138
import CarmenQExact.Source15818Stationarity139

/-!
# Stationarity bridge shard 34 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn136 :
    stationarityAt source15818Data 136 = 0 := by
  change source15818StationarityValue136 = 0
  exact source15818StationarityValue136Zero

theorem source15818StationarityColumn137 :
    stationarityAt source15818Data 137 = 0 := by
  change source15818StationarityValue137 = 0
  exact source15818StationarityValue137Zero

theorem source15818StationarityColumn138 :
    stationarityAt source15818Data 138 = 0 := by
  change source15818StationarityValue138 = 0
  exact source15818StationarityValue138Zero

theorem source15818StationarityColumn139 :
    stationarityAt source15818Data 139 = 0 := by
  change source15818StationarityValue139 = 0
  exact source15818StationarityValue139Zero

end CarmenQExact
