import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 168 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row174 : Fin 3173 := ⟨174, by decide⟩
private def row268 : Fin 3173 := ⟨268, by decide⟩
private def row329 : Fin 3173 := ⟨329, by decide⟩
private def row345 : Fin 3173 := ⟨345, by decide⟩
private def row361 : Fin 3173 := ⟨361, by decide⟩
private def row362 : Fin 3173 := ⟨362, by decide⟩
private def row745 : Fin 3173 := ⟨745, by decide⟩
private def row746 : Fin 3173 := ⟨746, by decide⟩
private def row747 : Fin 3173 := ⟨747, by decide⟩
private def row748 : Fin 3173 := ⟨748, by decide⟩
private def row749 : Fin 3173 := ⟨749, by decide⟩
private def row750 : Fin 3173 := ⟨750, by decide⟩

def source15818ObjectiveCoord168 : ℚ := q 0 1

def source15818Column168 : Array (RayEntry 3173) := #[
  { row := row174, value := q (-1) 1 },
  { row := row268, value := q 1 1 },
  { row := row329, value := q 261175671186813 281474976710656 },
  { row := row345, value := q (-8374994374731957) 9007199254740992 },
  { row := row361, value := q 8374994374731957 9007199254740992 },
  { row := row362, value := q (-261175671186813) 281474976710656 },
  { row := row745, value := q 5404319552844595 9007199254740992 },
  { row := row746, value := q 2476979795053773 4503599627370496 },
  { row := row747, value := q 5404319552844595 9007199254740992 },
  { row := row748, value := q 2476979795053773 4503599627370496 },
  { row := row749, value := q 5404319552844595 9007199254740992 },
  { row := row750, value := q 2476979795053773 4503599627370496 },
]

def source15818StationarityValue168 : ℚ :=
  source15818Column168.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord168

theorem source15818StationarityValue168Zero :
    source15818StationarityValue168 = 0 := by
  decide +kernel

end CarmenQExact
