import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 186 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row192 : Fin 3173 := ⟨192, by decide⟩
private def row286 : Fin 3173 := ⟨286, by decide⟩
private def row395 : Fin 3173 := ⟨395, by decide⟩
private def row411 : Fin 3173 := ⟨411, by decide⟩
private def row441 : Fin 3173 := ⟨441, by decide⟩
private def row442 : Fin 3173 := ⟨442, by decide⟩
private def row753 : Fin 3173 := ⟨753, by decide⟩
private def row754 : Fin 3173 := ⟨754, by decide⟩

def source15818ObjectiveCoord186 : ℚ := q 0 1

def source15818Column186 : Array (RayEntry 3173) := #[
  { row := row192, value := q (-1) 1 },
  { row := row286, value := q 1 1 },
  { row := row395, value := q 77829474067439 140737488355328 },
  { row := row411, value := q (-4993843966331245) 9007199254740992 },
  { row := row441, value := q 4993843966331245 9007199254740992 },
  { row := row442, value := q (-77829474067439) 140737488355328 },
  { row := row753, value := q (-5404319552844595) 9007199254740992 },
  { row := row754, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue186 : ℚ :=
  source15818Column186.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord186

theorem source15818StationarityValue186Zero :
    source15818StationarityValue186 = 0 := by
  decide +kernel

end CarmenQExact
