import CarmenQExact.Source15818Data

/-!
# Sparse dual upper bound for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818CertifiedUpperLtTarget :
    certifiedUpper source15818Data < source15818Data.target := by
  decide +kernel

end CarmenQExact
