import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 208 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row214 : Fin 3173 := ⟨214, by decide⟩
private def row308 : Fin 3173 := ⟨308, by decide⟩
private def row465 : Fin 3173 := ⟨465, by decide⟩
private def row481 : Fin 3173 := ⟨481, by decide⟩
private def row493 : Fin 3173 := ⟨493, by decide⟩
private def row494 : Fin 3173 := ⟨494, by decide⟩
private def row757 : Fin 3173 := ⟨757, by decide⟩
private def row758 : Fin 3173 := ⟨758, by decide⟩
private def row759 : Fin 3173 := ⟨759, by decide⟩
private def row760 : Fin 3173 := ⟨760, by decide⟩
private def row761 : Fin 3173 := ⟨761, by decide⟩
private def row762 : Fin 3173 := ⟨762, by decide⟩

def source15818ObjectiveCoord208 : ℚ := q 0 1

def source15818Column208 : Array (RayEntry 3173) := #[
  { row := row214, value := q (-1) 1 },
  { row := row308, value := q 1 1 },
  { row := row465, value := q 4654212870180819 9007199254740992 },
  { row := row481, value := q (-4667021567102341) 9007199254740992 },
  { row := row493, value := q 4667021567102341 9007199254740992 },
  { row := row494, value := q (-4654212870180819) 9007199254740992 },
  { row := row757, value := q 5404319552844595 9007199254740992 },
  { row := row758, value := q 2476979795053773 4503599627370496 },
  { row := row759, value := q 5404319552844595 9007199254740992 },
  { row := row760, value := q 2476979795053773 4503599627370496 },
  { row := row761, value := q 5404319552844595 9007199254740992 },
  { row := row762, value := q 2476979795053773 4503599627370496 },
]

def source15818StationarityValue208 : ℚ :=
  source15818Column208.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord208

theorem source15818StationarityValue208Zero :
    source15818StationarityValue208 = 0 := by
  decide +kernel

end CarmenQExact
