import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 259 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row265 : Fin 3173 := ⟨265, by decide⟩
private def row789 : Fin 3173 := ⟨789, by decide⟩
private def row790 : Fin 3173 := ⟨790, by decide⟩
private def row791 : Fin 3173 := ⟨791, by decide⟩
private def row792 : Fin 3173 := ⟨792, by decide⟩

def source15818ObjectiveCoord259 : ℚ := q 0 1

def source15818Column259 : Array (RayEntry 3173) := #[
  { row := row265, value := q (-1) 1 },
  { row := row789, value := q 1 1 },
  { row := row790, value := q 1 1 },
  { row := row791, value := q (-5404319552844595) 9007199254740992 },
  { row := row792, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue259 : ℚ :=
  source15818Column259.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord259

theorem source15818StationarityValue259Zero :
    source15818StationarityValue259 = 0 := by
  decide +kernel

end CarmenQExact
