import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 264 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row544 : Fin 3173 := ⟨544, by decide⟩
private def row545 : Fin 3173 := ⟨545, by decide⟩
private def row555 : Fin 3173 := ⟨555, by decide⟩
private def row564 : Fin 3173 := ⟨564, by decide⟩
private def row573 : Fin 3173 := ⟨573, by decide⟩
private def row582 : Fin 3173 := ⟨582, by decide⟩
private def row600 : Fin 3173 := ⟨600, by decide⟩
private def row802 : Fin 3173 := ⟨802, by decide⟩
private def row839 : Fin 3173 := ⟨839, by decide⟩
private def row842 : Fin 3173 := ⟨842, by decide⟩
private def row855 : Fin 3173 := ⟨855, by decide⟩
private def row858 : Fin 3173 := ⟨858, by decide⟩
private def row871 : Fin 3173 := ⟨871, by decide⟩
private def row874 : Fin 3173 := ⟨874, by decide⟩
private def row887 : Fin 3173 := ⟨887, by decide⟩
private def row890 : Fin 3173 := ⟨890, by decide⟩
private def row906 : Fin 3173 := ⟨906, by decide⟩
private def row919 : Fin 3173 := ⟨919, by decide⟩
private def row922 : Fin 3173 := ⟨922, by decide⟩

def source15818ObjectiveCoord264 : ℚ := q 0 1

def source15818Column264 : Array (RayEntry 3173) := #[
  { row := row544, value := q (-1) 1 },
  { row := row545, value := q (-1) 1 },
  { row := row555, value := q 7461808180621107 18014398509481984 },
  { row := row564, value := q (-6590813560681557) 9007199254740992 },
  { row := row573, value := q 5979042252613815 18014398509481984 },
  { row := row582, value := q 3793696303756565 72057594037927936 },
  { row := row600, value := q (-1327096525091787) 4503599627370496 },
  { row := row802, value := q (-1) 1 },
  { row := row839, value := q 7461808180621107 18014398509481984 },
  { row := row842, value := q (-1) 1 },
  { row := row855, value := q (-6590813560681557) 9007199254740992 },
  { row := row858, value := q (-1) 1 },
  { row := row871, value := q 5979042252613815 18014398509481984 },
  { row := row874, value := q 2381816649896375 4503599627370496 },
  { row := row887, value := q 3793696303756565 72057594037927936 },
  { row := row890, value := q (-3772333662396479) 18014398509481984 },
  { row := row906, value := q (-16661540748777) 70368744177664 },
  { row := row919, value := q (-1327096525091787) 4503599627370496 },
  { row := row922, value := q (-4876063988843295) 9007199254740992 },
]

def source15818StationarityValue264 : ℚ :=
  source15818Column264.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord264

theorem source15818StationarityValue264Zero :
    source15818StationarityValue264 = 0 := by
  decide +kernel

end CarmenQExact
