import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity212
import CarmenQExact.Source15818Stationarity213
import CarmenQExact.Source15818Stationarity214
import CarmenQExact.Source15818Stationarity215

/-!
# Stationarity bridge shard 53 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn212 :
    stationarityAt source15818Data 212 = 0 := by
  change source15818StationarityValue212 = 0
  exact source15818StationarityValue212Zero

theorem source15818StationarityColumn213 :
    stationarityAt source15818Data 213 = 0 := by
  change source15818StationarityValue213 = 0
  exact source15818StationarityValue213Zero

theorem source15818StationarityColumn214 :
    stationarityAt source15818Data 214 = 0 := by
  change source15818StationarityValue214 = 0
  exact source15818StationarityValue214Zero

theorem source15818StationarityColumn215 :
    stationarityAt source15818Data 215 = 0 := by
  change source15818StationarityValue215 = 0
  exact source15818StationarityValue215Zero

end CarmenQExact
