import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 226 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row232 : Fin 3173 := ⟨232, by decide⟩
private def row552 : Fin 3173 := ⟨552, by decide⟩
private def row553 : Fin 3173 := ⟨553, by decide⟩
private def row555 : Fin 3173 := ⟨555, by decide⟩
private def row836 : Fin 3173 := ⟨836, by decide⟩

def source15818ObjectiveCoord226 : ℚ := q 0 1

def source15818Column226 : Array (RayEntry 3173) := #[
  { row := row232, value := q (-1) 1 },
  { row := row552, value := q (-1) 1 },
  { row := row553, value := q (-1) 1 },
  { row := row555, value := q 1 1 },
  { row := row836, value := q (-1) 1 },
]

def source15818StationarityValue226 : ℚ :=
  source15818Column226.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord226

theorem source15818StationarityValue226Zero :
    source15818StationarityValue226 = 0 := by
  decide +kernel

end CarmenQExact
