import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity00
import CarmenQExact.Source15818Stationarity01
import CarmenQExact.Source15818Stationarity02
import CarmenQExact.Source15818Stationarity03

/-!
# Stationarity bridge shard 00 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn000 :
    stationarityAt source15818Data 0 = 0 := by
  change source15818StationarityValue000 = 0
  exact source15818StationarityValue000Zero

theorem source15818StationarityColumn001 :
    stationarityAt source15818Data 1 = 0 := by
  change source15818StationarityValue001 = 0
  exact source15818StationarityValue001Zero

theorem source15818StationarityColumn002 :
    stationarityAt source15818Data 2 = 0 := by
  change source15818StationarityValue002 = 0
  exact source15818StationarityValue002Zero

theorem source15818StationarityColumn003 :
    stationarityAt source15818Data 3 = 0 := by
  change source15818StationarityValue003 = 0
  exact source15818StationarityValue003Zero

end CarmenQExact
