import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 257 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row263 : Fin 3173 := ⟨263, by decide⟩
private def row783 : Fin 3173 := ⟨783, by decide⟩
private def row784 : Fin 3173 := ⟨784, by decide⟩
private def row785 : Fin 3173 := ⟨785, by decide⟩
private def row786 : Fin 3173 := ⟨786, by decide⟩

def source15818ObjectiveCoord257 : ℚ := q 0 1

def source15818Column257 : Array (RayEntry 3173) := #[
  { row := row263, value := q (-1) 1 },
  { row := row783, value := q 1 1 },
  { row := row784, value := q 1 1 },
  { row := row785, value := q (-5404319552844595) 9007199254740992 },
  { row := row786, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue257 : ℚ :=
  source15818Column257.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord257

theorem source15818StationarityValue257Zero :
    source15818StationarityValue257 = 0 := by
  decide +kernel

end CarmenQExact
