import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity124
import CarmenQExact.Source15818Stationarity125
import CarmenQExact.Source15818Stationarity126
import CarmenQExact.Source15818Stationarity127

/-!
# Stationarity bridge shard 31 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn124 :
    stationarityAt source15818Data 124 = 0 := by
  change source15818StationarityValue124 = 0
  exact source15818StationarityValue124Zero

theorem source15818StationarityColumn125 :
    stationarityAt source15818Data 125 = 0 := by
  change source15818StationarityValue125 = 0
  exact source15818StationarityValue125Zero

theorem source15818StationarityColumn126 :
    stationarityAt source15818Data 126 = 0 := by
  change source15818StationarityValue126 = 0
  exact source15818StationarityValue126Zero

theorem source15818StationarityColumn127 :
    stationarityAt source15818Data 127 = 0 := by
  change source15818StationarityValue127 = 0
  exact source15818StationarityValue127Zero

end CarmenQExact
