import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity250
import CarmenQExact.Source15818Stationarity251
import CarmenQExact.Source15818Stationarity252
import CarmenQExact.Source15818Stationarity253

/-!
# Stationarity bridge shard 65 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn250 :
    stationarityAt source15818Data 250 = 0 := by
  change source15818StationarityValue250 = 0
  exact source15818StationarityValue250Zero

theorem source15818StationarityColumn251 :
    stationarityAt source15818Data 251 = 0 := by
  change source15818StationarityValue251 = 0
  exact source15818StationarityValue251Zero

theorem source15818StationarityColumn252 :
    stationarityAt source15818Data 252 = 0 := by
  change source15818StationarityValue252 = 0
  exact source15818StationarityValue252Zero

theorem source15818StationarityColumn253 :
    stationarityAt source15818Data 253 = 0 := by
  change source15818StationarityValue253 = 0
  exact source15818StationarityValue253Zero

end CarmenQExact
