import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 221 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row227 : Fin 3173 := ⟨227, by decide⟩
private def row540 : Fin 3173 := ⟨540, by decide⟩
private def row541 : Fin 3173 := ⟨541, by decide⟩
private def row545 : Fin 3173 := ⟨545, by decide⟩
private def row821 : Fin 3173 := ⟨821, by decide⟩

def source15818ObjectiveCoord221 : ℚ := q 0 1

def source15818Column221 : Array (RayEntry 3173) := #[
  { row := row227, value := q (-1) 1 },
  { row := row540, value := q (-1) 1 },
  { row := row541, value := q (-1) 1 },
  { row := row545, value := q 1 1 },
  { row := row821, value := q (-1) 1 },
]

def source15818StationarityValue221 : ℚ :=
  source15818Column221.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord221

theorem source15818StationarityValue221Zero :
    source15818StationarityValue221 = 0 := by
  decide +kernel

end CarmenQExact
