import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 191 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row197 : Fin 3173 := ⟨197, by decide⟩
private def row291 : Fin 3173 := ⟨291, by decide⟩
private def row400 : Fin 3173 := ⟨400, by decide⟩
private def row416 : Fin 3173 := ⟨416, by decide⟩
private def row451 : Fin 3173 := ⟨451, by decide⟩
private def row452 : Fin 3173 := ⟨452, by decide⟩
private def row753 : Fin 3173 := ⟨753, by decide⟩
private def row754 : Fin 3173 := ⟨754, by decide⟩

def source15818ObjectiveCoord191 : ℚ := q 0 1

def source15818Column191 : Array (RayEntry 3173) := #[
  { row := row197, value := q (-1) 1 },
  { row := row291, value := q 1 1 },
  { row := row400, value := q 77829474067439 140737488355328 },
  { row := row416, value := q (-4993843966331245) 9007199254740992 },
  { row := row451, value := q 4993843966331245 9007199254740992 },
  { row := row452, value := q (-77829474067439) 140737488355328 },
  { row := row753, value := q (-5404319552844595) 9007199254740992 },
  { row := row754, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue191 : ℚ :=
  source15818Column191.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord191

theorem source15818StationarityValue191Zero :
    source15818StationarityValue191 = 0 := by
  decide +kernel

end CarmenQExact
