import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 182 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row188 : Fin 3173 := ⟨188, by decide⟩
private def row282 : Fin 3173 := ⟨282, by decide⟩
private def row343 : Fin 3173 := ⟨343, by decide⟩
private def row359 : Fin 3173 := ⟨359, by decide⟩
private def row383 : Fin 3173 := ⟨383, by decide⟩
private def row384 : Fin 3173 := ⟨384, by decide⟩
private def row745 : Fin 3173 := ⟨745, by decide⟩
private def row746 : Fin 3173 := ⟨746, by decide⟩

def source15818ObjectiveCoord182 : ℚ := q 0 1

def source15818Column182 : Array (RayEntry 3173) := #[
  { row := row188, value := q (-1) 1 },
  { row := row282, value := q 1 1 },
  { row := row343, value := q 261175671186813 281474976710656 },
  { row := row359, value := q (-2093748593682989) 2251799813685248 },
  { row := row383, value := q 2093748593682989 2251799813685248 },
  { row := row384, value := q (-261175671186813) 281474976710656 },
  { row := row745, value := q (-5404319552844595) 9007199254740992 },
  { row := row746, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue182 : ℚ :=
  source15818Column182.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord182

theorem source15818StationarityValue182Zero :
    source15818StationarityValue182 = 0 := by
  decide +kernel

end CarmenQExact
