import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity176
import CarmenQExact.Source15818Stationarity177
import CarmenQExact.Source15818Stationarity178
import CarmenQExact.Source15818Stationarity179

/-!
# Stationarity bridge shard 44 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn176 :
    stationarityAt source15818Data 176 = 0 := by
  change source15818StationarityValue176 = 0
  exact source15818StationarityValue176Zero

theorem source15818StationarityColumn177 :
    stationarityAt source15818Data 177 = 0 := by
  change source15818StationarityValue177 = 0
  exact source15818StationarityValue177Zero

theorem source15818StationarityColumn178 :
    stationarityAt source15818Data 178 = 0 := by
  change source15818StationarityValue178 = 0
  exact source15818StationarityValue178Zero

theorem source15818StationarityColumn179 :
    stationarityAt source15818Data 179 = 0 := by
  change source15818StationarityValue179 = 0
  exact source15818StationarityValue179Zero

end CarmenQExact
