import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity96
import CarmenQExact.Source15818Stationarity97
import CarmenQExact.Source15818Stationarity98
import CarmenQExact.Source15818Stationarity99

/-!
# Stationarity bridge shard 24 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn096 :
    stationarityAt source15818Data 96 = 0 := by
  change source15818StationarityValue096 = 0
  exact source15818StationarityValue096Zero

theorem source15818StationarityColumn097 :
    stationarityAt source15818Data 97 = 0 := by
  change source15818StationarityValue097 = 0
  exact source15818StationarityValue097Zero

theorem source15818StationarityColumn098 :
    stationarityAt source15818Data 98 = 0 := by
  change source15818StationarityValue098 = 0
  exact source15818StationarityValue098Zero

theorem source15818StationarityColumn099 :
    stationarityAt source15818Data 99 = 0 := by
  change source15818StationarityValue099 = 0
  exact source15818StationarityValue099Zero

end CarmenQExact
