import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity216
import CarmenQExact.Source15818Stationarity217
import CarmenQExact.Source15818Stationarity218
import CarmenQExact.Source15818Stationarity219

/-!
# Stationarity bridge shard 54 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn216 :
    stationarityAt source15818Data 216 = 0 := by
  change source15818StationarityValue216 = 0
  exact source15818StationarityValue216Zero

theorem source15818StationarityColumn217 :
    stationarityAt source15818Data 217 = 0 := by
  change source15818StationarityValue217 = 0
  exact source15818StationarityValue217Zero

theorem source15818StationarityColumn218 :
    stationarityAt source15818Data 218 = 0 := by
  change source15818StationarityValue218 = 0
  exact source15818StationarityValue218Zero

theorem source15818StationarityColumn219 :
    stationarityAt source15818Data 219 = 0 := by
  change source15818StationarityValue219 = 0
  exact source15818StationarityValue219Zero

end CarmenQExact
