import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 215 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row221 : Fin 3173 := ⟨221, by decide⟩
private def row315 : Fin 3173 := ⟨315, by decide⟩
private def row472 : Fin 3173 := ⟨472, by decide⟩
private def row488 : Fin 3173 := ⟨488, by decide⟩
private def row519 : Fin 3173 := ⟨519, by decide⟩
private def row520 : Fin 3173 := ⟨520, by decide⟩
private def row757 : Fin 3173 := ⟨757, by decide⟩
private def row758 : Fin 3173 := ⟨758, by decide⟩

def source15818ObjectiveCoord215 : ℚ := q 0 1

def source15818Column215 : Array (RayEntry 3173) := #[
  { row := row221, value := q (-1) 1 },
  { row := row315, value := q 1 1 },
  { row := row472, value := q 4654212870180819 9007199254740992 },
  { row := row488, value := q (-4667021567102341) 9007199254740992 },
  { row := row519, value := q 4667021567102341 9007199254740992 },
  { row := row520, value := q (-4654212870180819) 9007199254740992 },
  { row := row757, value := q (-5404319552844595) 9007199254740992 },
  { row := row758, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue215 : ℚ :=
  source15818Column215.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord215

theorem source15818StationarityValue215Zero :
    source15818StationarityValue215 = 0 := by
  decide +kernel

end CarmenQExact
