import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity248

/-!
# Stationarity bridge shard 63 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn248 :
    stationarityAt source15818Data 248 = 0 := by
  change source15818StationarityValue248 = 0
  exact source15818StationarityValue248Zero

end CarmenQExact
