import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity132
import CarmenQExact.Source15818Stationarity133
import CarmenQExact.Source15818Stationarity134
import CarmenQExact.Source15818Stationarity135

/-!
# Stationarity bridge shard 33 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn132 :
    stationarityAt source15818Data 132 = 0 := by
  change source15818StationarityValue132 = 0
  exact source15818StationarityValue132Zero

theorem source15818StationarityColumn133 :
    stationarityAt source15818Data 133 = 0 := by
  change source15818StationarityValue133 = 0
  exact source15818StationarityValue133Zero

theorem source15818StationarityColumn134 :
    stationarityAt source15818Data 134 = 0 := by
  change source15818StationarityValue134 = 0
  exact source15818StationarityValue134Zero

theorem source15818StationarityColumn135 :
    stationarityAt source15818Data 135 = 0 := by
  change source15818StationarityValue135 = 0
  exact source15818StationarityValue135Zero

end CarmenQExact
