import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity188
import CarmenQExact.Source15818Stationarity189
import CarmenQExact.Source15818Stationarity190
import CarmenQExact.Source15818Stationarity191

/-!
# Stationarity bridge shard 47 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn188 :
    stationarityAt source15818Data 188 = 0 := by
  change source15818StationarityValue188 = 0
  exact source15818StationarityValue188Zero

theorem source15818StationarityColumn189 :
    stationarityAt source15818Data 189 = 0 := by
  change source15818StationarityValue189 = 0
  exact source15818StationarityValue189Zero

theorem source15818StationarityColumn190 :
    stationarityAt source15818Data 190 = 0 := by
  change source15818StationarityValue190 = 0
  exact source15818StationarityValue190Zero

theorem source15818StationarityColumn191 :
    stationarityAt source15818Data 191 = 0 := by
  change source15818StationarityValue191 = 0
  exact source15818StationarityValue191Zero

end CarmenQExact
