import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity24
import CarmenQExact.Source15818Stationarity25
import CarmenQExact.Source15818Stationarity26
import CarmenQExact.Source15818Stationarity27

/-!
# Stationarity bridge shard 06 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn024 :
    stationarityAt source15818Data 24 = 0 := by
  change source15818StationarityValue024 = 0
  exact source15818StationarityValue024Zero

theorem source15818StationarityColumn025 :
    stationarityAt source15818Data 25 = 0 := by
  change source15818StationarityValue025 = 0
  exact source15818StationarityValue025Zero

theorem source15818StationarityColumn026 :
    stationarityAt source15818Data 26 = 0 := by
  change source15818StationarityValue026 = 0
  exact source15818StationarityValue026Zero

theorem source15818StationarityColumn027 :
    stationarityAt source15818Data 27 = 0 := by
  change source15818StationarityValue027 = 0
  exact source15818StationarityValue027Zero

end CarmenQExact
