import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 171 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row177 : Fin 3173 := ⟨177, by decide⟩
private def row271 : Fin 3173 := ⟨271, by decide⟩
private def row332 : Fin 3173 := ⟨332, by decide⟩
private def row348 : Fin 3173 := ⟨348, by decide⟩
private def row385 : Fin 3173 := ⟨385, by decide⟩
private def row386 : Fin 3173 := ⟨386, by decide⟩
private def row749 : Fin 3173 := ⟨749, by decide⟩
private def row750 : Fin 3173 := ⟨750, by decide⟩

def source15818ObjectiveCoord171 : ℚ := q 0 1

def source15818Column171 : Array (RayEntry 3173) := #[
  { row := row177, value := q (-1) 1 },
  { row := row271, value := q 1 1 },
  { row := row332, value := q 261175671186813 281474976710656 },
  { row := row348, value := q (-2093748593682989) 2251799813685248 },
  { row := row385, value := q 2093748593682989 2251799813685248 },
  { row := row386, value := q (-261175671186813) 281474976710656 },
  { row := row749, value := q (-5404319552844595) 9007199254740992 },
  { row := row750, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue171 : ℚ :=
  source15818Column171.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord171

theorem source15818StationarityValue171Zero :
    source15818StationarityValue171 = 0 := by
  decide +kernel

end CarmenQExact
