import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 194 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row200 : Fin 3173 := ⟨200, by decide⟩
private def row294 : Fin 3173 := ⟨294, by decide⟩
private def row403 : Fin 3173 := ⟨403, by decide⟩
private def row419 : Fin 3173 := ⟨419, by decide⟩
private def row445 : Fin 3173 := ⟨445, by decide⟩
private def row446 : Fin 3173 := ⟨446, by decide⟩
private def row751 : Fin 3173 := ⟨751, by decide⟩
private def row752 : Fin 3173 := ⟨752, by decide⟩

def source15818ObjectiveCoord194 : ℚ := q 0 1

def source15818Column194 : Array (RayEntry 3173) := #[
  { row := row200, value := q (-1) 1 },
  { row := row294, value := q 1 1 },
  { row := row403, value := q 77829474067439 140737488355328 },
  { row := row419, value := q (-1248460991582811) 2251799813685248 },
  { row := row445, value := q 1248460991582811 2251799813685248 },
  { row := row446, value := q (-77829474067439) 140737488355328 },
  { row := row751, value := q (-5404319552844595) 9007199254740992 },
  { row := row752, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue194 : ℚ :=
  source15818Column194.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord194

theorem source15818StationarityValue194Zero :
    source15818StationarityValue194 = 0 := by
  decide +kernel

end CarmenQExact
