import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 240 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row246 : Fin 3173 := ⟨246, by decide⟩
private def row585 : Fin 3173 := ⟨585, by decide⟩
private def row586 : Fin 3173 := ⟨586, by decide⟩
private def row591 : Fin 3173 := ⟨591, by decide⟩
private def row894 : Fin 3173 := ⟨894, by decide⟩

def source15818ObjectiveCoord240 : ℚ := q 0 1

def source15818Column240 : Array (RayEntry 3173) := #[
  { row := row246, value := q (-1) 1 },
  { row := row585, value := q (-1) 1 },
  { row := row586, value := q (-1) 1 },
  { row := row591, value := q 1 1 },
  { row := row894, value := q (-1) 1 },
]

def source15818StationarityValue240 : ℚ :=
  source15818Column240.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord240

theorem source15818StationarityValue240Zero :
    source15818StationarityValue240 = 0 := by
  decide +kernel

end CarmenQExact
