import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity72
import CarmenQExact.Source15818Stationarity73
import CarmenQExact.Source15818Stationarity74
import CarmenQExact.Source15818Stationarity75

/-!
# Stationarity bridge shard 18 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn072 :
    stationarityAt source15818Data 72 = 0 := by
  change source15818StationarityValue072 = 0
  exact source15818StationarityValue072Zero

theorem source15818StationarityColumn073 :
    stationarityAt source15818Data 73 = 0 := by
  change source15818StationarityValue073 = 0
  exact source15818StationarityValue073Zero

theorem source15818StationarityColumn074 :
    stationarityAt source15818Data 74 = 0 := by
  change source15818StationarityValue074 = 0
  exact source15818StationarityValue074Zero

theorem source15818StationarityColumn075 :
    stationarityAt source15818Data 75 = 0 := by
  change source15818StationarityValue075 = 0
  exact source15818StationarityValue075Zero

end CarmenQExact
