import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 271 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row2 : Fin 3173 := ⟨2, by decide⟩
private def row554 : Fin 3173 := ⟨554, by decide⟩
private def row555 : Fin 3173 := ⟨555, by decide⟩
private def row564 : Fin 3173 := ⟨564, by decide⟩
private def row573 : Fin 3173 := ⟨573, by decide⟩
private def row582 : Fin 3173 := ⟨582, by decide⟩
private def row600 : Fin 3173 := ⟨600, by decide⟩
private def row812 : Fin 3173 := ⟨812, by decide⟩
private def row839 : Fin 3173 := ⟨839, by decide⟩
private def row840 : Fin 3173 := ⟨840, by decide⟩
private def row855 : Fin 3173 := ⟨855, by decide⟩
private def row856 : Fin 3173 := ⟨856, by decide⟩
private def row871 : Fin 3173 := ⟨871, by decide⟩
private def row872 : Fin 3173 := ⟨872, by decide⟩
private def row887 : Fin 3173 := ⟨887, by decide⟩
private def row888 : Fin 3173 := ⟨888, by decide⟩
private def row904 : Fin 3173 := ⟨904, by decide⟩
private def row919 : Fin 3173 := ⟨919, by decide⟩
private def row920 : Fin 3173 := ⟨920, by decide⟩

def source15818ObjectiveCoord271 : ℚ := q 0 1

def source15818Column271 : Array (RayEntry 3173) := #[
  { row := row2, value := q (-1) 1 },
  { row := row554, value := q 1 1 },
  { row := row555, value := q 1 1 },
  { row := row564, value := q (-77236096414237) 140737488355328 },
  { row := row573, value := q (-5610869370562079) 151115727451828646838272 },
  { row := row582, value := q (-3576226802236361) 18014398509481984 },
  { row := row600, value := q (-6356380331433097) 72057594037927936 },
  { row := row812, value := q (-1) 1 },
  { row := row839, value := q 1 1 },
  { row := row840, value := q 1 1 },
  { row := row855, value := q (-77236096414237) 140737488355328 },
  { row := row856, value := q (-1) 1 },
  { row := row871, value := q (-5610869370562079) 151115727451828646838272 },
  { row := row872, value := q 6705452908292837 151115727451828646838272 },
  { row := row887, value := q (-3576226802236361) 18014398509481984 },
  { row := row888, value := q 3556088750984643 4503599627370496 },
  { row := row904, value := q 3424427496437499 4503599627370496 },
  { row := row919, value := q (-6356380331433097) 72057594037927936 },
  { row := row920, value := q (-2919354079326395) 18014398509481984 },
]

def source15818StationarityValue271 : ℚ :=
  source15818Column271.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord271

theorem source15818StationarityValue271Zero :
    source15818StationarityValue271 = 0 := by
  decide +kernel

end CarmenQExact
