import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 213 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row219 : Fin 3173 := ⟨219, by decide⟩
private def row313 : Fin 3173 := ⟨313, by decide⟩
private def row470 : Fin 3173 := ⟨470, by decide⟩
private def row486 : Fin 3173 := ⟨486, by decide⟩
private def row503 : Fin 3173 := ⟨503, by decide⟩
private def row504 : Fin 3173 := ⟨504, by decide⟩
private def row757 : Fin 3173 := ⟨757, by decide⟩
private def row758 : Fin 3173 := ⟨758, by decide⟩
private def row759 : Fin 3173 := ⟨759, by decide⟩
private def row760 : Fin 3173 := ⟨760, by decide⟩
private def row761 : Fin 3173 := ⟨761, by decide⟩
private def row762 : Fin 3173 := ⟨762, by decide⟩

def source15818ObjectiveCoord213 : ℚ := q 0 1

def source15818Column213 : Array (RayEntry 3173) := #[
  { row := row219, value := q (-1) 1 },
  { row := row313, value := q 1 1 },
  { row := row470, value := q 4654212870180819 9007199254740992 },
  { row := row486, value := q (-4667021567102341) 9007199254740992 },
  { row := row503, value := q 4667021567102341 9007199254740992 },
  { row := row504, value := q (-4654212870180819) 9007199254740992 },
  { row := row757, value := q 5404319552844595 9007199254740992 },
  { row := row758, value := q 2476979795053773 4503599627370496 },
  { row := row759, value := q 5404319552844595 9007199254740992 },
  { row := row760, value := q 2476979795053773 4503599627370496 },
  { row := row761, value := q 5404319552844595 9007199254740992 },
  { row := row762, value := q 2476979795053773 4503599627370496 },
]

def source15818StationarityValue213 : ℚ :=
  source15818Column213.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord213

theorem source15818StationarityValue213Zero :
    source15818StationarityValue213 = 0 := by
  decide +kernel

end CarmenQExact
