import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity52
import CarmenQExact.Source15818Stationarity53
import CarmenQExact.Source15818Stationarity54
import CarmenQExact.Source15818Stationarity55

/-!
# Stationarity bridge shard 13 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn052 :
    stationarityAt source15818Data 52 = 0 := by
  change source15818StationarityValue052 = 0
  exact source15818StationarityValue052Zero

theorem source15818StationarityColumn053 :
    stationarityAt source15818Data 53 = 0 := by
  change source15818StationarityValue053 = 0
  exact source15818StationarityValue053Zero

theorem source15818StationarityColumn054 :
    stationarityAt source15818Data 54 = 0 := by
  change source15818StationarityValue054 = 0
  exact source15818StationarityValue054Zero

theorem source15818StationarityColumn055 :
    stationarityAt source15818Data 55 = 0 := by
  change source15818StationarityValue055 = 0
  exact source15818StationarityValue055Zero

end CarmenQExact
