import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 174 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row180 : Fin 3173 := ⟨180, by decide⟩
private def row274 : Fin 3173 := ⟨274, by decide⟩
private def row335 : Fin 3173 := ⟨335, by decide⟩
private def row351 : Fin 3173 := ⟨351, by decide⟩
private def row379 : Fin 3173 := ⟨379, by decide⟩
private def row380 : Fin 3173 := ⟨380, by decide⟩
private def row749 : Fin 3173 := ⟨749, by decide⟩
private def row750 : Fin 3173 := ⟨750, by decide⟩

def source15818ObjectiveCoord174 : ℚ := q 0 1

def source15818Column174 : Array (RayEntry 3173) := #[
  { row := row180, value := q (-1) 1 },
  { row := row274, value := q 1 1 },
  { row := row335, value := q 261175671186813 281474976710656 },
  { row := row351, value := q (-2093748593682989) 2251799813685248 },
  { row := row379, value := q 2093748593682989 2251799813685248 },
  { row := row380, value := q (-261175671186813) 281474976710656 },
  { row := row749, value := q (-5404319552844595) 9007199254740992 },
  { row := row750, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue174 : ℚ :=
  source15818Column174.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord174

theorem source15818StationarityValue174Zero :
    source15818StationarityValue174 = 0 := by
  decide +kernel

end CarmenQExact
