import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity64
import CarmenQExact.Source15818Stationarity65
import CarmenQExact.Source15818Stationarity66
import CarmenQExact.Source15818Stationarity67

/-!
# Stationarity bridge shard 16 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn064 :
    stationarityAt source15818Data 64 = 0 := by
  change source15818StationarityValue064 = 0
  exact source15818StationarityValue064Zero

theorem source15818StationarityColumn065 :
    stationarityAt source15818Data 65 = 0 := by
  change source15818StationarityValue065 = 0
  exact source15818StationarityValue065Zero

theorem source15818StationarityColumn066 :
    stationarityAt source15818Data 66 = 0 := by
  change source15818StationarityValue066 = 0
  exact source15818StationarityValue066Zero

theorem source15818StationarityColumn067 :
    stationarityAt source15818Data 67 = 0 := by
  change source15818StationarityValue067 = 0
  exact source15818StationarityValue067Zero

end CarmenQExact
