import CarmenQExact.Source15818Nonnegative
import CarmenQExact.Source15818Soc

/-!
# Product-cone certificate for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

theorem source15818DualCone :
    rationalProductConeDual (rationalDualAt source15818Data.dual)
      source15818Data.zeroDim source15818Data.nonnegativeDim
      source15818Data.socSizes.toList := by
  exact rationalProductConeDual_of_parts
    (rationalDualAt source15818Data.dual) source15818Data.zeroDim
    source15818Data.nonnegativeDim source15818Data.socSizes.toList
    source15818Nonnegative source15818Soc

end CarmenQExact
