import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 230 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row236 : Fin 3173 := ⟨236, by decide⟩
private def row562 : Fin 3173 := ⟨562, by decide⟩
private def row563 : Fin 3173 := ⟨563, by decide⟩
private def row564 : Fin 3173 := ⟨564, by decide⟩
private def row852 : Fin 3173 := ⟨852, by decide⟩

def source15818ObjectiveCoord230 : ℚ := q 0 1

def source15818Column230 : Array (RayEntry 3173) := #[
  { row := row236, value := q (-1) 1 },
  { row := row562, value := q (-1) 1 },
  { row := row563, value := q (-1) 1 },
  { row := row564, value := q 1 1 },
  { row := row852, value := q (-1) 1 },
]

def source15818StationarityValue230 : ℚ :=
  source15818Column230.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord230

theorem source15818StationarityValue230Zero :
    source15818StationarityValue230 = 0 := by
  decide +kernel

end CarmenQExact
