import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 233 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row239 : Fin 3173 := ⟨239, by decide⟩
private def row569 : Fin 3173 := ⟨569, by decide⟩
private def row570 : Fin 3173 := ⟨570, by decide⟩
private def row573 : Fin 3173 := ⟨573, by decide⟩
private def row865 : Fin 3173 := ⟨865, by decide⟩

def source15818ObjectiveCoord233 : ℚ := q 0 1

def source15818Column233 : Array (RayEntry 3173) := #[
  { row := row239, value := q (-1) 1 },
  { row := row569, value := q (-1) 1 },
  { row := row570, value := q (-1) 1 },
  { row := row573, value := q 1 1 },
  { row := row865, value := q (-1) 1 },
]

def source15818StationarityValue233 : ℚ :=
  source15818Column233.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord233

theorem source15818StationarityValue233Zero :
    source15818StationarityValue233 = 0 := by
  decide +kernel

end CarmenQExact
