import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity204
import CarmenQExact.Source15818Stationarity205
import CarmenQExact.Source15818Stationarity206
import CarmenQExact.Source15818Stationarity207

/-!
# Stationarity bridge shard 51 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn204 :
    stationarityAt source15818Data 204 = 0 := by
  change source15818StationarityValue204 = 0
  exact source15818StationarityValue204Zero

theorem source15818StationarityColumn205 :
    stationarityAt source15818Data 205 = 0 := by
  change source15818StationarityValue205 = 0
  exact source15818StationarityValue205Zero

theorem source15818StationarityColumn206 :
    stationarityAt source15818Data 206 = 0 := by
  change source15818StationarityValue206 = 0
  exact source15818StationarityValue206Zero

theorem source15818StationarityColumn207 :
    stationarityAt source15818Data 207 = 0 := by
  change source15818StationarityValue207 = 0
  exact source15818StationarityValue207Zero

end CarmenQExact
