import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 220 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row226 : Fin 3173 := ⟨226, by decide⟩
private def row538 : Fin 3173 := ⟨538, by decide⟩
private def row539 : Fin 3173 := ⟨539, by decide⟩
private def row545 : Fin 3173 := ⟨545, by decide⟩
private def row818 : Fin 3173 := ⟨818, by decide⟩

def source15818ObjectiveCoord220 : ℚ := q 0 1

def source15818Column220 : Array (RayEntry 3173) := #[
  { row := row226, value := q (-1) 1 },
  { row := row538, value := q (-1) 1 },
  { row := row539, value := q (-1) 1 },
  { row := row545, value := q 1 1 },
  { row := row818, value := q (-1) 1 },
]

def source15818StationarityValue220 : ℚ :=
  source15818Column220.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord220

theorem source15818StationarityValue220Zero :
    source15818StationarityValue220 = 0 := by
  decide +kernel

end CarmenQExact
