import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 236 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row242 : Fin 3173 := ⟨242, by decide⟩
private def row576 : Fin 3173 := ⟨576, by decide⟩
private def row577 : Fin 3173 := ⟨577, by decide⟩
private def row582 : Fin 3173 := ⟨582, by decide⟩
private def row878 : Fin 3173 := ⟨878, by decide⟩

def source15818ObjectiveCoord236 : ℚ := q 0 1

def source15818Column236 : Array (RayEntry 3173) := #[
  { row := row242, value := q (-1) 1 },
  { row := row576, value := q (-1) 1 },
  { row := row577, value := q (-1) 1 },
  { row := row582, value := q 1 1 },
  { row := row878, value := q (-1) 1 },
]

def source15818StationarityValue236 : ℚ :=
  source15818Column236.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord236

theorem source15818StationarityValue236Zero :
    source15818StationarityValue236 = 0 := by
  decide +kernel

end CarmenQExact
