import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity32
import CarmenQExact.Source15818Stationarity33
import CarmenQExact.Source15818Stationarity34
import CarmenQExact.Source15818Stationarity35

/-!
# Stationarity bridge shard 08 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn032 :
    stationarityAt source15818Data 32 = 0 := by
  change source15818StationarityValue032 = 0
  exact source15818StationarityValue032Zero

theorem source15818StationarityColumn033 :
    stationarityAt source15818Data 33 = 0 := by
  change source15818StationarityValue033 = 0
  exact source15818StationarityValue033Zero

theorem source15818StationarityColumn034 :
    stationarityAt source15818Data 34 = 0 := by
  change source15818StationarityValue034 = 0
  exact source15818StationarityValue034Zero

theorem source15818StationarityColumn035 :
    stationarityAt source15818Data 35 = 0 := by
  change source15818StationarityValue035 = 0
  exact source15818StationarityValue035Zero

end CarmenQExact
