import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 250 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row256 : Fin 3173 := ⟨256, by decide⟩
private def row763 : Fin 3173 := ⟨763, by decide⟩
private def row764 : Fin 3173 := ⟨764, by decide⟩
private def row767 : Fin 3173 := ⟨767, by decide⟩
private def row768 : Fin 3173 := ⟨768, by decide⟩

def source15818ObjectiveCoord250 : ℚ := q 0 1

def source15818Column250 : Array (RayEntry 3173) := #[
  { row := row256, value := q (-1) 1 },
  { row := row763, value := q 1 1 },
  { row := row764, value := q 1 1 },
  { row := row767, value := q (-5404319552844595) 9007199254740992 },
  { row := row768, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue250 : ℚ :=
  source15818Column250.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord250

theorem source15818StationarityValue250Zero :
    source15818StationarityValue250 = 0 := by
  decide +kernel

end CarmenQExact
