import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 244 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row250 : Fin 3173 := ⟨250, by decide⟩
private def row594 : Fin 3173 := ⟨594, by decide⟩
private def row595 : Fin 3173 := ⟨595, by decide⟩
private def row600 : Fin 3173 := ⟨600, by decide⟩
private def row910 : Fin 3173 := ⟨910, by decide⟩

def source15818ObjectiveCoord244 : ℚ := q 0 1

def source15818Column244 : Array (RayEntry 3173) := #[
  { row := row250, value := q (-1) 1 },
  { row := row594, value := q (-1) 1 },
  { row := row595, value := q (-1) 1 },
  { row := row600, value := q 1 1 },
  { row := row910, value := q (-1) 1 },
]

def source15818StationarityValue244 : ℚ :=
  source15818Column244.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord244

theorem source15818StationarityValue244Zero :
    source15818StationarityValue244 = 0 := by
  decide +kernel

end CarmenQExact
