import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 273 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row544 : Fin 3173 := ⟨544, by decide⟩
private def row545 : Fin 3173 := ⟨545, by decide⟩
private def row555 : Fin 3173 := ⟨555, by decide⟩
private def row564 : Fin 3173 := ⟨564, by decide⟩
private def row573 : Fin 3173 := ⟨573, by decide⟩
private def row582 : Fin 3173 := ⟨582, by decide⟩
private def row600 : Fin 3173 := ⟨600, by decide⟩
private def row814 : Fin 3173 := ⟨814, by decide⟩
private def row839 : Fin 3173 := ⟨839, by decide⟩
private def row842 : Fin 3173 := ⟨842, by decide⟩
private def row855 : Fin 3173 := ⟨855, by decide⟩
private def row858 : Fin 3173 := ⟨858, by decide⟩
private def row871 : Fin 3173 := ⟨871, by decide⟩
private def row874 : Fin 3173 := ⟨874, by decide⟩
private def row887 : Fin 3173 := ⟨887, by decide⟩
private def row890 : Fin 3173 := ⟨890, by decide⟩
private def row906 : Fin 3173 := ⟨906, by decide⟩
private def row919 : Fin 3173 := ⟨919, by decide⟩
private def row922 : Fin 3173 := ⟨922, by decide⟩

def source15818ObjectiveCoord273 : ℚ := q 0 1

def source15818Column273 : Array (RayEntry 3173) := #[
  { row := row544, value := q 1 1 },
  { row := row545, value := q 1 1 },
  { row := row555, value := q (-7461808180621107) 18014398509481984 },
  { row := row564, value := q (-6590813560681557) 9007199254740992 },
  { row := row573, value := q 4208152027921559 151115727451828646838272 },
  { row := row582, value := q (-3576226802236361) 18014398509481984 },
  { row := row600, value := q (-6356380331433097) 72057594037927936 },
  { row := row814, value := q (-1) 1 },
  { row := row839, value := q (-7461808180621107) 18014398509481984 },
  { row := row842, value := q 1 1 },
  { row := row855, value := q (-6590813560681557) 9007199254740992 },
  { row := row858, value := q (-1) 1 },
  { row := row871, value := q 4208152027921559 151115727451828646838272 },
  { row := row874, value := q 6705452908292837 151115727451828646838272 },
  { row := row887, value := q (-3576226802236361) 18014398509481984 },
  { row := row890, value := q 3556088750984643 4503599627370496 },
  { row := row906, value := q 3424427496437499 4503599627370496 },
  { row := row919, value := q (-6356380331433097) 72057594037927936 },
  { row := row922, value := q (-2919354079326395) 18014398509481984 },
]

def source15818StationarityValue273 : ℚ :=
  source15818Column273.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord273

theorem source15818StationarityValue273Zero :
    source15818StationarityValue273 = 0 := by
  decide +kernel

end CarmenQExact
