import CarmenQExact.Source15818Data

/-!
# Nonnegative-cone shard 04 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818NonnegativeShard04 :
    rationalNonnegativeSegment (rationalDualAt source15818Data.dual)
      262 64 := by
  apply nonnegativeRangeOK_sound
  decide +kernel

end CarmenQExact
