import CarmenQExact.Source15818Data
import CarmenQExact.Source15818Stationarity116
import CarmenQExact.Source15818Stationarity117
import CarmenQExact.Source15818Stationarity118
import CarmenQExact.Source15818Stationarity119

/-!
# Stationarity bridge shard 29 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

theorem source15818StationarityColumn116 :
    stationarityAt source15818Data 116 = 0 := by
  change source15818StationarityValue116 = 0
  exact source15818StationarityValue116Zero

theorem source15818StationarityColumn117 :
    stationarityAt source15818Data 117 = 0 := by
  change source15818StationarityValue117 = 0
  exact source15818StationarityValue117Zero

theorem source15818StationarityColumn118 :
    stationarityAt source15818Data 118 = 0 := by
  change source15818StationarityValue118 = 0
  exact source15818StationarityValue118Zero

theorem source15818StationarityColumn119 :
    stationarityAt source15818Data 119 = 0 := by
  change source15818StationarityValue119 = 0
  exact source15818StationarityValue119Zero

end CarmenQExact
