import CarmenQExact.Source15818DualData

/-!
# Stationarity arithmetic shard 214 for source cell 15818

Generated by `export_exact_socp_certificate_lean.py`.
-/

namespace CarmenQExact

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

private def q (numerator : Int) (denominator : Nat) : ℚ :=
  (numerator : ℚ) / (denominator : ℚ)

private def row220 : Fin 3173 := ⟨220, by decide⟩
private def row314 : Fin 3173 := ⟨314, by decide⟩
private def row471 : Fin 3173 := ⟨471, by decide⟩
private def row487 : Fin 3173 := ⟨487, by decide⟩
private def row511 : Fin 3173 := ⟨511, by decide⟩
private def row512 : Fin 3173 := ⟨512, by decide⟩
private def row759 : Fin 3173 := ⟨759, by decide⟩
private def row760 : Fin 3173 := ⟨760, by decide⟩

def source15818ObjectiveCoord214 : ℚ := q 0 1

def source15818Column214 : Array (RayEntry 3173) := #[
  { row := row220, value := q (-1) 1 },
  { row := row314, value := q 1 1 },
  { row := row471, value := q 4654212870180819 9007199254740992 },
  { row := row487, value := q (-1166755391775585) 2251799813685248 },
  { row := row511, value := q 1166755391775585 2251799813685248 },
  { row := row512, value := q (-4654212870180819) 9007199254740992 },
  { row := row759, value := q (-5404319552844595) 9007199254740992 },
  { row := row760, value := q (-2476979795053773) 4503599627370496 },
]

def source15818StationarityValue214 : ℚ :=
  source15818Column214.foldl
    (fun total entry =>
      total + entry.value * source15818Dual entry.row)
    source15818ObjectiveCoord214

theorem source15818StationarityValue214Zero :
    source15818StationarityValue214 = 0 := by
  decide +kernel

end CarmenQExact
